Mozilla/5.0 (X11; U; AIX 0043031B4C00; en-US; rv:1.2.1) Gecko/20021209
OS: AIX

Amiga-AWeb/3.5.07 beta
Agent Type: browser
Browser Name: Amiga Aweb
OS: Amiga OS

AmigaVoyager/2.95 (compatible; MC680x0; AmigaOS)
Agent Type: browser
Browser Name: Amiga Voyager
OS: Amiga OS

Opera/9.80 (Android; Linux; Opera Mobi/49; U; en) Presto/2.4.18 Version/10.00
Agent Type: mobile browser
OS: Android
Bot Name: Opera Mobile

Mozilla/5.0 (Linux; U; Android 2.1; en-us; Nexus One Build/ERD62) AppleWebKit/530.17 (KHTML, like Gecko) Version/4.0 Mobile Safari/530.17
OS: Android

Mozilla/5.0 (Linux; U; Android 2.1-update1; en-au; HTC_Desire_A8183 V1.16.841.1 Build/ERE27) AppleWebKit/530.17 (KHTML, like Gecko) Version/4.0 Mobile Safari/530.17
Agent Type: mobile browser
OS: Android
Bot Name: Android Webkit

Mozilla/5.0 (Linux; U; Android 1.5; en-gb; T-Mobile G1 Build/CRC1) AppleWebKit/528.5+ (KHTML, like Gecko) Version/3.1.2 Mobile Safari/525.20.1
OS: Android

Mozilla/5.0 (compatible; Origyn Web Browser; AROS; x86_64; U) AppleWebKit/525.1+ (KHTML, like Gecko, Safari/525.1+)
OS: AROS

Mozilla/5.0 (BeOS; U; BeOS BeBox; fr; rv:1.9) Gecko/2008052906 BonEcho/2.0
OS: BeOS

Mozilla/3.0 (compatible; NetPositive/2.1.1; BeOS)
Agent Type: browser
Browser Name: NetPositive
OS: BeOS

Mozilla/5.0 (X11; U; CrOS i686 9.10.0; en-US) AppleWebKit/532.5 (KHTML, like Gecko) Chrome/4.0.253.0 Safari/532.5
OS: Chromium OS

Mozilla/5.0 (Danger hiptop 4.7; U; rv:1.7.12) Gecko/20050920
Agent Type: mobile browser
OS: Danger Hiptop
Bot Name: NetFront

Mozilla/5.0 (compatible; Konqueror/4.1; DragonFly) KHTML/4.1.4 (like Gecko)
OS: DragonFly BSD

Mozilla/5.0 (X11; U; DragonFly i386; de; rv:1.9.1) Gecko/20090720 Firefox/3.5.1
OS: DragonFly BSD

Mozilla/5.0 (X11; U; FreeBSD i386; pl; rv:1.8.1.12) Gecko/20080213 Epiphany/2.20 Firefox/2.0.0.12
OS: FreeBSD

Mozilla/5.0 (X11; U; FreeBSD amd64; en-US; rv:1.8.0.8) Gecko/20061116 Firefox/1.5.0.8
OS: FreeBSD

Mozilla/5.0 (BeOS; U; Haiku BePC; en-US; rv:1.8.1.21pre) Gecko/20090218 BonEcho/2.0.0.21pre
OS: Haiku OS

Mozilla/5.0 (X11; U; HP-UX 9000/785; es-ES; rv:1.0.1) Gecko/20020827 Netscape/7.0
OS: HP-UX

Mozilla/5.0 (iPad; U; CPU OS 3_2_1 like Mac OS X; en-us) AppleWebKit/531.21.10 (KHTML, like Gecko) Mobile/7B405
OS: iPhone OS

Mozilla/5.0 (iPhone; U; CPU iPhone OS 2_0_1 like Mac OS X; en-us) AppleWebKit/525.18.1 (KHTML, like Gecko) Version/3.1.1 Mobile/5B108 Safari/525.20
OS: iPhone OS

Opera/9.80 (iPhone; Opera Mini/5.0.0176/764; U; en) Presto/2.4.15
Agent Type: mobile browser
OS: iPhone OS
Bot Name: Opera Mini

Mozilla/5.0 (iPhone; U; CPU like Mac OS X; en) AppleWebKit/420+ (KHTML, like Gecko) Version/3.0 Mobile/1A543a Safari/419.3
OS: iPhone OS

Mozilla/4.8C-SGI [en] (X11; U; IRIX64 6.5 IP27)
OS: IRIX

Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.9.1.7) Gecko/20100106 Jolicloud/alpha (robby) Firefox/3.5.7
OS: Jolicloud

Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.9.1.3) Gecko/20090911 Jolicloud/alpha (robby) Firefox/3.5.3
OS: Jolicloud

HotJava/1.0.1/JRE1.1.x
OS: JVM (Java)

Java/1.4.2_03
OS: JVM (Java)

Mozilla/5.0 (X11; U; Linux i686; en-gb) AppleWebKit/525.1+ (KHTML, like Gecko, Safari/525.1+) epiphany-webkit
OS: Linux

Uzbl (X11; U; Arch Linux i686; de-DE) Webkit/1.1.10
OS: Linux

Midori/0.1.8 (X11; Arch Linux x86_64; U; en-us) WebKit/532+
OS: Linux

Mozilla/5.0 (X11; U; Linux x86_64; en-US; rv:1.9.0.5) Gecko/2008121911 CentOS/3.0.5-1.el5.centos Firefox/3.0.5
OS: Linux

Mozilla/5.0 (X11; U; Linux x86_64; en-US; rv:1.8.0.12) Gecko/20080419 CentOS/1.5.0.12-0.15.el4.centos Firefox/1.5.0.12 pango-text
OS: Linux

Mozilla/5.0 (compatible; Konqueror/3.5; Linux; x86_64) KHTML/3.5.5 (like Gecko) (Debian)
OS: Linux

Mozilla/5.0 (X11; U; Linux i686; de; rv:1.9.1.5) Gecko/20091112 Iceweasel/3.5.5 (like Firefox/3.5.5; Debian-3.5.5-1)
OS: Linux

Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.8.0.6) Gecko/20060905 Fedora/1.5.0.6-10 Firefox/1.5.0.6 pango-text
OS: Linux

Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.9.0.8) Gecko Fedora/1.9.0.8-1.fc10 Kazehakase/0.5.6
Agent Type: browser
Browser Name: Kazehakase
OS: Linux

ELinks (0.11.3; Linux 2.6.23-gentoo-r6 i686; 128x48)
OS: Linux

Mozilla/5.0 (X11; U; Linux Gentoo i686; pl; rv:1.8.0.8) Gecko/20061219 Firefox/1.5.0.8
OS: Linux

ELinks/0.9.3 (textmode; Linux 2.6.9-kanotix-8 i686; 127x41)
OS: Linux

Mozilla/5.0(X11; U; Linux armv7l; fr-FR; rv:1.9.2a1pre) Gecko/20091127 Firefox/3.5 Maemo Browser 1.5.6 RX-51 N900
OS: Linux

Mozilla/5.0 (X11; U; Linux x86_64; en-US; rv:1.9.0.7) Gecko/2009031120 Mandriva/1.9.0.7-0.1mdv2009.0 (2009.0) Firefox/3.0.7
OS: Linux

Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.8.1.11) Gecko/20070914 Mandriva/2.0.0.11-1.1mdv2007.0 (2007.0) Firefox/2.0.0.11
OS: Linux

Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.9.0.9) Gecko/2009042113 Linux Mint/6 (Felicia) Firefox/3.0.9
OS: Linux

Opera/9.64 (X11; Linux i686; U; Linux Mint; nb) Presto/2.1.1
OS: Linux

Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.9.0.18) Gecko/2010020406 Red Hat/3.0.18-1.el5_4 Firefox/3.18
OS: Linux

Wget/1.9+cvs-stable (Red Hat modified)
OS: Linux

Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.9.1.2) Gecko/20090729 Slackware/13.0 Firefox/3.5.2
OS: Linux

Mozilla/5.0 (X11; U; Linux x86_64; zh-cn) AppleWebKit/531.2+ (KHTML, like Gecko) Safari/531.2+ Epiphany/2.28.0 SUSE/2.28.0-2.4
OS: Linux

Mozilla/5.0 (X11; U; Linux i686; de; rv:1.9.1.1) Gecko/20090714 SUSE/3.5.1-1.1 Firefox/3.5.1
OS: Linux

Mozilla/5.0 (X11; U; Linux x86_64; en; rv:1.9.0.14) Gecko/20080528 Ubuntu/9.10 (karmic) Epiphany/2.22 Firefox/3.0
OS: Linux

Mozilla/5.0 (X11; U; Linux x86_64; zh-TW; rv:1.9.0.8) Gecko/2009032712 Ubuntu/8.04 (hardy) Firefox/3.0.8 GTB5
OS: Linux

Mozilla/5.0 (Macintosh; U; PPC Mac OS X Mach-O; en-US; rv:1.5b) Gecko/20030917 Camino/0.7+
OS: Mac OS X

Mozilla/5.0 (Macintosh; U; PPC Mac OS X; en-US; rv:1.0.1) Gecko/20021104 Chimera/0.6
OS: Mac OS X

Miro/2.0.4 (http://www.getmiro.com/; Darwin 10.3.0 i386)
OS: Mac OS X
OS Version: 10.3

Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10.4; en-US; rv:1.9.1b3pre) Gecko/20090223 SeaMonkey/2.0a3
OS: Mac OS X
OS Version: 10.4

Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_5_5; en-us) AppleWebKit/525.26.2 (KHTML, like Gecko) Version/3.2 Safari/525.26.12
OS: Mac OS X
OS Version: 10.5

Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10.5; en; rv:1.9.0.8pre) Gecko/2009022800 Camino/2.0b3pre
OS: Mac OS X
OS Version: 10.5

Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_6_2; en-US) AppleWebKit/533.1 (KHTML, like Gecko) Chrome/5.0.329.0 Safari/533.1
OS: Mac OS X
OS Version: 10.6

Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10.6; en-US; rv:1.9.1.6) Gecko/20091201 Firefox/3.5.6 (.NET CLR 3.5.30729)
OS: Mac OS X
OS Version: 10.6

Links (2.1pre26; Minix 3 i686; 228x66)
OS: MINIX
OS Version: 3 

Links (2.1pre26; Minix 3 i686; 80x20)
OS: MINIX
OS Version: 3 

Mozilla/5.0 (compatible; Origyn Web Browser; MorphOS; PPC; U) AppleWebKit/528.5+ (KHTML, like Gecko, Safari/528.5+)
Agent Type: browser
Browser Name: OWB
OS: MorphOS

Mozilla/4.0 WebTV/2.6 (compatible; MSIE 4.0)
OS: MSN TV (WebTV)

Mozilla/5.0 (X11; U; NetBSD; en-US; rv:1.8.1.6) Gecko/20080115 Firefox/2.0.0.6
OS: NetBSD

NetSurf/1.2 (NetBSD; i386; NetBSD 4.99.59 i386)
OS: NetBSD

Opera/9.30 (Nintendo Wii; U; ; 2047-7; fr)
OS: Nintendo Wii

Mozilla/5.0 (X11; U; OpenBSD i386; en-US; rv:1.7.10) Gecko/20050919 (No IDN) Firefox/1.0.6
OS: OpenBSD

Mozilla/5.0 (compatible; Konqueror/4.1; OpenBSD) KHTML/4.1.4 (like Gecko)
Agent Type: browser
Browser Name: Konqueror
OS: OpenBSD

Opera/9.22 (X11; OpenBSD i386; U; en)
OS: OpenBSD

Mozilla/4.61 [de] (OS/2; U)
OS: OS/2

Mozilla/4.61 [en] (OS/2; U)
OS: OS/2

Mozilla/5.0 (OS/2; U; Warp 4.5; en-US; rv:1.8.0.7) Gecko/20060910 MultiZilla/1.8.2.0i SeaMonkey/1.0.5
OS: OS/2 Warp

Mozilla/5.0 (OS/2; U; Warp 4.5; en-US; rv:1.8.1.3pre) Gecko/20070307 SeaMonkey/1.1.1
OS: OS/2 Warp

Mozilla/5.0 (OS/2; U; Warp 4.5; en-US; rv:1.7.12) Gecko/20050922 Firefox/1.0.7
OS: OS/2 Warp

CorePlayer/1.0 (Palm OS 5.4.9; ARM Intel PXA27x; en) CorePlayer/1.3.2_6909
Agent Type: multimedia player
OS: Palm OS
Bot Name: CorePlayer

CorePlayer/1.0 (Palm OS 5.4.9; ARM Intel PXA27x; en) CorePlayer/1.3.2_6909
OS: Palm OS

Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.9.1.2) Gecko/20090803 PCLinuxOS/1.9.1-3pclos2009 (2009) Firefox/3.5.3
OS: PClinuxOS

Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.9.2) Gecko/20100127 PCLinuxOS/1.9.2-3pclos2010 (2010) Firefox/3.6
OS: PClinuxOS

Mozilla/5.0 (Photon; U; QNX x86pc; en-US; rv:1.6) Gecko/20040429
OS: QNX x86pc

Mozilla/5.0 (Photon; U; QNX x86pc; en-US; rv:1.6) Gecko/20040429
OS: QNX x86pc

Mozilla/4.79 [en] (X11; U; SunOS 5.10 i86pc)
OS: Solaris

Mozilla/5.0 (X11; U; SunOS sun4u; en-US; rv:1.8.1.11) Gecko/20080118 Firefox/2.0.0.11
OS: Solaris

Mozilla/5.0 (X11; U; SunOS sun4m; en-US; rv:1.4b) Gecko/20030517 Mozilla Firebird/0.6
OS: Solaris

Mozilla/5.0 (compatible; U; ABrowse 0.6; Syllable) AppleWebKit/420+ (KHTML, like Gecko)
Agent Type: browser
Browser Name: ABrowse
OS: Syllable

Mozilla/5.0 (compatible; ABrowse 0.4; Syllable)
Agent Type: browser
Browser Name: ABrowse
OS: Syllable

Opera/9.80 (S60; SymbOS; Opera Mobi/352; U; de) Presto/2.4.15 Version/10.00
Agent Type: mobile browser
OS: Symbian OS
Bot Name: Opera Mobile

Mozilla/5.0 (webOS/1.0; U; en-US) AppleWebKit/525.27.1 (KHTML, like Gecko) Version/1.0 Safari/525.27.1 Pre/1.0
Agent Type: mobile browser
OS: webOS
Bot Name: Palm Pre web browser

Mozilla/5.0 (webOS/1.4.1.1; U; en-US) AppleWebKit/532.2 (KHTML, like Gecko) Version/1.0 Safari/532.2 Pre/1.0
OS: webOS

Mozilla/4.0 (compatible; MSIE 5.0; Windows 2000) Opera 6.0  [en]
OS: Windows
OS Version: 2000

Mozilla/4.0 (compatible; MSIE 5.01; Windows NT 5.0; SV1; .NET CLR 1.1.4322; .NET CLR 1.0.3705; .NET CLR 2.0.50727)
OS: Windows
OS Version: 2000

Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 5.2; WOW64; Trident/4.0; uZard/1.0; Server_KO_SKT)
OS: Windows
OS Version: 2003 Server

NCSA_Mosaic/2.0 (Windows 3.1)
Agent Type: browser
Browser Name: NCSA Mosaic
OS: Windows
OS Version: 3.x

Mozilla/1.22 (compatible; MSIE 2.0; Windows 3.1)
OS: Windows
OS Version: 3.x

Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.1; WOW64; Trident/4.0; GTB6.4; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; OfficeLiveConnector.1.3; OfficeLivePatch.0.0; .NET CLR 1.1.4322)
OS: Windows
OS Version: 7

Mozilla/5.0 (Windows; U; Windows NT 6.1; sk; rv:1.9.1.7) Gecko/20091221 Firefox/3.5.7
OS: Windows
OS Version: 7

Mozilla/4.0 (compatible; MSIE 4.01; Windows 95)
OS: Windows
OS Version: 95

Mozilla/4.0 (compatible; MSIE 5.0; Windows 95) Opera 6.02  [en]
OS: Windows
OS Version: 95

Mozilla/4.0 (compatible; MSIE 5.5; AOL 6.0; Windows 95)
OS: Windows
OS Version: 95

Mozilla/4.7 [en] (Win95; I)
OS: Windows
OS Version: 95

Mozilla/5.0 (Windows; U; Win95; en-US; rv:1.5) Gecko/20031007 Firebird/0.7
Agent Type: browser
Browser Name: Firebird (old name for Firefox)
OS: Windows
OS Version: 95

Mozilla/5.0 (Windows; U; Windows 98; en-US; rv:1.8.1.8pre) Gecko/20071019 Firefox/2.0.0.8 Navigator/9.0.0.1
OS: Windows
OS Version: 98

Mozilla/4.0 (compatible; MSIE 6.0b; Windows 98; YComp 5.0.0.0)
OS: Windows
OS Version: 98

Mozilla/4.0 (compatible; MSIE 4.01; Windows 98)
OS: Windows
OS Version: 98

Mozilla/5.0 (Windows; U; Windows CE 5.1; rv:1.8.1a3) Gecko/20060610 Minimo/0.016
Agent Type: mobile browser
OS: Windows
OS Version: CE
Bot Name: Minimo

Mozilla/4.0 (compatible; MSIE 4.01; Windows CE; 176x220)
OS: Windows
OS Version: CE

Mozilla/4.0 (compatible; MSIE 5.0; Windows ME) Opera 6.0  [de]
OS: Windows
OS Version: ME

Mozilla/5.0 (Windows; U; Win 9x 4.90; de-DE; rv:0.9.4.1) Gecko/20020314 Netscape6/6.2.2
OS: Windows
OS Version: ME

Mozilla/4.0 (compatible; MSIE 5.5; Windows 98; Win 9x 4.90; Wanadoo 5.1; Wanadoo 5.3; Wanadoo 5.5)
OS: Windows
OS Version: ME

Opera/9.80 (Windows Mobile; WCE; Opera Mobi/WMD-50430; U; en-GB) Presto/2.4.13 Version/10.00
Agent Type: mobile browser
OS: Windows
OS Version: Mobile
Bot Name: Opera Mobile

Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 4; SV1)
OS: Windows
OS Version: NT

HTC_HD2_T9193 Opera/9.7 (Windows NT 5.1; U; en) V1.49.841.1 (71528)
Agent Type: mobile browser
OS: Windows
OS Version: Phone 7
Bot Name: Opera Mobile

Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.0; Trident/4.0; SLCC1; .NET CLR 2.0.50727; .NET CLR 1.1.4322; InfoPath.2; .NET CLR 3.5.21022; .NET CLR 3.5.30729; MS-RTC LM 8; OfficeLiveConnector.1.4; OfficeLivePatch.1.3; .NET CLR 3.0.30729)
Agent Type: browser
Browser Name: IE
OS: Windows
OS Version: Vista

Mozilla/5.0 (Windows; U; Windows NT 5.1; cs; rv:1.9.1.8) Gecko/20100202 Firefox/3.5.8
OS: Windows
OS Version: XP

Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 5.1; )
OS: Windows
OS Version: XP

Mozilla/5.0 (PLAYSTATION 3; 1.00)
OS: XrossMediaBar (XMB)

Mozilla/4.0 (PSP (PlayStation Portable); 2.00)
Agent Type: mobile browser
OS: XrossMediaBar (XMB)
Bot Name: NetFront

Mozilla/5.0 (PLAYSTATION 3; 1.90)
Agent Type: mobile browser
OS: XrossMediaBar (XMB)
Bot Name: NetFront

Mozilla/4.0 (compatible; MSIE 6.0; Windows 98; Win 9x 4.90; http://www.Abolimba.de)
Agent Type: browser
Browser Name: Abolimba

Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1; JyxoToolbar1.0; http://www.Abolimba.de; .NET CLR 2.0.50727; .NET CLR 3.0.04506.648; .NET CLR 3.5.21022; .NET CLR 1.1.4322)
Agent Type: browser
Browser Name: Abolimba

Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1; Acoo Browser; .NET CLR 1.1.4322; .NET CLR 2.0.50727)
Agent Type: browser
Browser Name: Acoo Browser

Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.0; Acoo Browser; SLCC1; .NET CLR 2.0.50727; Media Center PC 5.0; .NET CLR 3.0.04506)
Agent Type: browser
Browser Name: Acoo Browser

Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 5.1; Acoo Browser; InfoPath.2; .NET CLR 2.0.50727; Alexa Toolbar)
Agent Type: browser
Browser Name: Acoo Browser

amaya/9.52 libwww/5.4.0
Agent Type: browser
Browser Name: Amaya

amaya/11.1 libwww/5.4.0
Agent Type: browser
Browser Name: Amaya

AmigaVoyager/3.4.4 (MorphOS/PPC native)
Agent Type: browser
Browser Name: Amiga Voyager

Mozilla/4.0 (compatible; MSIE 7.0; AOL 7.0; Windows NT 5.1; FunWebProducts)
Agent Type: browser
Browser Name: AOL Explorer

Mozilla/4.0 (compatible; MSIE 6.0; AOL 8.0; Windows NT 5.1; SV1)
Agent Type: browser
Browser Name: AOL Explorer

Mozilla/4.0 (compatible; MSIE 7.0; AOL 9.0; Windows NT 5.1; .NET CLR 1.1.4322; Zango 10.1.181.0)
Agent Type: browser
Browser Name: AOL Explorer

Mozilla/4.0 (compatible; MSIE 6.0; AOL 6.0; Windows NT 5.1)
Agent Type: browser
Browser Name: AOL Explorer

Mozilla/4.0 (compatible; MSIE 7.0; AOL 9.5; AOLBuild 4337.35; Windows NT 5.1; .NET CLR 1.1.4322; .NET CLR 2.0.50727)
Agent Type: browser
Browser Name: AOL Explorer

Mozilla/5.0 (Windows; U; Windows NT 5.1; zh-CN) AppleWebKit/523.15 (KHTML, like Gecko, Safari/419.3) Arora/0.3 (Change: 287 c9dfb30)
Agent Type: browser
Browser Name: Arora

Mozilla/5.0 (X11; U; Linux; en-US) AppleWebKit/527+ (KHTML, like Gecko, Safari/419.3) Arora/0.6
Agent Type: browser
Browser Name: Arora

Mozilla/5.0 (X11; U; Linux; C -) AppleWebKit/523.15 (KHTML, like Gecko, Safari/419.3) Arora/0.5
Agent Type: browser
Browser Name: Arora

Avant Browser (http://www.avantbrowser.com)
Agent Type: browser
Browser Name: Avant Browser

Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1; JyxoToolbar1.0;  Embedded Web Browser from: http://bsalsa.com/; Avant Browser; .NET CLR 2.0.50727; .NET CLR 3.0.04506.648; .NET CLR 3.5.21022; .NET CLR 1.1.4322)
Agent Type: browser
Browser Name: Avant Browser

Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 5.1; GTB5; Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1) ; Avant Browser)
Agent Type: browser
Browser Name: Avant Browser

Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; Avant Browser; Avant Browser; .NET CLR 1.1.4322; .NET CLR 2.0.50727; InfoPath.1)
Agent Type: browser
Browser Name: Avant Browser

Mozilla/5.0 (Windows; U; WinNT; en; Preview) Gecko/20020603 Beonex/0.8-stable
Agent Type: browser
Browser Name: Beonex

Mozilla/5.0 (Windows; U; WinNT; en; rv:1.0.2) Gecko/20030311 Beonex/0.8.2-stable
Agent Type: browser
Browser Name: Beonex

Mozilla/5.0 (Windows; U; Win9x; en; Stable) Gecko/20020911 Beonex/0.8.1-stable
Agent Type: browser
Browser Name: Beonex

Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.9) Gecko/2008120120 Blackbird/0.9991
Agent Type: browser
Browser Name: Blackbird

Mozilla/5.0 (X11; 78; CentOS; US-en) AppleWebKit/527+ (KHTML, like Gecko) Bolt/0.862 Version/3.0 Safari/523.15
Agent Type: browser
Browser Name: Bolt

Mozilla/4.61 [en] (X11; U; ) - BrowseX (2.0.0 Windows)
Agent Type: browser
Browser Name: BrowseX

Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1; Browzar)
Agent Type: browser
Browser Name: Browzar

Bunjalloo/0.7.6(Nintendo DS;U;en)
Agent Type: browser
Browser Name: Bunjalloo

Bunjalloo/0.7.4(Nintendo DS;U;en)
Agent Type: browser
Browser Name: Bunjalloo

Mozilla/5.0 (Macintosh; U; PPC Mac OS X Mach-O; en-US; rv:1.7.2) Gecko/20040825 Camino/0.8.1
Agent Type: browser
Browser Name: Camino

Mozilla/5.0 (Macintosh; U; Intel Mac OS X Mach-O; en; rv:1.8.1.12) Gecko/20080206 Camino/1.5.5
Agent Type: browser
Browser Name: Camino

Mozilla/5.0 (Macintosh; U; PPC Mac OS X Mach-O; en-US; rv:1.0.1) Gecko/20030111 Chimera/0.6
Agent Type: browser
Browser Name: Camino

Mozilla/5.0 (Macintosh; U; PPC Mac OS X Mach-O; en-US; rv:1.8.0.10) Gecko/20070228 Camino/1.0.4
Agent Type: browser
Browser Name: Camino

Mozilla/5.0 (Macintosh; U; PPC Mac OS X Mach-O; en; rv:1.8.1.4pre) Gecko/20070511 Camino/1.6pre
Agent Type: browser
Browser Name: Camino

Mozilla/5.0 (Macintosh; U; PPC Mac OS X; en) AppleWebKit/418.9 (KHTML, like Gecko, Safari) Safari/419.3 Cheshire/1.0.ALPHA
Agent Type: browser
Browser Name: Cheshire

Mozilla/5.0 (Macintosh; U; PPC Mac OS X; en) AppleWebKit/419 (KHTML, like Gecko, Safari/419.3) Cheshire/1.0.ALPHA
Agent Type: browser
Browser Name: Cheshire

Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US) AppleWebKit/525.19 (KHTML, like Gecko) Chrome/1.0.154.36 Safari/525.19
Agent Type: browser
Browser Name: Chrome

Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US) AppleWebKit/525.19 (KHTML, like Gecko) Chrome/1.0.154.53 Safari/525.19
Agent Type: browser
Browser Name: Chrome

Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.9.0.10) Gecko/2009042815 Firefox/3.0.10 CometBird/3.0.10
Agent Type: browser
Browser Name: CometBird

Mozilla/5.0 (Windows; U; Windows NT 6.0; en-US; rv:1.9.0.5) Gecko/2009011615 Firefox/3.0.5 CometBird/3.0.5
Agent Type: browser
Browser Name: CometBird

Mozilla/5.0 (Windows; U; Windows NT 6.1; en-US) AppleWebKit/532.0 (KHTML, like Gecko) Comodo_Dragon/1.0.0.9 Chrome/ Version/3.2.1 Safari/532.0
Agent Type: browser
Browser Name: Comodo Dragon

Mozilla/5.0 (Windows; U; Windows NT 5.2; en-US) AppleWebKit/532.0 (KHTML, like Gecko) Comodo_Dragon/1.0.0.5 Safari/532.0
Agent Type: browser
Browser Name: Comodo Dragon

Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US) AppleWebKit/532.0 (KHTML, like Gecko) Comodo_Dragon/1.0.0.9 Chrome/ Version/3.2.1 Safari/532.0
Agent Type: browser
Browser Name: Comodo Dragon

Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.9.2.10) Gecko/20100914 Conkeror/0.9.3
Agent Type: browser
Browser Name: Conkeror

Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.9.1.11) Gecko/20100721 Conkeror/0.9.2 (Debian-0.9.2+git100804-1)
Agent Type: browser
Browser Name: Conkeror

Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 5.1; .NET CLR 1.1.4322; .NET CLR 2.0.50727; Crazy Browser 3.0.0 Beta2)
Agent Type: browser
Browser Name: Crazy Browser

Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; Crazy Browser 1.0.5)
Agent Type: browser
Browser Name: Crazy Browser

Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1; .NET CLR 1.1.4322; Crazy Browser 2.0.1)
Agent Type: browser
Browser Name: Crazy Browser

Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1; Crazy Browser 1.0.5; .NET CLR 1.1.4322; InfoPath.1)
Agent Type: browser
Browser Name: Crazy Browser

Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; Deepnet Explorer 1.5.0; .NET CLR 1.0.3705)
Agent Type: browser
Browser Name: Deepnet Explorer

Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_5_6; en-us) AppleWebKit/525.27.1 (KHTML, like Gecko) Demeter/1.0.9 Safari/125
Agent Type: browser
Browser Name: Demeter

Mozilla/5.0 (Macintosh; U; PPC Mac OS X; pl-pl) AppleWebKit/312.8 (KHTML, like Gecko, Safari) DeskBrowse/1.0
Agent Type: browser
Browser Name: DeskBrowse

Dillo/0.8.5
Agent Type: browser
Browser Name: Dillo

Dillo/2.0
Agent Type: browser
Browser Name: Dillo

DocZilla/1.0 (Windows; U; WinNT4.0; en-US; rv:1.0.0) Gecko/20020804
Agent Type: browser
Browser Name: DocZilla

DocZilla/2.7 (Windows; U; Windows NT 5.1; en-US; rv:2.7.0) Gecko/20050706 CiTEC Information
Agent Type: browser
Browser Name: DocZilla

Mozilla/5.0 (Windows; U; Windows NT 5.1; cs-CZ) AppleWebKit/527+ (KHTML, like Gecko, Safari/419.3)  Dooble
Agent Type: browser
Browser Name: Dooble

Doris/1.15 [en] (Symbian)
Agent Type: browser
Browser Name: Doris

edbrowse/2.2.10
Agent Type: browser
Browser Name: Edbrowse

edbrowse/3.1.2-1
Agent Type: browser
Browser Name: Edbrowse

edbrowse/1.5.17-2
Agent Type: browser
Browser Name: Edbrowse

Mozilla/5.0 (Windows; U; Windows NT 6.1; en-US) AppleWebKit/533+ (KHTML, like Gecko) Element Browser 5.0
Agent Type: browser
Browser Name: Element Browser

Mozilla/5.0 (Windows; U; Windows NT 6.1; cs-CZ) AppleWebKit/533+ (KHTML, like Gecko) Element Browser 6.0
Agent Type: browser
Browser Name: Element Browser

ELinks/0.13.GIT (textmode; Linux 2.6.22-2-686 i686; 148x68-3)
Agent Type: browser
Browser Name: Elinks

ELinks/0.9.3 (textmode; Linux 2.6.11 i686; 79x24)
Agent Type: browser
Browser Name: Elinks

Enigma Browser
Agent Type: browser
Browser Name: Enigma browser

Mozilla/5.0 (X11; U; Linux i686; en; rv:1.8.1.12) Gecko/20080208 (Debian-1.8.1.12-2) Epiphany/2.20
Agent Type: browser
Browser Name: Epiphany

Mozilla/5.0 (X11; U; Linux x86_64; en; rv:1.9.0.12) Gecko/20080528 Fedora/2.24.3-8.fc10 Epiphany/2.22 Firefox/3.0
Agent Type: browser
Browser Name: Epiphany

Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.7.3) Gecko/20041007 Epiphany/1.4.7
Agent Type: browser
Browser Name: Epiphany

Mozilla/4.0 (compatible; MSIE 5.23; Macintosh; PPC) Escape 5.1.1
Agent Type: browser
Browser Name: Espial TV Browser

Mozilla/4.0 (compatible; MSIE 5.23; Macintosh; PPC) Escape 5.1.8
Agent Type: browser
Browser Name: Espial TV Browser

Mozilla/5.0 (Windows; U; Win98; en-US; rv:1.5) Gecko/20031007 Firebird/0.7
Agent Type: browser
Browser Name: Firebird (old name for Firefox)

Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10.5; ko; rv:1.9.1b2) Gecko/20081201 Firefox/3.1b2
Agent Type: browser
Browser Name: Firefox

Mozilla/5.0 (Windows; U; Windows NT 5.1; cs; rv:1.9.0.8) Gecko/2009032609 Firefox/3.0.8
Agent Type: browser
Browser Name: Firefox

Mozilla/5.0 (Windows; Windows NT 6.1; rv:2.0b2) Gecko/20100720 Firefox/4.0b2
Agent Type: browser
Browser Name: Firefox

Mozilla/5.0 (Windows; U; WinNT4.0; en-US; rv:1.7.9) Gecko/20050711 Firefox/1.0.5
Agent Type: browser
Browser Name: Firefox

Mozilla/5.0 (X11; U; SunOS sun4u; en-US; rv:1.9b5) Gecko/2008032620 Firefox/3.0b5
Agent Type: browser
Browser Name: Firefox

Mozilla/5.0 (X11; U; OpenBSD i386; en-US; rv:1.8.0.5) Gecko/20060819 Firefox/1.5.0.5
Agent Type: browser
Browser Name: Firefox

Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10.5; en-US; rv:1.9.1b3) Gecko/20090305 Firefox/3.1b3 GTB5
Agent Type: browser
Browser Name: Firefox

Mozilla/5.0 (X11; U; Linux x86_64; en-US; rv:1.8.1.12) Gecko/20080214 Firefox/2.0.0.12
Agent Type: browser
Browser Name: Firefox

Mozilla/5.0 (Windows; U; Windows NT 5.0; es-ES; rv:1.8.0.3) Gecko/20060426 Firefox/1.5.0.3
Agent Type: browser
Browser Name: Firefox

Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.8.1.9) Gecko/20071113 BonEcho/2.0.0.9
Agent Type: browser
Browser Name: Firefox (BonEcho)

Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.8.1) Gecko/20061026 BonEcho/2.0
Agent Type: browser
Browser Name: Firefox (BonEcho)

Mozilla/5.0 (BeOS; U; Haiku BePC; en-US; rv:1.8.1.21pre) Gecko/20090227 BonEcho/2.0.0.21pre
Agent Type: browser
Browser Name: Firefox (BonEcho)

Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.9.0.8) Gecko/2009033017 GranParadiso/3.0.8
Agent Type: browser
Browser Name: Firefox (GranParadiso)

Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10.6; en-US; rv:1.9.2) Gecko/20100411 Lorentz/3.6.3 GTB7.0
Agent Type: browser
Browser Name: Firefox (Lorentz)

Mozilla/5.0 (X11; U; Linux i686; it; rv:1.9.3a1pre) Gecko/20091019 Minefield/3.7a1pre
Agent Type: browser
Browser Name: Firefox (Minefield)

Mozilla/5.0 (Windows; U; Windows NT 5.0; en-US; rv:1.9.3a4pre) Gecko/20100402 Minefield/3.7a4pre
Agent Type: browser
Browser Name: Firefox (Minefield)

Mozilla/5.0 (Windows; U; Windows NT 6.1; cs; rv:1.9.2a2pre) Gecko/20090912 Namoroka/3.6a2pre (.NET CLR 3.5.30729)
Agent Type: browser
Browser Name: Firefox (Namoroka)

Mozilla/5.0 (X11; U; Linux x86_64; en-US; rv:1.9.2a2pre) Gecko/20090901 Ubuntu/9.10 (karmic) Namoroka/3.6a2pre
Agent Type: browser
Browser Name: Firefox (Namoroka)

Mozilla/5.0 (Windows; U; Windows NT 6.1; en-US; rv:1.9.2a1) Gecko/20090806 Namoroka/3.6a1
Agent Type: browser
Browser Name: Firefox (Namoroka)

Mozilla/5.0 (X11; U; Linux x86_64; en-US; rv:1.9.1b3pre) Gecko/20090109 Shiretoko/3.1b3pre
Agent Type: browser
Browser Name: Firefox (Shiretoko)

Mozilla/5.0 (Windows; U; Windows NT 6.0; en-US; rv:1.9.1b4pre) Gecko/20090311 Shiretoko/3.1b4pre
Agent Type: browser
Browser Name: Firefox (Shiretoko)

Mozilla/5.0 (Macintosh; U; PPC Mac OS X Mach-O; en-US; rv:1.8.0.1) Gecko/20060314 Flock/0.5.13.2
Agent Type: browser
Browser Name: Flock

Mozilla/5.0 (Windows; U; Windows NT 6.0; en-US; rv:1.9.0.2) Gecko/2008092122 Firefox/3.0.2 Flock/2.0b3
Agent Type: browser
Browser Name: Flock

Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US) AppleWebKit/532.5 (KHTML, like Gecko) Flock/3.0.0.3737 Chrome/4.1.249.1071 Safari/532.5
Agent Type: browser
Browser Name: Flock

Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US) AppleWebKit/525.13 (KHTML, like Gecko) Fluid/0.9.4 Safari/525.13
Agent Type: browser
Browser Name: Fluid

Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.7.12) Gecko/20050929 Galeon/1.3.21
Agent Type: browser
Browser Name: Galeon

Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.9.0.8) Gecko/20090327 Galeon/2.0.7
Agent Type: browser
Browser Name: Galeon

Mozilla/5.0 (Windows; U; Windows NT 6.1; en-US; rv:1.9.1.5) Gecko/20091105 Firefox/3.5.5 compat GlobalMojo/1.5.5 GlobalMojoExt/1.5
Agent Type: browser
Browser Name: GlobalMojo

Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.0; GreenBrowser)
Agent Type: browser
Browser Name: GreenBrowser

Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 5.1; .NET CLR 2.0.50727; GreenBrowser)
Agent Type: browser
Browser Name: GreenBrowser

Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 5.1; .NET CLR 1.1.4322; InfoPath.1; .NET CLR 2.0.50727; .NET CLR 3.0.04506.30; GreenBrowser)
Agent Type: browser
Browser Name: GreenBrowser

HotJava/1.1.2 FCS
Agent Type: browser
Browser Name: HotJava

Mozilla/3.0 (x86 [cs] Windows NT 5.1; Sun)
Agent Type: browser
Browser Name: HotJava

Mozilla/5.1 (X11; U; Linux i686; en-US; rv:1.8.0.3) Gecko/20060425 SUSE/1.5.0.3-7 Hv3/alpha
Agent Type: browser
Browser Name: Hv3

Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 5.1; Trident/4.0; SIMBAR={CFBFDAEA-F21E-4D6E-A9B0-E100A69B860F}; Hydra Browser; .NET CLR 2.0.50727; .NET CLR 1.1.4322; .NET CLR 3.0.04506.30)
Agent Type: browser
Browser Name: Hydra Browser

Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1; Hydra Browser; .NET CLR 2.0.50727; .NET CLR 3.0.4506.2152; .NET CLR 3.5.30729)
Agent Type: browser
Browser Name: Hydra Browser

IBrowse/2.3 (AmigaOS 3.9)
Agent Type: browser
Browser Name: IBrowse

Mozilla/5.0 (compatible; IBrowse 3.0; AmigaOS4.0)
Agent Type: browser
Browser Name: IBrowse

Mozilla/4.5 (compatible; iCab 2.9.1; Macintosh; U; PPC)
Agent Type: browser
Browser Name: iCab

iCab/3.0.2 (Macintosh; U; PPC Mac OS X)
Agent Type: browser
Browser Name: iCab

iCab/4.0 (Macintosh; U; Intel Mac OS X)
Agent Type: browser
Browser Name: iCab

ICE Browser/v5_4_3 (Java 1.4.2; Windows XP 5.1 x86)
Agent Type: browser
Browser Name: ICE browser

Mozilla/5.0 (Java 1.6.0_01; Windows XP 5.1 x86; en) ICEbrowser/v6_1_2
Agent Type: browser
Browser Name: ICE browser

ICE Browser/5.05 (Java 1.4.0; Windows 2000 5.0 x86)
Agent Type: browser
Browser Name: ICE browser

Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.8.1.9) Gecko/20071030 Iceape/1.1.6 (Debian-1.1.6-3)
Agent Type: browser
Browser Name: IceApe

Mozilla/5.0 (X11; U; Linux ppc; en-US; rv:1.8.1.13) Gecko/20080313 Iceape/1.1.9 (Debian-1.1.9-5)
Agent Type: browser
Browser Name: IceApe

Mozilla/5.0 (X11; U; Linux x86_64; en-US; rv:1.8.1.8) Gecko/20071008 Iceape/1.1.5 (Ubuntu-1.1.5-1ubuntu0.7.10)
Agent Type: browser
Browser Name: IceApe

Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.9.0.3) Gecko/2008092921 IceCat/3.0.3-g1
Agent Type: browser
Browser Name: IceCat

Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.8.1.11) Gecko/20071203 IceCat/2.0.0.11-g1
Agent Type: browser
Browser Name: IceCat

Mozilla/5.0 (X11; U; Linux i686; de; rv:1.9.0.5) Gecko/2008122011 Iceweasel/3.0.5 (Debian-3.0.5-1)
Agent Type: browser
Browser Name: IceWeasel

Mozilla/5.0 (X11; U; Linux x86_64; en-US; rv:1.8.1.1) Gecko/20061205 Iceweasel/2.0.0.1 (Debian-2.0.0.1+dfsg-4)
Agent Type: browser
Browser Name: IceWeasel

Mozilla/5.0 (X11; U; Linux i686; it; rv:1.9.0.5) Gecko/2008122011 Iceweasel/3.0.5 (Debian-3.0.5-1)
Agent Type: browser
Browser Name: IceWeasel

Mozilla/5.0 (X11; U; Linux i686; pt-PT; rv:1.9.2.3) Gecko/20100402 Iceweasel/3.6.3 (like Firefox/3.6.3) GTB7.0
Agent Type: browser
Browser Name: IceWeasel

Mozilla/4.0 (Windows; MSIE 6.0; Windows NT 5.1; SV1; .NET CLR 2.0.50727)
Agent Type: browser
Browser Name: IE

Mozilla/2.0 (compatible; MSIE 4.0; Windows 98)
Agent Type: browser
Browser Name: IE

Mozilla/4.0 (Mozilla/4.0; MSIE 7.0; Windows NT 5.1; FDM; SV1; .NET CLR 3.0.04506.30)
Agent Type: browser
Browser Name: IE

Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; Trident/5.0)
Agent Type: browser
Browser Name: IE

Mozilla/4.0 (compatible; MSIE 5.01; Windows NT)
Agent Type: browser
Browser Name: IE

Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1; .NET CLR 1.0.3705; .NET CLR 1.1.4322; Media Center PC 4.0; .NET CLR 2.0.50727)
Agent Type: browser
Browser Name: IE

Mozilla/4.0 (compatible; MSIE 5.0; Windows NT;)
Agent Type: browser
Browser Name: IE

Mozilla/4.0 (compatible; MSIE 5.0b1; Mac_PowerPC)
Agent Type: browser
Browser Name: IE

Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.0; Trident/4.0; GTB5; SLCC1; .NET CLR 2.0.50727; Media Center PC 5.0; .NET CLR 3.0.04506; InfoPath.2; OfficeLiveConnector.1.3; OfficeLivePatch.0.0)
Agent Type: browser
Browser Name: IE

Mozilla/4.0 (compatible; MSIE 5.23; Mac_PowerPC)
Agent Type: browser
Browser Name: IE

Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1; GTB6; Ant.com Toolbar 1.6; MSIECrawler)
Agent Type: browser
Browser Name: IE

Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.0; Trident/4.0; SLCC1; .NET CLR 2.0.50727; .NET CLR 1.1.4322; InfoPath.2; .NET CLR 3.5.21022; .NET CLR 3.5.30729; MS-RTC LM 8; OfficeLiveConnector.1.4; OfficeLivePatch.1.3; .NET CLR 3.0.30729)
Agent Type: browser
Browser Name: IE 8.0 (Compatibility View)

Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.1; WOW64; Trident/4.0; SLCC2; .NET CLR 2.0.50727; InfoPath.2)
Agent Type: browser
Browser Name: IE 8.0 (Compatibility View)

Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; iRider 2.21.1108; FDM)
Agent Type: browser
Browser Name: iRider

Mozilla/5.0 (Windows; U; Windows NT 6.1; en-US) AppleWebKit/528.7 (KHTML, like Gecko) Iron/1.0.155.0 Safari/528.7
Agent Type: browser
Browser Name: Iron

Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US) AppleWebKit/525.19 (KHTML, like Gecko) Iron/0.2.152.0 Safari/12081672.525
Agent Type: browser
Browser Name: Iron

Mozilla/5.0 (Windows; U; Windows NT 6.1; en-US) AppleWebKit/533.1 (KHTML, like Gecko) Iron/5.0.326.0 Chrome/5.0.326.0 Safari/533.1
Agent Type: browser
Browser Name: Iron

Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US) AppleWebKit/531.0 (KHTML, like Gecko) Iron/3.0.189.0 Safari/531.0
Agent Type: browser
Browser Name: Iron

Mozilla/5.0 (Windows; U; Windows NT 6.0; en-US) AppleWebKit/528.5 (KHTML, like Gecko) Iron/0.4.155.0 Safari/528.5
Agent Type: browser
Browser Name: Iron

Mozilla/5.0 (Windows; U; Windows NT 6.1; en-US; rv:1.8.1.19) Gecko/20081217 K-Meleon/1.5.2
Agent Type: browser
Browser Name: K-Meleon

Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.8.1.21) Gecko/20090331 K-Meleon/1.5.3
Agent Type: browser
Browser Name: K-Meleon

Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.8.0.5) Gecko/20060706 K-Meleon/1.0
Agent Type: browser
Browser Name: K-Meleon

Mozilla/5.0 (Windows; U; Windows NT 5.0; en-US; rv:1.8.1.21) Gecko/20090331 K-Meleon/1.5.3
Agent Type: browser
Browser Name: K-Meleon

Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.8.0.6) Gecko/20060731 K-Ninja/2.0.2
Agent Type: browser
Browser Name: K-Ninja

Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.8.1.4pre) Gecko/20070404 K-Ninja/2.1.3
Agent Type: browser
Browser Name: K-Ninja

Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.8.1.2pre) Gecko/20070215 K-Ninja/2.1.1
Agent Type: browser
Browser Name: K-Ninja

Mozilla/5.0 (Windows; U; Windows NT 5.1; zh-CN; rv:1.9) Gecko/20080705 Firefox/3.0 Kapiko/3.0
Agent Type: browser
Browser Name: Kapiko

Mozilla/5.0 (X11; Linux i686; U;) Gecko/20070322 Kazehakase/0.4.5
Agent Type: browser
Browser Name: Kazehakase

Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.9.1.3) Gecko Strata/4.4.1.1402
Agent Type: browser
Browser Name: Kirix Strata

Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; KKman2.0)
Agent Type: browser
Browser Name: KKman

Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1; KKMAN3.2)
Agent Type: browser
Browser Name: KKman

Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; KKman3.0)
Agent Type: browser
Browser Name: KKman

Mozilla/5.0 (compatible; Konqueror/2.2.1; Linux)
Agent Type: browser
Browser Name: Konqueror

Mozilla/5.0 (compatible; Konqueror/3.5; SunOS)
Agent Type: browser
Browser Name: Konqueror

Mozilla/5.0 (compatible; Konqueror/3.1-rc5; i686 Linux; 20020712)
Agent Type: browser
Browser Name: Konqueror

Mozilla/5.0 (compatible; Konqueror/4.3; Windows) KHTML/4.3.0 (like Gecko)
Agent Type: browser
Browser Name: Konqueror

Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.8.1.6) Gecko/20071115 Firefox/2.0.0.6 LBrowser/2.0.0.6
Agent Type: browser
Browser Name: LBrowser

Links (0.96; Linux 2.4.20-18.7 i586)
Agent Type: browser
Browser Name: Links

Links (0.98; Win32; 80x25)
Agent Type: browser
Browser Name: Links

Links (2.1pre18; Linux 2.4.31 i686; 100x37)
Agent Type: browser
Browser Name: Links

Links (2.1; Linux 2.6.18-gentoo-r6 x86_64; 80x24)
Agent Type: browser
Browser Name: Links

Links (2.2; Linux 2.6.25-gentoo-r9 sparc64; 166x52)
Agent Type: browser
Browser Name: Links

Mozilla/4.0 (compatible; MSIE 6.0; Linux 2.6.26-1-amd64) Lobo/0.98.3
Agent Type: browser
Browser Name: Lobo

Mozilla/4.0 (compatible; MSIE 6.0; Windows XP 5.1) Lobo/0.98.4
Agent Type: browser
Browser Name: Lobo

Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.9.1b3pre) Gecko/2008 Lunascape/4.9.9.98
Agent Type: browser
Browser Name: Lunascape

Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1; JyxoToolbar1.0; .NET CLR 2.0.50727; .NET CLR 3.0.04506.648; .NET CLR 3.5.21022; .NET CLR 1.1.4322; .NET CLR 3.0.4506.2152; .NET CLR 3.5.30729; Lunascape 5.1.4.5)
Agent Type: browser
Browser Name: Lunascape

Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US) AppleWebKit/528+ (KHTML, like Gecko, Safari/528.0) Lunascape/5.0.2.0
Agent Type: browser
Browser Name: Lunascape

Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.9.1.2) Gecko/20090804 Firefox/3.5.2 Lunascape/5.1.4.5
Agent Type: browser
Browser Name: Lunascape

Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.0; .NET CLR 1.1.4322; Lunascape 2.1.3)
Agent Type: browser
Browser Name: Lunascape

Lynx/2.8.6rel.4 libwww-FM/2.14 SSL-MM/1.4.1 GNUTLS/1.6.3
Agent Type: browser
Browser Name: Lynx

Lynx/2.8.3dev.6 libwww-FM/2.14
Agent Type: browser
Browser Name: Lynx

Lynx/2.8.5dev.16 libwww-FM/2.14 SSL-MM/1.4.1 OpenSSL/0.9.7a
Agent Type: browser
Browser Name: Lynx

Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.7.12) Gecko/20051001 Firefox/1.0.7 Madfox/0.3.2u3
Agent Type: browser
Browser Name: Madfox

Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 5.1; SV1; Maxthon; .NET CLR 1.1.4322)
Agent Type: browser
Browser Name: Maxthon

Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1; MyIE2)
Agent Type: browser
Browser Name: Maxthon

Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 5.1; Trident/4.0; .NET CLR 2.0.50727; MAXTHON 2.0)
Agent Type: browser
Browser Name: Maxthon

Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US) AppleWebKit/530.6 (KHTML, like Gecko) Maxthon/3.0 Safari/530.6
Agent Type: browser
Browser Name: Maxthon

Midori/0.1.5 (X11; Linux; U; en-gb) WebKit/532+
Agent Type: browser
Browser Name: Midori

Midori/0.1.7
Agent Type: browser
Browser Name: Midori

Mozilla/5.0 (Windows; U; Windows NT 6.1; cs-CZ) AppleWebKit/532.4 (KHTML, like Gecko) MiniBrowser/3.0 Safari/532.4
Agent Type: browser
Browser Name: Mini Browser

Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.0.1) Gecko/20020919
Agent Type: browser
Browser Name: Mozilla

Mozilla/5.0 (Windows; U; Windows NT 5.0; it-IT; rv:1.7.12) Gecko/20050915
Agent Type: browser
Browser Name: Mozilla

Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1; Multi-Browser 10.1 (www.multibrowser.de); SIMBAR={3C117E1F-85A8-4b43-816C-E78E9AACDE21}; .NET CLR 1.1.4322; .NET CLR 2.0.50727; .NET CLR 3.0.04506.30) 
Agent Type: browser
Browser Name: Multi-Browser XP

Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1; Multi-Browser 10.1 (www.multibrowser.de); .NET CLR 1.1.4322)
Agent Type: browser
Browser Name: Multi-Browser XP

Mozilla/5.0 (Windows; U; Windows NT 5.0; en-US; rv:1.2.1; MultiZilla v1.1.32 final) Gecko/20021130
Agent Type: browser
Browser Name: MultiZilla

Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.4; MultiZilla v1.5.0.0f) Gecko/20030624
Agent Type: browser
Browser Name: MultiZilla

myibrow/2.2 (Windows; U; Windows NT 5.1; cs; rv:1.8.1.14) Gecko/20080001 My Internet Browser/2.2.0.0 20080913235045
Agent Type: browser
Browser Name: My Internet Browser

MyIBrow/3.0 (Windows; U; Windows NT 5.1; cs; compatible) MYIBE/2009000000 (Gecko/Khtml)
Agent Type: browser
Browser Name: My Internet Browser

Mozilla/5.0 (Windows; U; Windows NT 6.1; cs; rv:1.9.2.6) Gecko/20100628 myibrow/4alpha2
Agent Type: browser
Browser Name: My Internet Browser

NCSA_Mosaic/3.0 (Windows 95)
Agent Type: browser
Browser Name: NCSA Mosaic

NCSA Mosaic/1.0 (X11;SunOS 4.1.4 sun4m)
Agent Type: browser
Browser Name: NCSA Mosaic

NCSA_Mosaic/2.6 (X11; SunOS 4.1.3 sun4m)
Agent Type: browser
Browser Name: NCSA Mosaic

Mozilla/3.01 (compatible; Netbox/3.5 R92; Linux 2.2)
Agent Type: browser
Browser Name: NetBox

Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1; NetCaptor 7.5.4; .NET CLR 2.0.50727; .NET CLR 3.0.04506.648; .NET CLR 3.5.21022; .NET CLR 1.1.4322; .NET CLR 3.0.4506.2152; .NET CLR 3.5.30729)
Agent Type: browser
Browser Name: NetCaptor

Mozilla/4.0 (compatible; MSIE 5.01; Windows NT 5.0; NetCaptor 6.5.0RC1)
Agent Type: browser
Browser Name: NetCaptor

Mozilla/3.0 (compatible; NetPositive/2.2)
Agent Type: browser
Browser Name: NetPositive

Mozilla/3.0 (compatible; NetPositive/2.2.2; BeOS)
Agent Type: browser
Browser Name: NetPositive

Mozilla/4.04 [en] (X11; I; IRIX 5.3 IP22)
Agent Type: browser
Browser Name: Netscape Navigator

Mozilla/5.0 (Windows; U; Win 9x 4.90; de-DE; rv:0.9.2) Gecko/20010726 Netscape6/6.1
Agent Type: browser
Browser Name: Netscape Navigator

Mozilla/5.0 (Windows; U; Windows NT 6.0; en-US; rv:1.8.1.12) Gecko/20080219 Firefox/2.0.0.12 Navigator/9.0.0.6
Agent Type: browser
Browser Name: Netscape Navigator

Mozilla/4.08 [en] (WinNT; U ;Nav)
Agent Type: browser
Browser Name: Netscape Navigator

Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.0.2) Gecko/20030208 Netscape/7.02
Agent Type: browser
Browser Name: Netscape Navigator

Mozilla/3.0 (Win95; I)
Agent Type: browser
Browser Name: Netscape Navigator

Mozilla/4.51 [en] (Win98; U)
Agent Type: browser
Browser Name: Netscape Navigator

Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.7.5) Gecko/20060127 Netscape/8.1
Agent Type: browser
Browser Name: Netscape Navigator

NetSurf/2.0 (RISC OS; armv3l)
Agent Type: browser
Browser Name: NetSurf

NetSurf/1.2 (Linux; i686)
Agent Type: browser
Browser Name: NetSurf

Mozilla/4.7 (compatible; OffByOne; Windows 2000)
Agent Type: browser
Browser Name: Off By One

Mozilla/4.7 (compatible; OffByOne; Windows 98)
Agent Type: browser
Browser Name: Off By One

OmniWeb/2.7-beta-3 OWF/1.0
Agent Type: browser
Browser Name: OmniWeb

Mozilla/5.0 (Macintosh; U; PPC Mac OS X; en-US) AppleWebKit/420+ (KHTML, like Gecko, Safari) OmniWeb/v595
Agent Type: browser
Browser Name: OmniWeb

Mozilla/4.5 (compatible; OmniWeb/4.1.1-v424.6; Mac_PowerPC)
Agent Type: browser
Browser Name: OmniWeb

Mozilla/5.0 (Macintosh; U; Intel Mac OS X; en-US) AppleWebKit/528.16 (KHTML, like Gecko, Safari/528.16) OmniWeb/v622.8.0.112941
Agent Type: browser
Browser Name: OmniWeb

Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1) Opera 7.10 [en]
Agent Type: browser
Browser Name: Opera

Opera/9.80 (Windows NT 5.1; U; cs) Presto/2.2.15 Version/10.00
Agent Type: browser
Browser Name: Opera

Opera/9.51 (Macintosh; Intel Mac OS X; U; en)
Agent Type: browser
Browser Name: Opera

Opera/5.11 (Windows 98; U) [en]
Agent Type: browser
Browser Name: Opera

Mozilla/4.0 (compatible; MSIE 5.0; Windows NT 4.0) Opera 6.01 [en]
Agent Type: browser
Browser Name: Opera

Opera/9.02 (Windows XP; U; ru)
Agent Type: browser
Browser Name: Opera

Opera/9.70 (Linux i686 ; U; en) Presto/2.2.1
Agent Type: browser
Browser Name: Opera

Mozilla/4.0 (compatible; MSIE 5.0; Windows 98) Opera 5.12 [en]
Agent Type: browser
Browser Name: Opera

Opera/7.03 (Windows NT 5.0; U) [en]
Agent Type: browser
Browser Name: Opera

Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; en) Opera 9.24
Agent Type: browser
Browser Name: Opera

Opera/6.0 (Windows 2000; U) [fr]
Agent Type: browser
Browser Name: Opera

Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.9.0.7) Gecko/2009030821 Firefox/3.0.7 Orca/1.1 build 2
Agent Type: browser
Browser Name: Orca

Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.9.0.6) Gecko/2009022300 Firefox/3.0.6 Orca/1.1 build 1
Agent Type: browser
Browser Name: Orca

Mozilla/1.10 [en] (Compatible; RISC OS 3.70; Oregano 1.10)
Agent Type: browser
Browser Name: Oregano

Mozilla/5.0 (compatible; Origyn Web Browser; AmigaOS 4.0; U; en) AppleWebKit/531.0+ (KHTML, like Gecko, Safari/531.0+)
Agent Type: browser
Browser Name: OWB

Mozilla/5.0 (compatible; Origyn Web Browser; AmigaOS 4.1; ppc; U; en) AppleWebKit/530.0+ (KHTML, like Gecko, Safari/530.0+)
Agent Type: browser
Browser Name: OWB

Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.9.2) Gecko/20100206 Palemoon/3.6.0.5
Agent Type: browser
Browser Name: Pale Moon

Mozilla/5.0 (Windows; U; Windows NT 6.1; en-US; rv:1.9.2.3) Gecko/20100403 Firefox/3.6.3 (Palemoon/3.6.3)
Agent Type: browser
Browser Name: Pale Moon

Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; PhaseOut-www.phaseout.net)
Agent Type: browser
Browser Name: Phaseout

Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.4a) Gecko/20030411 Phoenix/0.5
Agent Type: browser
Browser Name: Phoenix (old name for Firefox)

Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.2b) Gecko/20021029 Phoenix/0.4
Agent Type: browser
Browser Name: Phoenix (old name for Firefox)

Mozilla/5.0 (Windows; U; Windows NT 5.1; cs-CZ) AppleWebKit/527+ (KHTML, like Gecko)  QtWeb Internet Browser/2.5 http://www.QtWeb.net
Agent Type: browser
Browser Name: QtWeb

Mozilla/5.0 (Windows; U; Windows NT 5.1; cs-CZ) AppleWebKit/532.4 (KHTML, like Gecko)  QtWeb Internet Browser/3.3 http://www.QtWeb.net
Agent Type: browser
Browser Name: QtWeb

Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US) AppleWebKit/527+ (KHTML, like Gecko) QtWeb Internet Browser/1.2 http://www.QtWeb.net
Agent Type: browser
Browser Name: QtWeb

Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US) AppleWebKit/527+ (KHTML, like Gecko) QtWeb Internet Browser/1.7 http://www.QtWeb.net
Agent Type: browser
Browser Name: QtWeb

Mozilla/5.0 (X11; U; Linux; cs-CZ) AppleWebKit/527+ (KHTML, like Gecko, Safari/419.3)  rekonq
Agent Type: browser
Browser Name: rekonq

retawq/0.2.6c [en] (text)
Agent Type: browser
Browser Name: retawq

Mozilla/5.0 (Macintosh; U; PPC Mac OS X 10_5_6; it-it) AppleWebKit/528.16 (KHTML, like Gecko) Version/4.0 Safari/528.16
Agent Type: browser
Browser Name: Safari

Mozilla/5.0 (Windows; U; Windows NT 5.1; cs-CZ) AppleWebKit/523.15 (KHTML, like Gecko) Version/3.0 Safari/523.15
Agent Type: browser
Browser Name: Safari

Mozilla/5.0 (Macintosh; U; PPC Mac OS X; de-de) AppleWebKit/125.2 (KHTML, like Gecko) Safari/125.7
Agent Type: browser
Browser Name: Safari

Mozilla/5.0 (Windows; U; Windows NT 6.0; en-US) AppleWebKit/528.16 (KHTML, like Gecko) Version/4.0 Safari/528.16
Agent Type: browser
Browser Name: Safari

Mozilla/5.0 (Macintosh; U; PPC Mac OS X; fi-fi) AppleWebKit/420+ (KHTML, like Gecko) Safari/419.3
Agent Type: browser
Browser Name: Safari

Mozilla/5.0 (Macintosh; U; PPC Mac OS X; en-us) AppleWebKit/312.8 (KHTML, like Gecko) Safari/312.6
Agent Type: browser
Browser Name: Safari

Mozilla/5.0 (X11; U; Linux i686; rv:1.9.1a2pre) Gecko/20080824052448 SeaMonkey/2.0a1pre
Agent Type: browser
Browser Name: SeaMonkey

Mozilla/5.0 (Windows; U; Win 9x 4.90; en-GB; rv:1.8.1.6) Gecko/20070802 SeaMonkey/1.1.4
Agent Type: browser
Browser Name: SeaMonkey

Mozilla/5.0 (Windows; U; Windows NT 6.1; en-US; rv:1.9.1b3pre) Gecko/20081208 SeaMonkey/2.0a3pre
Agent Type: browser
Browser Name: SeaMonkey

Mozilla/5.0 (BeOS; U; BeOS BePC; en-US; rv:1.9a1) Gecko/20060702 SeaMonkey/1.5a
Agent Type: browser
Browser Name: SeaMonkey

Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10.5; en-US; rv:1.9.1b3pre) Gecko/20081202 SeaMonkey/2.0a2
Agent Type: browser
Browser Name: SeaMonkey

Mozilla/5.0 (Macintosh; U; Intel Mac OS X; en-US; rv:1.8.1.13) Gecko/20080313 SeaMonkey/1.1.9
Agent Type: browser
Browser Name: SeaMonkey

Mozilla/5.0 (Macintosh; U; PPC Mac OS X; ja-jp) AppleWebKit/419 (KHTML, like Gecko) Shiira/1.2.3 Safari/125
Agent Type: browser
Browser Name: Shiira

Mozilla/5.0 (Macintosh; U; PPC Mac OS X; en) AppleWebKit/417.9 (KHTML, like Gecko, Safari) Shiira/1.1
Agent Type: browser
Browser Name: Shiira

Mozilla/5.0 (Macintosh; U; Intel Mac OS X; fr) AppleWebKit/418.9.1 (KHTML, like Gecko) Shiira Safari/125
Agent Type: browser
Browser Name: Shiira

Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.0; SiteKiosk 5.5 Build 45)
Agent Type: browser
Browser Name: SiteKiosk

Mozilla/4.0 (compatible; MSIE 6.0; Windows 98; SiteKiosk 4.8)
Agent Type: browser
Browser Name: SiteKiosk

Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.0; SiteKiosk 6.5 Build 150)
Agent Type: browser
Browser Name: SiteKiosk

Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 5.1; SiteKiosk 7.0 Build 248)
Agent Type: browser
Browser Name: SiteKiosk

Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1) Sleipnir/2.8.1
Agent Type: browser
Browser Name: Sleipnir

Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 5.1; .NET CLR 1.1.4322; InfoPath.1; .NET CLR 2.0.50727) Sleipnir/2.8.4
Agent Type: browser
Browser Name: Sleipnir

Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 5.1; Trident/4.0; .NET CLR 2.0.50727; SlimBrowser)
Agent Type: browser
Browser Name: SlimBrowser

Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 5.1; Q312461; SlimBrowser [flashpeak.com]; .NET CLR 1.1.4322; .NET CLR 2.0.50727; .NET CLR 3.0.04506.30
Agent Type: browser
Browser Name: SlimBrowser

Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_5_5; en-us) AppleWebKit/525.27.1 (KHTML, like Gecko) Stainless/0.4 Safari/525.20.1
Agent Type: browser
Browser Name: Stainless

Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_5_6; en-us) AppleWebKit/528.16 (KHTML, like Gecko) Stainless/0.5.3 Safari/525.20.1
Agent Type: browser
Browser Name: Stainless

Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_4_11; en) AppleWebKit/525.18 (KHTML, like Gecko) Sunrise/1.7.4 like Safari/4525.22
Agent Type: browser
Browser Name: Sunrise

Mozilla/5.0 (Macintosh; U; PPC Mac OS X; en-us) AppleWebKit/125.5.7 (KHTML, like Gecko) SunriseBrowser/0.853
Agent Type: browser
Browser Name: Sunrise

Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.9.0.10pre) Gecko/2009041814 Firefox/3.0.10pre (Swiftfox)
Agent Type: browser
Browser Name: Swiftfox

Mozilla/5.0 (X11; U; Linux x86_64; en-US; rv:1.8.1.6pre) Gecko/20070730 Swiftweasel/2.0.0.6pre
Agent Type: browser
Browser Name: Swiftweasel

Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.8.1.7) Gecko/20070919 Swiftweasel/2.0.0.7 
Agent Type: browser
Browser Name: Swiftweasel

Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1; .NET CLR 2.0.50727; .NET CLR 3.0.04506.648; .NET CLR 3.5.21022; .NET CLR 1.1.4322; TheWorld)
Agent Type: browser
Browser Name: TheWorld Browser

Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; Tjusig 2.40.164; SV1; .NET CLR 2.0.50727)
Agent Type: browser
Browser Name: Tjusig

Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1; JyxoToolbar1.0; Tjusig 2.40.164; .NET CLR 2.0.50727; .NET CLR 3.0.04506.648; .NET CLR 3.5.21022; .NET CLR 1.1.4322)
Agent Type: browser
Browser Name: Tjusig

Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 5.1; TencentTraveler 4.0; .NET CLR 2.0.50727)
Agent Type: browser
Browser Name: TT Explorer

Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1; TencentTraveler )
Agent Type: browser
Browser Name: TT Explorer

Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1; TencentTraveler 4.0; .NET CLR 2.0.50727)
Agent Type: browser
Browser Name: TT Explorer

Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.0; UltraBrowser 11.0; .NET CLR 2.0.50727; .NET CLR 3.0.04506.648; .NET CLR 3.5.21022; .NET CLR 1.1.4322)
Agent Type: browser
Browser Name: UltraBrowser 

Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.0; WOW64; Trident/4.0; UltraBrowser 11.0; GTB6.5; Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1) ; SLCC1; .NET CLR 2.0.50727; InfoPath.2; Media Center PC 5.0; .NET CLR 3.5.21022; .NET CLR 3.5.30729;
Agent Type: browser
Browser Name: UltraBrowser 

Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; JyxoToolbar1.0; SV1; UltraBrowser 11.0; .NET CLR 2.0.50727; .NET CLR 3.0.04506.648; .NET CLR 3.5.21022; .NET CLR 1.1.4322)
Agent Type: browser
Browser Name: UltraBrowser 

Webkit/1.1.8 (Linux; en-us) Uzbl
Agent Type: browser
Browser Name: Uzbl

Uzbl (X11; U; Linux x86_64; en-GB) AppleWebkit/1.1.10
Agent Type: browser
Browser Name: Uzbl

Uzbl (Webkit 1.1.9) (Linux)
Agent Type: browser
Browser Name: Uzbl

Uzbl (U; Linux x86_64; en-GB) Webkit 1.1.10
Agent Type: browser
Browser Name: Uzbl

w3m/0.5.2
Agent Type: browser
Browser Name: w3m

w3m/0.5.1
Agent Type: browser
Browser Name: w3m

Mozilla/5.0 (Windows; U; Windows NT 5.1; cs-CZ) AppleWebKit/532.4 (KHTML, like Gecko) WeltweitimnetzBrowser/0.15 Safari/532.4
Agent Type: browser
Browser Name: Weltweitimnetz Browser

Mozilla/5.0 (Macintosh; U; PPC Mac OS X; en-us) AppleWebKit/103u (KHTML, like Gecko) wKiosk/100
Agent Type: browser
Browser Name: wKiosk

WorldWideweb (NEXT)
Agent Type: browser
Browser Name: WorldWideWeb

Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.9.0.9) Gecko/2009042410 Firefox/3.0.9 Wyzo/3.0.3
Agent Type: browser
Browser Name: Wyzo

X-Smiles/1.2-20081113
Agent Type: browser
Browser Name: X-Smiles

Mozilla/3.0 (compatible; AvantGo 3.2)
Agent Type: offline browser
Bot Name: AvantGo

User-Agent: Mozilla/3.0 (compatible; AvantGo 5.2; FreeBSD)
Agent Type: offline browser
Bot Name: AvantGo

Axel 2.4 (CYGWIN_NT-6.1-WOW64)
Agent Type: offline browser
Bot Name: Axel

Axel 2.4 (Linux)
Agent Type: offline browser
Bot Name: Axel

GetRight/3.2
Agent Type: offline browser
Bot Name: GetRight

Mozilla/4.5 (compatible; HTTrack 3.0x; Windows 98)
Agent Type: offline browser
Bot Name: HTTrack

iSiloX/4.37 Windows/32
Agent Type: offline browser
Bot Name: iSiloX

iSiloXC/4.37 Windows/32
Agent Type: offline browser
Bot Name: iSiloXC

iSiloXC/4.37 Linux/i386
Agent Type: offline browser
Bot Name: iSiloXC

JoBo/1.4
Agent Type: offline browser
Bot Name: JoBo

Web Downloader/5.7
Agent Type: offline browser
Bot Name: Offline Explorer

Offline Explorer/1.4
Agent Type: offline browser
Bot Name: Offline Explorer

Web Downloader/7.9
Agent Type: offline browser
Bot Name: Offline Explorer

Offline Explorer/2.5
Agent Type: offline browser
Bot Name: Offline Explorer

SiteSucker/1.6.9
Agent Type: offline browser
Bot Name: SiteSucker

SuperBot/4.7.0.74 (Windows XP)
Agent Type: offline browser
Bot Name: SuperBot

SuperBot/4.4.0.60 (Windows XP)
Agent Type: offline browser
Bot Name: SuperBot

Teleport Pro/1.2x
Agent Type: offline browser
Bot Name: Teleport Pro

WebCopier v4.2
Agent Type: offline browser
Bot Name: WebCopier

WebCopier v3.0
Agent Type: offline browser
Bot Name: WebCopier

WebStripper/2.69
Agent Type: offline browser
Bot Name: WebStripper

WebZIP/3.5 (http://www.spidersoft.com)
Agent Type: offline browser
Bot Name: WebZIP

WebZIP/7.0 (http://www.spidersoft.com)
Agent Type: offline browser
Bot Name: WebZIP

Wget/1.5.3
Agent Type: offline browser
Bot Name: Wget

Wget/1.10.1 (Red Hat modified)
Agent Type: offline browser
Bot Name: Wget

Xaldon_WebSpider/2.0.b1
Agent Type: offline browser
Bot Name: Xaldon WebSpider

Xaldon WebSpider 2.7.b6 
Agent Type: offline browser
Bot Name: Xaldon WebSpider

Mozilla/5.0 (Linux; U; Android 1.5; de-de; HTC Magic Build/CRB17) AppleWebKit/528.5+ (KHTML, like Gecko) Version/3.1.2 Mobile Safari/525.20.1
Agent Type: mobile browser
Bot Name: Android Webkit

BlackBerry9530/4.7.0.76 Profile/MIDP-2.0 Configuration/CLDC-1.1 VendorID/126
Agent Type: mobile browser
Bot Name: BlackBerry

BlackBerry8820/4.5.0.110 Profile/MIDP-2.0 Configuration/CLDC-1.1 VendorID/102
Agent Type: mobile browser
Bot Name: BlackBerry

BlackBerry8330m/4.5.0.131 Profile/MIDP-2.0 Configuration/CLDC-1.1 VendorID/104
Agent Type: mobile browser
Bot Name: BlackBerry

BlackBerry9000/4.6.0.126 Profile/MIDP-2.0 Configuration/CLDC-1.1 VendorID/120
Agent Type: mobile browser
Bot Name: BlackBerry

BlackBerry8100/4.5.0.124 Profile/MIDP-2.0 Configuration/CLDC-1.1 VendorID/100
Agent Type: mobile browser
Bot Name: BlackBerry

Mozilla/4.0 (compatible; MSIE 6.0; Windows 98; PalmSource/Palm-TunX; Blazer/4.3) 16;320x448
Agent Type: mobile browser
Bot Name: Blazer

UPG1 UP/4.0 (compatible; Blazer 1.0)
Agent Type: mobile browser
Bot Name: Blazer

Mozilla/4.0 (compatible; MSIE 6.0; Windows 98; PalmSource/Palm-D050; Blazer/4.3) 16;320x448
Agent Type: mobile browser
Bot Name: Blazer

Palm680/RC1 Mozilla/4.0 (compatible; MSIE 6.0; Windows 98; PalmSource/Palm-D053; Blazer/4.5) 16;320x320 UP.Link/6.3.1.17.06.3.1.17.0
Agent Type: mobile browser
Bot Name: Blazer

Mozilla/4.0 (compatible; MSIE 6.0; Windows 98; PalmSource/hspr-H102; Blazer/4.0) 16;320x320
Agent Type: mobile browser
Bot Name: Blazer

Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.9.1b2pre) Gecko/20081015 Fennec/1.0a1
Agent Type: mobile browser
Bot Name: Fennec

Mozilla/5.0 (X11; U; Linux armv7l; en-US; rv:1.9.2a1pre) Gecko/20090322 Fennec/1.0b2pre
Agent Type: mobile browser
Bot Name: Fennec

HTC_P4550/TYTN_II Mozilla/4.0 (compatible; MSIE 6.0; Windows CE; IEMobile 7.11)
Agent Type: mobile browser
Bot Name: IE Mobile

Mozilla/4.0 (compatible; MSIE 6.0; Windows CE; IEMobile 7.11) 320x240; VZW; Motorola-Q9c; Windows Mobile 6.1 Standard
Agent Type: mobile browser
Bot Name: IE Mobile

8900a/1.2 Mozilla/4.0 (compatible; MSIE 6.0; Windows CE; IEMobile 7.6)
Agent Type: mobile browser
Bot Name: IE Mobile

SAMSUNG-S8000/S8000XEIF6 SHP/VPP/R5 Jasmine/1.0 Nextreaming SMM-MMS/1.2.0 profile/MIDP-2.1 configuration/CLDC-1.1
Agent Type: mobile browser
Bot Name: Jasmine

SAMSUNG-GT-S5600-Vodafone/S5600BUID1 SHP/VPP/R5 Jasmine/0.8 Qtv5.3 SMM-MMS/1.2.0 profile/MIDP-2.1 configuration/CLDC-1.1
Agent Type: mobile browser
Bot Name: Jasmine

Mozilla/5.0 (X11; U; Linux armv7l; en-GB; rv:1.9.2a1pre) Gecko/20090514 Firefox/3.0 Tablet browser 0.9.7 RX-34
Agent Type: mobile browser
Bot Name: MicroB

Mozilla/5.0 (X11; U; Linux armv6l; rv: 1.8.1.5pre) Gecko/20070619 Minimo/0.020
Agent Type: mobile browser
Bot Name: Minimo

MOT-V3i/08.B4.34R MIB/2.2.1 Profile/MIDP-2.0
Agent Type: mobile browser
Bot Name: Motorola Internet Browser

MOT-V3r/0E.C0.13R MIB/2.2.1 Profile/MIDP-2.0 Configuration/CLDC-1.1
Agent Type: mobile browser
Bot Name: Motorola Internet Browser

MOT-L6/0A.52.45R MIB/2.2.1 Profile/MIDP-2.0 Configuration/CLDC-1.1
Agent Type: mobile browser
Bot Name: Motorola Internet Browser

Mozilla/4.08 (Windows; Mobile Content Viewer/1.0) NetFront/3.2
Agent Type: other
Bot Name: NetFront Mobile Content Viewer

Mozilla/5.0 (Danger hiptop 4.0; U; rv:1.7.12) Gecko/20050920
Agent Type: mobile browser
Bot Name: NetFront

Amoi 8709/R14.4 NF-Browser/3.4
Agent Type: mobile browser
Bot Name: NetFront

Mozilla/4.0 (PDA; PalmOS/sony/model prmr/Revision:1.1.54 (en)) NetFront/3.0
Agent Type: mobile browser
Bot Name: NetFront

Mozilla/4.0 (PDA; Windows CE/1.0.1) NetFront/3.0
Agent Type: mobile browser
Bot Name: NetFront

Mozilla/5.0 (SymbianOS/9.2; U; Series60/3.1 NokiaE51-1/220.34.37; Profile/MIDP-2.0 Configuration/CLDC-1.1 ) AppleWebKit/413 (KHTML, like Gecko) Safari/413
Agent Type: mobile browser
Bot Name: Nokia Web Browser

Mozilla/5.0 (SymbianOS/9.2; U; Series60/3.1 NokiaN95/11.0.026; Profile MIDP-2.0 Configuration/CLDC-1.1) AppleWebKit/413 (KHTML, like Gecko) Safari/413
Agent Type: mobile browser
Bot Name: Nokia Web Browser

Nokia3250/2.0 (04.21) SymbianOS/9.1 Series60/3.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 UP.Link/6.5.1.3.0 Novarra-Vision/7.3
Agent Type: mobile browser
Bot Name: Nokia Web Browser

NokiaE65-1/3.0 (1.0633.18.01) SymbianOS/9.1 Series60/3.0 Profile/MIDP-2.0 Configuration/CLDC-1.1
Agent Type: mobile browser
Bot Name: Nokia Web Browser

NokiaN93-1/20.0.04
Agent Type: mobile browser
Bot Name: Nokia Web Browser

Mozilla/5.0 (SymbianOS/9.2; U; Series60/3.1 NokiaN82/31.0.016; Profile/MIDP-2.0 Configuration/CLDC-1.1 ) AppleWebKit/413 (KHTML, like Gecko) Safari/413
Agent Type: mobile browser
Bot Name: Nokia Web Browser

Mozilla/5.0 (SymbianOS/9.2; U; Series60/3.1 NokiaN81-1/1.00 Profile/MIDP-2.0 Configuration/CLDC-1.1) AppleWebKit/413 (KHTML, like Gecko) Safari/413
Agent Type: mobile browser
Bot Name: Nokia Web Browser

NokiaE50-1/3.0 (07.36.0.0) SymbianOS/9.1 Series60/3.0 Profile/MIDP-2.0 Configuration/CLDC-1.1
Agent Type: mobile browser
Bot Name: Nokia Web Browser

Alcatel-OT-S520/1.0 ObigoInternetBrowser/Q03C
Agent Type: mobile browser
Bot Name: Obigo

LG-CU720/V1.0g Obigo/Q05A Profile/MIDP-2.0 Configuration/CLDC-1.1 UP.Link/6.3.0.0.0
Agent Type: mobile browser
Bot Name: Obigo

LG-KB770-Orange/v10c Browser/Teleca-Q7.1 MMS/LG-MMS-V1.0/1.2 Java/ASVM/1.1 Profile/MIDP-2.1 Configuration/CLDC-1.1 UNTRUSTED/1.0
Agent Type: mobile browser
Bot Name: Obigo

Samsung-SPHA900 AU-MIC-A900/2.0 MMP/2.0 Profile/MIDP-2.0 Configuration/CLDC-1.1
Agent Type: mobile browser
Bot Name: Obigo

SONIM-XP1 / Obigo Browser 2.0
Agent Type: mobile browser
Bot Name: Obigo

Samsung-SPHA920 AU-MIC-A920/2.0 MMP/2.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 Novarra-Vision/7.3
Agent Type: mobile browser
Bot Name: Obigo

LG-KC550 Teleca/WAP2.0 MIDP-2.0/CLDC-1.1
Agent Type: mobile browser
Bot Name: Obigo

LG-CU720/V1.0l Obigo/Q05A Profile/MIDP-2.0 Configuration/CLDC-1.1
Agent Type: mobile browser
Bot Name: Obigo

UP.Browser/7.0.2.3.119 (GUI) MMP/2.0 Push/PO
Agent Type: mobile browser
Bot Name: Openwave Mobile Browser

KWC-S1300/ UP.Browser/7.2.6.1.839 (GUI) MMP/2.0
Agent Type: mobile browser
Bot Name: Openwave Mobile Browser

UP.Browser/3.04-TS14 UP.Link/3.4.4
Agent Type: mobile browser
Bot Name: Openwave Mobile Browser

Opera/8.01 (J2ME/MIDP; Opera Mini/3.1.9427/1724; nb; U; ssr)
Agent Type: mobile browser
Bot Name: Opera Mini

Opera/8.01 (J2ME/MIDP; Opera Mini/1.1.3475/hifi/tmobile/cz; SonyEricsson W880i; cs; U; ssr)
Agent Type: mobile browser
Bot Name: Opera Mini

Opera/9.60 (J2ME/MIDP; Opera Mini/4.2.14320/554; U; cs) Presto/2.2.0
Agent Type: mobile browser
Bot Name: Opera Mini

Opera/9.60 (J2ME/MIDP; Opera Mini/5.0.15650/960; U; en) Presto/2.2.0
Agent Type: mobile browser
Bot Name: Opera Mini

SAMSUNG-GT-i8000/1.0 (Windows CE; Opera Mobi; U; en) Opera 9.5
Agent Type: mobile browser
Bot Name: Opera Mobile

Opera/9.80 (S60; SymbOS; Opera Mobi/499; U; es-ES) Presto/2.4.18 Version/10.00
Agent Type: mobile browser
Bot Name: Opera Mobile

LG-LX600 Polaris/6.0 MMP/2.0 Profile/MIDP-2.1 Configuration/CLDC-1.1
Agent Type: mobile browser
Bot Name: Polaris

Samsung-SPHM320 Infraware-Polaris/5.01 MMP/2.0
Agent Type: mobile browser
Bot Name: Polaris

Samsung-SPHM320 Polaris/5.0 MMP/2.0
Agent Type: mobile browser
Bot Name: Polaris

UTSTARCOM-GTX75/UC1.25 POLARIS/6.00 Profile/MIDP-2.0 Configuration/CLDC-1.1 UP.Link/6.3.0.0.0
Agent Type: mobile browser
Bot Name: Polaris

SonyEricssonK750i/R1CA/SN352557010359373 Browser/SEMC-Browser/4.2 Profile/MIDP-2.0 Configuration/CLDC-1.1
Agent Type: mobile browser
Bot Name: SEMC Browser

SonyEricssonK750i/R1L Browser/SEMC-Browser/4.2 Profile/MIDP-2.0 Configuration/CLDC-1.1
Agent Type: mobile browser
Bot Name: SEMC Browser

Mozilla/5.0 (X11; U; Linux armv6l; fi-fi) AppleWebKit/528.5  (KHTML, like Gecko, Safari/528.5 ) tear
Agent Type: mobile browser
Bot Name: Tear

Mozilla/5.0 (Macintosh; U; Intel Mac OS X; en) AppleWebKit/418.9.1 (KHTML, like Gecko) Safari/419.3 TeaShark/0.8
Agent Type: mobile browser
Bot Name: TeaShark

UCWEB7.0.0.33/27/999
Agent Type: mobile browser
Bot Name: UC Browser

NOKIAN82 UCWEB
Agent Type: mobile browser
Bot Name: UC Browser

Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 5.2; WOW64; Trident/4.0; uZardWeb/1.0; Server_USA)
Agent Type: mobile browser
Bot Name: uZard Web

Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.2; SV1; uZardWeb/1.0; Server_JP)
Agent Type: mobile browser
Bot Name: uZard Web

Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.2; WOW64; SV1; uZardWeb/1.0; Server_HK)
Agent Type: mobile browser
Bot Name: uZard Web

GcMail Browser/1.0 (compatible; MSIE 5.0; Windows 98) 
Agent Type: email client
Bot Name: GcMail

Mozilla/4.0 (compatible; Lotus-Notes/5.0; Windows-NT)
Agent Type: email client
Bot Name: Lotus Notes

Mozilla/4.0 (compatible; Lotus-Notes/6.0; Windows-NT)
Agent Type: email client
Bot Name: Lotus Notes

Mozilla/4.0 (compatible; Lotus-Notes/5.0; Macintosh PPC)
Agent Type: email client
Bot Name: Lotus Notes

Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 5.1; .NET CLR 1.1.4322; .NET CLR 2.0.50727; MSOffice 12)
Agent Type: email client
Bot Name: Outlook 2007

Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.1; WOW64; Trident/4.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; InfoPath.2; AskTB5.5; MSOffice 12)
Agent Type: email client
Bot Name: Outlook 2007

Microsoft Office/14.0 (Windows NT 5.1; Microsoft Outlook 14.0.4536; Pro; MSOffice 14)
Agent Type: email client
Bot Name: Outlook 2010

Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.0; Trident/4.0; InfoPath.2; MSOffice 14)
Agent Type: email client
Bot Name: Outlook 2010

PocoMail/3.2.2004
Agent Type: email client
Bot Name: PocoMail

PocoMail/4.1.3650
Agent Type: email client
Bot Name: PocoMail

Pocomail/4.8.4400
Agent Type: email client
Bot Name: PocoMail

Postbox 1.0b14 (Windows/2009072715)
Agent Type: email client
Bot Name: Postbox

Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10.6; en-US; rv:1.9.1.8) Gecko/20100317 Postbox/1.1.3
Agent Type: email client
Bot Name: Postbox

Mozilla/5.0 (X11; U; Linux x86_64; en-US; rv:1.9.1.9pre) Gecko/20100308 Lightning/1.0b1 Shredder/3.0.4pre
Agent Type: email client
Bot Name: Shredder

Mozilla/5.0 (X11; U; Linux x86_64; en-US; rv:1.9.1.9pre) Gecko/20100209 Shredder/3.0.2pre
Agent Type: email client
Bot Name: Shredder

Mozilla/5.0 (X11; U; Linux x86_64; en-US; rv:1.9.1.9pre) Gecko/20100303 Shredder/3.0.4pre
Agent Type: email client
Bot Name: Shredder

Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.9.0.2pre) Gecko/2009031304 Spicebird/0.7.1 
Agent Type: email client
Bot Name: Spicebird

Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.9.0.2pre) Gecko/2009031117 Spicebird/0.7.1
Agent Type: email client
Bot Name: Spicebird

The Bat! 4.0.14
Agent Type: email client
Bot Name: The Bat!

The Bat! 4.0.0.22
Agent Type: email client
Bot Name: The Bat!

Mozilla/5.0 (Windows; U; Windows NT 6.0; en-US; rv:1.8.1.19) Gecko/20081209 Thunderbird/2.0.0.19
Agent Type: email client
Bot Name: Thunderbird

Mozilla/5.0 (Windows; U; Windows NT 5.1; cs; rv:1.9.1.8) Gecko/20100227 Lightning/1.0b1 Thunderbird/3.0.3
Agent Type: email client
Bot Name: Thunderbird

Mozilla/5.0 (Windows; U; Windows NT 6.0; en-US; rv:1.9pre) Gecko/2008050715 Thunderbird/3.0a1
Agent Type: email client
Bot Name: Thunderbird

Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.8.1.14) Gecko/20080505 Thunderbird/2.0.0.14
Agent Type: email client
Bot Name: Thunderbird

Mozilla/5.0 (Windows; U; Windows NT 5.1; cs; rv:1.8.1.21) Gecko/20090302 Lightning/0.9 Thunderbird/2.0.0.21
Agent Type: email client
Bot Name: Thunderbird

Outlook-Express/7.0 (MSIE 7.0; Windows NT 5.1; Trident/4.0; AskTB5.6; TmstmpExt)
Agent Type: email client
Bot Name: Windows Live Mail

Outlook-Express/7.0 (MSIE 7.0; Windows NT 6.1; WOW64; Trident/4.0; SLCC2; Media Center PC 6.0; OfficeLiveConnector.1.4; OfficeLivePatch.1.3; InfoPath.3; FDM; TmstmpExt)
Agent Type: email client
Bot Name: Windows Live Mail

Outlook-Express/7.0 (MSIE 7.0; Windows NT 6.1; Trident/4.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; TmstmpExt)
Agent Type: email client
Bot Name: Windows Live Mail

Mozilla/5.0 (Windows; U; cs-CZ) AppleWebKit/526.9+ (KHTML, like Gecko) AdobeAIR/1.5.1
Agent Type: library
Bot Name: Adobe AIR runtime

curl/7.15.1 (x86_64-suse-linux) libcurl/7.15.1 OpenSSL/0.9.8a zlib/1.2.3 libidn/0.6.0
Agent Type: library
Bot Name: cURL

curl 7.16.1 (i386-portbld-freebsd6.2) libcurl/7.16.1 OpenSSL/0.9.7m zlib/1.2.3
Agent Type: library
Bot Name: cURL

Feed::Find/0.06
Agent Type: library
Bot Name: Feed::Find

UniversalFeedParser/4.1 +http://feedparser.org/
Agent Type: library
Bot Name: FeedParser

GStreamer souphttpsrc libsoup/2.27.4
Agent Type: library
Bot Name: GStreamer

GStreamer souphttpsrc libsoup/2.26.2
Agent Type: library
Bot Name: GStreamer

HTTP_Request2/0.5.2 (http://pear.php.net/package/http_request2) PHP/5.2.10-2ubuntu6.4
Agent Type: library
Bot Name: HTTP_Request2

HTTP_Request2/0.5.1_(http://pear.php.net/package/http_request2) PHP/5.3.2-0.dotdeb.2 20100430220945
Agent Type: library
Bot Name: HTTP_Request2

Mozilla/3.0 (compatible; Indy Library)
Agent Type: library
Bot Name: Indy Library

Jakarta Commons-HttpClient/2.0
Agent Type: library
Bot Name: Jakarta Commons-HttpClient

Jakarta Commons-HttpClient/3.0-rc3
Agent Type: library
Bot Name: Jakarta Commons-HttpClient

Java/1.4.2_08
Agent Type: library
Bot Name: Java

Java1.3.1_06
Agent Type: library
Bot Name: Java

Java/1.6.0_03
Agent Type: library
Bot Name: Java

libsoup/2.26.1
Agent Type: library
Bot Name: LibSoup

libsoup/2.26.2
Agent Type: library
Bot Name: LibSoup

libwww-perl/5.53
Agent Type: library
Bot Name: libwww-perl

libwww-perl/5.812
Agent Type: library
Bot Name: libwww-perl

LWP::Simple/5.812
Agent Type: library
Bot Name: LWP::Simple

lwp-trivial/1.41
Agent Type: library
Bot Name: LWP::Simple

lwp-trivial/1.35
Agent Type: library
Bot Name: LWP::Simple

MagpieRSS/0.72 (+http://magpierss.sf.net; No cache)
Agent Type: library
Bot Name: MagpieRSS

php-openid/2.1.1 (php/5.2.5.fb4) curl/7.15.5
Agent Type: library
Bot Name: PHP OpenID library

PHPCrawl
Agent Type: library
Bot Name: PHPcrawl

Poe-Component-Client-HTTP/0.88
Agent Type: library
Bot Name: POE-Component-Client-HTTP

PycURL/7.13.2
Agent Type: library
Bot Name: PycURL

PycURL/7.19.0
Agent Type: library
Bot Name: PycURL

Python-urllib
Agent Type: library
Bot Name: Python-urllib

Python-urllib/2.1
Agent Type: library
Bot Name: Python-urllib

Python-urllib/2.4
Agent Type: library
Bot Name: Python-urllib

Python-webchecker/50851
Agent Type: library
Bot Name: Python-webchecker

Rome Client (http://tinyurl.com/64t5n) Ver: 0.9
Agent Type: library
Bot Name: ROME library

Rome Client (http://tinyurl.com/64t5n) Ver: 0.7
Agent Type: library
Bot Name: ROME library

SimplePie/1.1.2 (Feed Parser; http://simplepie.org; Allow like Gecko) Build/20081109150825 
Agent Type: library
Bot Name: SimplePie

SimplePie/1.0 b3.2 (Feed Parser; http://simplepie.org/; Allow like Gecko) Build/20061124
Agent Type: library
Bot Name: SimplePie

Snoopy v1.2.1
Agent Type: library
Bot Name: Snoopy

libsummer/0.2.0 libsoup/2.24.3
Agent Type: library
Bot Name: Summer

Typhoeus - http://github.com/pauldix/typhoeus/tree/master
Agent Type: library
Bot Name: Typhoeus

urlgrabber/3.1.0
Agent Type: library
Bot Name: urlgrabber

WinHttp
Agent Type: library
Bot Name: WinHTTP

WWW-Mechanize/0.7.6 (http://rubyforge.org/projects/mechanize/)
Agent Type: library
Bot Name: WWW::Mechanize

WWW-Mechanize/1.54
Agent Type: library
Bot Name: WWW::Mechanize

xine/1.1.16.3
Agent Type: library
Bot Name: xine

xine/1.1.14.1
Agent Type: library
Bot Name: xine

XML-RPC for PHP 2.2.1
Agent Type: library
Bot Name: XML-RPC for PHP

Klondike/1.50 (HTTP Win32)
Agent Type: wap
Bot Name: Klondike

WapTiger/5.0 (http://www.waptiger.com/ ()
Agent Type: wap
Bot Name: WapTiger

WinWAP-SPBE/1.3 (1.3.0.2;Win32)
Agent Type: wap
Bot Name: WinWap

WinWAP/4.1 (Win32) WinWAP-X/4.1.0.192
Agent Type: wap
Bot Name: WinWap

2Bone_LinkChecker/1.0 libwww-perl/5.803
Agent Type: validator
Bot Name: 2Bone LinkChecker

topSUBMIT.de HTMLChecker/1.1
Agent Type: validator
Bot Name: anw HTMLChecker

anw webtool LoadControl/1.3
Agent Type: validator
Bot Name: anw LoadControl

Checkbot/1.76
Agent Type: validator
Bot Name: Checkbot

Checkbot/1.80 LWP/5.80
Agent Type: validator
Bot Name: Checkbot

CSE HTML Validator Lite Online (http://online.htmlvalidator.com/php/onlinevallite.php)
Agent Type: validator
Bot Name: CSE HTML Validator

Cynthia 1.0
Agent Type: validator
Bot Name: Cynthia

FeedValidator/1.3
Agent Type: validator
Bot Name: FeedValidator

HTMLParser/1.6
Agent Type: validator
Bot Name: HTMLParser

LinkChecker/4.9 ( http://linkchecker.sourceforge.net/)
Agent Type: validator
Bot Name: LinkChecker

LinkChecker/5.1 ( http://linkchecker.sourceforge.net/)
Agent Type: validator
Bot Name: LinkChecker

LinkExaminer/1.00 (Windows)
Agent Type: validator
Bot Name: LinkExaminer

LinkExaminer/1.01 (Windows)
Agent Type: validator
Bot Name: LinkExaminer

LinkWalker/2.0 - www.seventwentyfour.com/
Agent Type: validator
Bot Name: LinkWalker

W3C_Multipage_Validator/2.0 (+http://www.validator.ca/)
Agent Type: validator
Bot Name: Multipage Validator

P3P Validator
Agent Type: validator
Bot Name: P3P Validator

FPLinkChecker/1.2
Agent Type: validator
Bot Name: PHP link checker

REL Link Checker Lite 1.0
Agent Type: validator
Bot Name: REL Link Checker Lite

W3C-checklink/4.2.1 [4.21] libwww-perl/5.803
Agent Type: validator
Bot Name: W3C Checklink

W3C-checklink/3.6.2.3 libwww-perl/5.64
Agent Type: validator
Bot Name: W3C Checklink

Jigsaw/2.2.5 W3C_CSS_Validator_JFouffa/2.0
Agent Type: validator
Bot Name: W3C CSS Validator

W3C-mobileOK/DDC-1.0 (see http://www.w3.org/2006/07/mobileok-ddc)
Agent Type: validator
Bot Name: W3C mobileOK Checker

W3C_Validator/1.432.2.22
Agent Type: validator
Bot Name: W3C Validator

W3C_Validator/1.654
Agent Type: validator
Bot Name: W3C Validator

CSSCheck/1.2.2
Agent Type: validator
Bot Name: WDG CSSCheck

Page Valet/4.1pre5
Agent Type: validator
Bot Name: WDG Page Valet

WDG_Validator/1.6.4
Agent Type: validator
Bot Name: WDG Validator

WDG_Validator/1.1
Agent Type: validator
Bot Name: WDG Validator

Xenu Link Sleuth 1.2d
Agent Type: validator
Bot Name: Xenu

Abilon
Agent Type: feed reader
Bot Name: Abilon

Akregator/1.2.9; librss/remnants
Agent Type: feed reader
Bot Name: Akregator

Akregator/1.2.2; librss/remnants
Agent Type: feed reader
Bot Name: Akregator

Akregator/1.2.5; librss/remnants
Agent Type: feed reader
Bot Name: Akregator

Apple-PubSub/65.1.1
Agent Type: feed reader
Bot Name: Apple-PubSub

Apple-PubSub/65.12.1
Agent Type: feed reader
Bot Name: Apple-PubSub

Apple-PubSub/65.6
Agent Type: feed reader
Bot Name: Apple-PubSub

Awasu/2.4PE
Agent Type: feed reader
Bot Name: Awasu

BlogBridge 6.6.2 Discoverer (http://www.blogbridge.com/) 1.6.0_10
Agent Type: feed reader
Bot Name: BlogBridge

BlogBridge 6.6.2 (http://www.blogbridge.com/) 1.6.0_07
Agent Type: feed reader
Bot Name: BlogBridge

Bloglines/3.1 (http://www.bloglines.com)
Agent Type: feed reader
Bot Name: Bloglines

CPG RSS Module File Reader
Agent Type: feed reader
Bot Name: CPG Dragonfly RSS Module

Dragonfly File Reader
Agent Type: feed reader
Bot Name: CPG Dragonfly RSS Module

CPG Dragonfly RSS Module Feed Viewer
Agent Type: feed reader
Bot Name: CPG Dragonfly RSS Module

Fastladder FeedFetcher/0.01 (http://fastladder.com/; 1 subscriber)
Agent Type: feed reader
Bot Name: Fastladder FeedFetcher

Feedfetcher-Google; (+http://www.google.com/feedfetcher.html; 1 subscribers; feed-id=6098063775789346370)
Agent Type: feed reader
Bot Name: Feedfetcher-Google

GreatNews/1.0
Agent Type: feed reader
Bot Name: GreatNews

Gregarius/0.5.2 (+http://devlog.gregarius.net/docs/ua)
Agent Type: feed reader
Bot Name: Gregarius

Gregarius/0.6.0 (+http://devlog.gregarius.net/docs/ua)
Agent Type: feed reader
Bot Name: Gregarius

Liferea/1.4.14 (Linux; en_US.UTF8; http://liferea.sf.net/)
Agent Type: feed reader
Bot Name: Liferea

Mozilla/5.0 (Macintosh; U; Intel Mac OS X; en) AppleWebKit/419 (KHTML, like Gecko) NetNewsWire/2.1.1
Agent Type: feed reader
Bot Name: NetNewsWire

Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_5_5; en-us) AppleWebKit/525.18 (KHTML, like Gecko) NetNewsWire/3.1.7
Agent Type: feed reader
Bot Name: NetNewsWire

NetNewsWire/3.2d7 (Mac OS X; http://www.newsgator.com/Individuals/NetNewsWire/)
Agent Type: feed reader
Bot Name: NetNewsWire

newsbeuter/1.2 (Linux 2.6.18-xen-r12-xm-217; x86_64; http://www.newsbeuter.org/) libcurl/7.19.4 GnuTLS/2.6.6 zlib/1.2.3
Agent Type: feed reader
Bot Name: Newsbeuter

Ilium Software NewsBreak http://www.iliumsoft.com
Agent Type: feed reader
Bot Name: NewsBreak

Mozilla/5.0 NewsFox/1.0.5
Agent Type: feed reader
Bot Name: NewsFox

Mozilla/5.0 NewsFox/1.0.4.1
Agent Type: feed reader
Bot Name: NewsFox

NewsGatorOnline/2.0 (http://www.newsgator.com; 1 subscribers)
Agent Type: feed reader
Bot Name: NewsGatorOnline

NFReader/1.4.1.0 (http://www.gaijin.at/)
Agent Type: feed reader
Bot Name: NFReader

NFReader/1.3.9.0 (http://www.gaijin.at/)
Agent Type: feed reader
Bot Name: NFReader

JetBrains Omea Reader 2.2 (http://www.jetbrains.com/omea/reader/)
Agent Type: feed reader
Bot Name: Omea Reader

RssBandit/1.2.0.114 (.NET CLR 1.1.4322.573; WinNT 5.1.2600.0; http://www.rssbandit.org)
Agent Type: feed reader
Bot Name: Rss Bandit

RssBandit/1.9.0.972
Agent Type: feed reader
Bot Name: Rss Bandit

RSS Menu/1.11.6 (Mac OS X; http://www.edot-studios.com)
Agent Type: feed reader
Bot Name: RSS Menu

Mozilla/4.0 (compatible; RSS Popper)
Agent Type: feed reader
Bot Name: RSS Popper

RSSOwl/2.0.0.200903042053 (Windows; U; en)
Agent Type: feed reader
Bot Name: RSSOwl

RSSOwl/2.0.0.200804242342
Agent Type: feed reader
Bot Name: RSSOwl

Mozilla/5.0 (Sage)
Agent Type: feed reader
Bot Name: Sage

HomePage Rss Reader 1.0; (1 subscribers; feed-id=82385)
Agent Type: feed reader
Bot Name: Seznam RSS reader

SharpReader/0.9.4.1 (.NET CLR 1.1.4322.573; WinNT 5.1.2600.0)
Agent Type: feed reader
Bot Name: SharpReader

SharpReader/0.9.6.0 (.NET CLR 1.1.4322.2032; WinNT 5.1.2600.0)
Agent Type: feed reader
Bot Name: SharpReader

YahooFeedSeeker/2.0 (compatible; Mozilla 4.0; MSIE 5.5; http://publisher.yahoo.com/rssguide; users 0; views 0)
Agent Type: feed reader
Bot Name: YahooFeedSeeker

YeahReader [http://www.yeahreader.com/]
Agent Type: feed reader
Bot Name: YeahReader

Banshee 1.5.1 (http://banshee-project.org/)
Agent Type: multimedia player
Bot Name: Banshee

boxee (alpha/Windows  build 7077 - 0.9.7.4825)
Agent Type: multimedia player
Bot Name: Boxxe

boxee (alpha/Darwin 8.7.1 i386 - 0.9.11.5591)
Agent Type: multimedia player
Bot Name: Boxxe

boxee (alpha/Linux 2.6.28-11-generic #40-Ubuntu SMP Fri Apr 3 17:39:41 UTC 2009 x86_64 - 0.9.7.4826M)
Agent Type: multimedia player
Bot Name: Boxxe

boxee (alpha/Darwin 9.5.2 i386 - 0.9.11.5591)
Agent Type: multimedia player
Bot Name: Boxxe

boxee (alpha/Windows XP Professional Service Pack 3, v.5755 build 2600 - 0.9.9.5324)
Agent Type: multimedia player
Bot Name: Boxxe

CorePlayer/1.0 (Series 60 3rd ; ARM; de) CorePlayer/1.3.2_6909
Agent Type: multimedia player
Bot Name: CorePlayer

CorePlayer/1.0 (Windows 5.01; x86 Intel; hu) CorePlayer/2.0.0_6873
Agent Type: multimedia player
Bot Name: CorePlayer

CorePlayer/1.0 (PocketPC 5.02; ARM 1136J; en) CorePlayer/1.3.2_6909
Agent Type: multimedia player
Bot Name: CorePlayer

FlyCast/1.34 (BlackBerry; 8330/4.5.0.131 Profile/MIDP-2.0 Configuration/CLDC-1.1 VendorID/-1)
Agent Type: multimedia player
Bot Name: FlyCast

FlyCast/1.35 (BlackBerry; 9530/4.7.0.99 Profile/MIDP-2.0 Configuration/CLDC-1.1 VendorID/-1)
Agent Type: multimedia player
Bot Name: FlyCast

FlyCast/1.32 (BlackBerry; 8330/4.3.0.124 Profile/MIDP-2.0 Configuration/CLDC-1.1 VendorID/-1)
Agent Type: multimedia player
Bot Name: FlyCast

foobar2000/0.9.5.2
Agent Type: multimedia player
Bot Name: foobar2000

foobar2000/0.9.6.5_beta_2
Agent Type: multimedia player
Bot Name: foobar2000

foobar2000/0.9.6.8
Agent Type: multimedia player
Bot Name: foobar2000

GomPlayer 2, 1, 17, 4710 (ENG)
Agent Type: multimedia player
Bot Name: GOM Player

GomPlayer 2, 1, 9, 3753 (ENG)
Agent Type: multimedia player
Bot Name: GOM Player

Miro/2.0.4 (http://www.getmiro.com/; Windows XP )
Agent Type: multimedia player
Bot Name: Miro

Miro/2.0 (http://www.getmiro.com/; Darwin 9.4.0 Power Macintosh)
Agent Type: multimedia player
Bot Name: Miro

Democracy/0.8.1 (http://www.participatoryculture.org)
Agent Type: multimedia player
Bot Name: Miro

Miro/2.1-svn (http://www.getmiro.com/; Windows 2000 )
Agent Type: multimedia player
Bot Name: Miro

Miro/2.0.3 (http://www.getmiro.com/; Linux 2.6.24-1-686 i686)
Agent Type: multimedia player
Bot Name: Miro

Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.9) Gecko Miro/2.0.4 (http://www.getmiro.com/)
Agent Type: multimedia player
Bot Name: Miro

Miro/3.0.1 (http://www.getmiro.com/; Darwin 8.11.1 i386)
Agent Type: multimedia player
Bot Name: Miro

MPlayer/SVN-r29189-snapshot-4.3.2
Agent Type: multimedia player
Bot Name: MPlayer

MPlayer/29040-4.3.3
Agent Type: multimedia player
Bot Name: MPlayer

PocketTunes/5.5.2
Agent Type: multimedia player
Bot Name: Pocket Tunes

PublicRadioPlayer/2.1 CFNetwork/459 Darwin/9.8.0
Agent Type: multimedia player
Bot Name: Public Radio Player

PublicRadioApp/1.3 CFNetwork/459 Darwin/10.0.0d3
Agent Type: multimedia player
Bot Name: Public Radio Player

QuickTime/7.6 (qtver=7.6;cpu=IA32;os=Mac 10,5,7)
Agent Type: multimedia player
Bot Name: QuickTime

QuickTime/7.6.2 (verqt=7.6.2;cpu=IA32;so=Mac 10.5.8)
Agent Type: multimedia player
Bot Name: QuickTime

QuickTime (qtver=7.0.2a26;os=Windows NT 6.0)
Agent Type: multimedia player
Bot Name: QuickTime

QuickTime/7.6.2 (qtver=7.6.2;os=Windows NT 5.1Service Pack 3)
Agent Type: multimedia player
Bot Name: QuickTime

QuickTime.7.6 (qtver=7.6;os=Windows NT 6.0Service Pack 2)
Agent Type: multimedia player
Bot Name: QuickTime

RSS_Radio 1.493
Agent Type: multimedia player
Bot Name: RSS Radio

Mozilla/5.0 (Windows; U; Windows NT 5.1; cs; rv:1.9.0.5) Gecko/2009021916 Songbird/1.1.2 (20090331142126)
Agent Type: multimedia player
Bot Name: Songbird

Mozilla/5.0 (X11; U; Linux i686; fr; rv:1.9.0.5) Gecko/2009021916 Songbird/1.1.2 (20090331141709)
Agent Type: multimedia player
Bot Name: Songbird

VLC media player - version 0.9.8a Grishenko - (c) 1996-2008 the VideoLAN team
Agent Type: multimedia player
Bot Name: VLC media player

VLC media player - version 0.9.8 Grishenko - (c) 1996-2009 the VideoLAN team
Agent Type: multimedia player
Bot Name: VLC media player

VLC media player - version 0.8.6g Janus - (c) 1996-2008 the VideoLAN team
Agent Type: multimedia player
Bot Name: VLC media player

VLC media player - version 1.1.0-git Yellow Bastard - (c) 1996-2009 the VideoLAN team
Agent Type: multimedia player
Bot Name: VLC media player

VLC media player - version 0.9.9 Grishenko - (c) 1996-2009 the VideoLAN team
Agent Type: multimedia player
Bot Name: VLC media player

Windows-Media-Player/11.0.6001.7000
Agent Type: multimedia player
Bot Name: Windows Media Player

Windows-Media-Player/9.00.00.3086
Agent Type: multimedia player
Bot Name: Windows Media Player

XBMC/9.04 r19840 (Mac OS X; Darwin 9.6.0; http://www.xbmc.org)
Agent Type: multimedia player
Bot Name: XBMC

XBMC/9.04-beta1 r19616 (Linux; Ubuntu 9.04; Linux 2.6.28-11-generic; http://www.xbmc.org)
Agent Type: multimedia player
Bot Name: XBMC

XBMC/9.04-beta1 r19639 (Windows; Windows XP Professional Service Pack 2 build 2600; http://www.xbmc.org)
Agent Type: multimedia player
Bot Name: XBMC

XMPlay/3.5
Agent Type: multimedia player
Bot Name: XMPlay

ApacheBench/2.3
Agent Type: other
Bot Name: AB (Apache Bench)

Mozilla/4.0 (compatible; Win32; ActiveXperts.Http.3.1)
Agent Type: other
Bot Name: ActiveXperts Network Monitor

Bookdog/5.2
Agent Type: other
Bot Name: Bookdog

Bookdog/5.1.44
Agent Type: other
Bot Name: Bookdog

Claws Mail GtkHtml2 plugin 0.24 (http://www.claws-mail.org/plugins.php)
Agent Type: other
Bot Name: Claws Mail GtkHtml2 plugin

Cyberduck/3.3 (5552)
Agent Type: other
Bot Name: Cyberduck

DownloadStudio/4.0
Agent Type: other
Bot Name: DownloadStudio

Funambol Mozilla Sync Client v0.9.1
Agent Type: other
Bot Name: Funambol Mozilla Sync Client

Funambol Outlook Plug-in v. 7.0.7
Agent Type: other
Bot Name: Funambol Outlook Sync Client

gvfs/1.0.3
Agent Type: other
Bot Name: GnomeVFS

gvfs/1.3.1
Agent Type: other
Bot Name: GnomeVFS

gvfs/0.2.3
Agent Type: other
Bot Name: GnomeVFS

GoldenPod 0.8.1 (podcatcher) libwwwperl
Agent Type: other
Bot Name: GoldenPod

AppEngine-Google; ( http://code.google.com/appengine)
Agent Type: other
Bot Name: Google App Engine

AppEngine-Google; (+http://code.google.com/appengine)
Agent Type: other
Bot Name: Google App Engine

Mozilla/5.0 (Windows; U; Windows NT 5.1; cs-CZ) AppleWebKit/532.4 (KHTML, like Gecko) Google Earth/5.2.1.1329 Safari/532.4
Agent Type: other
Bot Name: Google Earth

Google-Listen/1.0.3.1 (sapphire COC10)
Agent Type: other
Bot Name: Google Listen

Google-Listen/1.0.3.1 (hero CUPCAKE)
Agent Type: other
Bot Name: Google Listen

Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.0;Google Wireless Transcoder;)
Agent Type: other
Bot Name: Google Wireless Transcoder

Mozilla/5.0 (en-us) AppleWebKit/525.13 (KHTML, like Gecko; Google Wireless Transcoder) Version/3.1 Safari/525.13,Mozilla/5.0 (en-us) AppleWebKit/525.13 (KHTML, like Gecko; Google Wireless Transcoder) Version/3.1 Safari/525.13
Agent Type: other
Bot Name: Google Wireless Transcoder

gPodder/0.15.2 (+http://gpodder.org/)
Agent Type: other
Bot Name: gPodder

GSiteCrawler/v1.23 rev. 286 (http://gsitecrawler.com/)
Agent Type: other
Bot Name: GSiteCrawler

GSiteCrawler/v1.12 rev. 260 (http://gsitecrawler.com/)
Agent Type: other
Bot Name: GSiteCrawler

holmes/3.9 (xiantravelguide.com)
Agent Type: other
Bot Name: Holmes

holmes/3.9 (flashigri7.wordpress.com)
Agent Type: other
Bot Name: Holmes

holmes/3.9 (http://brightkite.com/people/freshcontent)
Agent Type: other
Bot Name: Holmes

holmes/3.9 (evro.chasi24.com)
Agent Type: other
Bot Name: Holmes

check_http/v2053 (nagios-plugins 1.4.13)
Agent Type: other
Bot Name: HTTP nagios plugin

iVideo Lite 1.2 (iPhone; iPhone OS 3.1.2; de_AT)
Agent Type: other
Bot Name: iVideo

Windows NT/5.1, UPnP/1.0, Jamcast/1.0
Agent Type: other
Bot Name: Jamcast

Jamcast 0.9.8.33
Agent Type: other
Bot Name: Jamcast

Windows NT/5.1, UPnP/1.0, Jamcast/0.9
Agent Type: other
Bot Name: Jamcast

LeechCraft (X11; U; Linux; ru_RU) (LeechCraft/Poshuku 0.3.55-324-g9365f23; WebKit 4.5.2/4.5.2)
Agent Type: other
Bot Name: LeechCraft

LeechCraft (X11; U; Linux; ru_RU) (LeechCraft/Poshuku 0.3.55-383-g7446455; WebKit 4.5.2/4.5.2)
Agent Type: other
Bot Name: LeechCraft

lftp/3.7.4
Agent Type: other
Bot Name: LFTP

lftp/3.7.3
Agent Type: other
Bot Name: LFTP

LinkbackPlugin/0.1 Laconica/0.8.0dev
Agent Type: other
Bot Name: LinkbackPlugin for Laconica

LinkbackPlugin/0.1 Laconica/0.8.0
Agent Type: other
Bot Name: LinkbackPlugin for Laconica

LinkbackPlugin/0.1 Laconica/0.7.3
Agent Type: other
Bot Name: LinkbackPlugin for Laconica

Microsoft Data Access Internet Publishing Provider DAV
Agent Type: other
Bot Name: Microsoft WebDAV client

Microsoft Data Access Internet Publishing Provider DAV 1.1 
Agent Type: other
Bot Name: Microsoft WebDAV client

muCommander-file-API (Java 11.3-b02; Windows XP 5.1 x86)
Agent Type: other
Bot Name: muCommander

muCommander v0.8.3 (Java 1.6.0_0-b11; Linux 2.6.24-19-generic i386)
Agent Type: other
Bot Name: muCommander

muCommander v0.8.3 (Java 1.4.2_03-b02; Windows XP 5.1 x86)
Agent Type: other
Bot Name: muCommander

Mozilla/4.0 (compatible; BorderManager 3.0)
Agent Type: other
Bot Name: Novell BorderManager

Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_5_7; fr-fr) AppleWebKit/525.28.3 (KHTML, like Gecko) Paparazzi!/0.5b5 (like Safari)
Agent Type: other
Bot Name: Paparazzi!

PHP/5.2.6
Agent Type: other
Bot Name: PHP

PHP/5.2.8
Agent Type: other
Bot Name: PHP

PHP/5.2.8-pl2-gentoo
Agent Type: other
Bot Name: PHP

Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.9.0.11pre) Gecko/2009042918 Prism/1.0b1
Agent Type: other
Bot Name: Prism

Mozilla/5.0 (compatible; PRTG Network Monitor (www.paessler.com); Windows)
Agent Type: other
Bot Name: PRTG Network Monitor

Radio Downloader 0.8.0.0
Agent Type: other
Bot Name: Radio Downloader

Radio Downloader 0.8.2.0
Agent Type: other
Bot Name: Radio Downloader

SZN-Image-Resizer
Agent Type: other
Bot Name: Seznam WAP Proxy

Nokia6230/2.0 (03.15) Profile/MIDP-2.0 Configuration/CLDC-1.1/szn-mobile-transcoder
Agent Type: other
Bot Name: Seznam WAP Proxy

Mozilla/5.0 (Windows; U; Windows NT 5.1; cs; rv:1.9.0.14) Gecko/2009082707 Firefox/3.0.14/szn-mobile-transcoder
Agent Type: other
Bot Name: Seznam WAP Proxy

Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1; .NET CLR 2.0.50727; .NET CLR 3.0.04506.648; .NET CLR 3.5.21022; .NET CLR 1.1.4322)/szn-mobile-transcoder
Agent Type: other
Bot Name: Seznam WAP Proxy

JoeDog/1.00 [en] (X11; I; Siege 2.66)
Agent Type: other
Bot Name: Siege

JoeDog/1.00 [en] (X11; I; Siege 2.68)
Agent Type: other
Bot Name: Siege

TulipChain/6.03 (http://ostermiller.org/tulipchain/) Java/1.6.0_07 (http://java.sun.com/) Windows_XP/5.1 RPT-HTTPClient/0.3-3
Agent Type: other
Bot Name: Tulip Chain

TulipChain/6.03 (http://ostermiller.org/tulipchain/) Java/1.6.0_0 (http://java.sun.com/) Linux/2.6.27.25-170.2.72_1.cubbi_tuxonice.fc10.x86_64 RPT-HTTPClient/0.3-3
Agent Type: other
Bot Name: Tulip Chain

Azureus 4.3.0.4;Windows 7;Java 1.6.0_18-ea
Agent Type: other
Bot Name: Vuze

Azureus 4.3.0.4
Agent Type: other
Bot Name: Vuze

Azureus 4.3.0.4;Windows XP;Java 1.7.0-ea
Agent Type: other
Bot Name: Vuze

webcollage.perl/1.107
Agent Type: other
Bot Name: WebCollage

webcollage1/1.129
Agent Type: other
Bot Name: WebCollage

webcollage/1.127
Agent Type: other
Bot Name: WebCollage

webcollage-noporn/1.127
Agent Type: other
Bot Name: WebCollage

webcollage.pl/1.133
Agent Type: other
Bot Name: WebCollage

webcollage.modified/1.148
Agent Type: other
Bot Name: WebCollage

webfs/2.0 (plan 9)
Agent Type: other
Bot Name: webfs

WinPodder (http://winpodder.com)
Agent Type: other
Bot Name: WinPodder

http://Anonymouse.org/ (Unix)
Agent Type: useragent anonymizer
Bot Name: Anonymouse.org

192.comAgent
Agent Type: bot
Bot Name: 192.comAgent

50.nu/0.01 ( +http://50.nu/bot.html )
Agent Type: bot
Bot Name: 50.nu

Mozilla/5.0 (compatible; 008/0.83; http://www.80legs.com/spider.html;) Gecko/2008032620
Agent Type: bot
Bot Name: 80legs

Mozilla/5.0 (compatible; 008/0.83; http://www.80legs.com/webcrawler.html;) Gecko/2008032620
Agent Type: bot
Bot Name: 80legs

Mozilla/5.0 (compatible; 80bot/0.71; http://www.80legs.com/spider.html;) Gecko/2008032620
Agent Type: bot
Bot Name: 80legs

Mozilla/5.0 (compatible; abby/1.0; +http://www.ellerdale.com/crawler.html)
Agent Type: bot
Bot Name: abby

AboutUsBot
Agent Type: bot
Bot Name: AboutUsBot

Mozilla/5.0 (compatible; AboutUsBot Johnny5/2.0; +http://www.AboutUs.org/)
Agent Type: bot
Bot Name: AboutUsBot

Mozilla/5.0 (compatible; AboutUsBot/0.9; +http://www.aboutus.org/AboutUsBot)
Agent Type: bot
Bot Name: AboutUsBot

Accelobot
Agent Type: bot
Bot Name: Accelobot

Accoona-AI-Agent/1.1.1 (crawler at accoona dot com)
Agent Type: bot
Bot Name: Accoona-AI-Agent

Accoona-AI-Agent/1.1.2 (aicrawler at accoonabot dot com)
Agent Type: bot
Bot Name: Accoona-AI-Agent

Acoon-Robot 4.0.2.17 (http://www.acoon.de)
Agent Type: bot
Bot Name: Acoon-Robot

Acoon-Robot 4.0.2 (http://www.acoon.de)
Agent Type: bot
Bot Name: Acoon-Robot

Acoon-Robot 4.0.1 (http://www.acoon.de)
Agent Type: bot
Bot Name: Acoon-Robot

Acoon-Robot 4.0.0RC2 (http://www.acoon.de)
Agent Type: bot
Bot Name: Acoon-Robot

OpenAcoon v4.1.0 (www.openacoon.de)
Agent Type: bot
Bot Name: Acoon-Robot

Acorn/Nutch-0.9 (Non-Profit Search Engine; acorn.isara.org; acorn at isara dot org)
Agent Type: bot
Bot Name: Acorn

www.adressendeutschland.de
Agent Type: bot
Bot Name: adressendeutschland.de

AdsBot-Google (+http://www.google.com/adsbot.html)
Agent Type: bot
Bot Name: AdsBot-Google

AdsBot-Google
Agent Type: bot
Bot Name: AdsBot-Google

Mozilla/5.0 (compatible; aiHitBot/1.0; +http://www.aihit.com/)
Agent Type: bot
Bot Name: aiHitBot

Mozilla/5.0 (compatible; aiHitBot/1.0-DS; +http://www.aihit.com/)
Agent Type: bot
Bot Name: aiHitBot

Mozilla/5.0 (compatible; aiHitBot-DM/2.0.2 +http://www.aihit.com)
Agent Type: bot
Bot Name: aiHitBot

appie 1.1 (www.walhello.com)
Agent Type: bot
Bot Name: aippie

Mozilla/5.0 (compatible; akula/k311; +http://k311.fd.cvut.cz/)
Agent Type: bot
Bot Name: akula

Mozilla/5.0 (compatible; akula/12.0rc-2; +http://k311.fd.cvut.cz/)
Agent Type: bot
Bot Name: akula

http://www.almaden.ibm.com/cs/crawler   [bc6]
Agent Type: bot
Bot Name: Almaden

http://www.almaden.ibm.com/cs/crawler   [fc13]
Agent Type: bot
Bot Name: Almaden

http://www.almaden.ibm.com/cs/crawler   [bc12]
Agent Type: bot
Bot Name: Almaden

http://www.almaden.ibm.com/cs/crawler
Agent Type: bot
Bot Name: Almaden

http://www.almaden.ibm.com/cs/crawler   [bc5]
Agent Type: bot
Bot Name: Almaden

http://www.almaden.ibm.com/cs/crawler   [hc4]
Agent Type: bot
Bot Name: Almaden

http://www.almaden.ibm.com/cs/crawler   [bc22]
Agent Type: bot
Bot Name: Almaden

http://www.almaden.ibm.com/cs/crawler   [bc14]
Agent Type: bot
Bot Name: Almaden

http://www.amagit.com/
Agent Type: bot
Bot Name: Amagit.COM

Amfibibot/0.07 (Amfibi Robot; http://www.amfibi.com; agent@amfibi.com)
Agent Type: bot
Bot Name: Amfibibot

amibot - http://www.amidalla.de - tech@amidalla.com libwww-perl/5.831
Agent Type: bot
Bot Name: amibot

Mozilla/5.0 (compatible; AportWorm/3.2; +http://www.aport.ru/help)
Agent Type: bot
Bot Name: AportWorm

http://arachnode.net 1.2
Agent Type: bot
Bot Name: arachnode.net

ASAHA Search Engine Turkey V.001 (http://www.asaha.com/)
Agent Type: bot
Bot Name: ASAHA Search Engine Turkey

Mozilla/2.0 (compatible; Ask Jeeves/Teoma; +http://about.ask.com/en/docs/about/webmasters.shtml)
Agent Type: bot
Bot Name: Ask Jeeves/Teoma

Mozilla/2.0 (compatible; Ask Jeeves/Teoma)
Agent Type: bot
Bot Name: Ask Jeeves/Teoma

Mozilla/2.0 (compatible; Ask Jeeves/Teoma; +http://sp.ask.com/docs/about/tech_crawling.html)
Agent Type: bot
Bot Name: Ask Jeeves/Teoma

Mozilla/5.0 (compatible; Ask Jeeves/Teoma; +http://about.ask.com/en/docs/about/webmasters.shtml)
Agent Type: bot
Bot Name: Ask Jeeves/Teoma

Mozilla/2.0 (compatible; Ask Jeeves/Teoma; http://about.ask.com/en/docs/about/webmasters.shtml)
Agent Type: bot
Bot Name: Ask Jeeves/Teoma

BabalooSpider/1.3 (BabalooSpider; http://www.babaloo.si; spider@babaloo.si)
Agent Type: bot
Bot Name: BabalooSpider

Baiduspider+(+http://www.baidu.jp/spider/)
Agent Type: bot
Bot Name: Baiduspider

Baiduspider+(+http://www.baidu.com/search/spider.htm)
Agent Type: bot
Bot Name: Baiduspider

baypup/colbert (Baypup; http://sf.baypup.com/webmasters; jason@baypup.com)
Agent Type: bot
Bot Name: baypup

baypup/1.1 (Baypup; http://www.baypup.com/; jason@baypup.com)
Agent Type: bot
Bot Name: baypup

baypup/colbert (Baypup; http://www.baypup.com/webmasters; jason@baypup.com)
Agent Type: bot
Bot Name: baypup

BDFetch
Agent Type: bot
Bot Name: BDFetch

Mozilla/5.0 (compatible; BecomeBot/3.0; MSIE 6.0 compatible; +http://www.become.com/site_owners.html)
Agent Type: bot
Bot Name: BecomeBot

Mozilla/5.0 (compatible; BecomeJPBot/2.3; MSIE 6.0 compatible; +http://www.become.co.jp/site_owners.html)
Agent Type: bot
Bot Name: BecomeBot

Mozilla/5.0 (compatible; BecomeBot/3.0; +http://www.become.com/site_owners.html)
Agent Type: bot
Bot Name: BecomeBot

Mozilla/5.0 (compatible; BecomeBot/2.3; MSIE 6.0 compatible; +http://www.become.com/site_owners.html)
Agent Type: bot
Bot Name: BecomeBot

Bigsearch.ca/Nutch-0.9-dev (Bigsearch.ca Internet Spider; http://www.bigsearch.ca/; info@enhancededge.com)
Agent Type: bot
Bot Name: Bigsearch.ca

Bigsearch.ca/Nutch-1.0-dev (Bigsearch.ca Internet Spider; http://www.bigsearch.ca/; info@enhancededge.com)
Agent Type: bot
Bot Name: Bigsearch.ca

Mozilla/5.0 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)
Agent Type: bot
Bot Name: bingbot

bitlybot
Agent Type: bot
Bot Name: bitlybot

Mozilla/5.0 (compatible; bixolabs/1.0; +http://bixolabs.com/crawler/general; crawler@mail.bixolabs.com)
Agent Type: bot
Bot Name: bixolabs

Mozilla/5.0 (compatible; bixolabs/1.0; +http://bixolabs.com/crawler/general; crawler@bixolabs.com)
Agent Type: bot
Bot Name: bixolabs

Blaiz-Bee/2.00.6082 (+http://www.blaiz.net)
Agent Type: bot
Bot Name: Blaiz-Bee

Blaiz-Bee/2.00.5622 (+http://www.blaiz.net)
Agent Type: bot
Bot Name: Blaiz-Bee

Blaiz-Bee/2.00.5655 (+http://www.blaiz.net)
Agent Type: bot
Bot Name: Blaiz-Bee

Blaiz-Bee/2.00.8315 (BE Internet Search Engine http://www.rawgrunt.com)
Agent Type: bot
Bot Name: Blaiz-Bee

Mozilla/5.0 (compatible; BlinkaCrawler/1.0; +http://www.blinka.jp/crawler/)
Agent Type: bot
Bot Name: BlinkaCrawler

Bloggsi/1.0 (http://bloggsi.com/)
Agent Type: bot
Bot Name: Bloggsi

BlogPulseLive (support@blogpulse.com)
Agent Type: bot
Bot Name: BlogPulse

BlogPulse (ISSpider-3.0)
Agent Type: bot
Bot Name: BlogPulse

boitho.com-dc/0.85 ( http://www.boitho.com/dcbot.html )
Agent Type: bot
Bot Name: boitho.com-dc

boitho.com-dc/0.82 ( http://www.boitho.com/dcbot.html )
Agent Type: bot
Bot Name: boitho.com-dc

boitho.com-dc/0.79 ( http://www.boitho.com/dcbot.html )
Agent Type: bot
Bot Name: boitho.com-dc

boitho.com-dc/0.86 ( http://www.boitho.com/dcbot.html )
Agent Type: bot
Bot Name: boitho.com-dc

boitho.com-dc/0.83 ( http://www.boitho.com/dcbot.html )
Agent Type: bot
Bot Name: boitho.com-dc

Nokia6680/1.0 (4.04.07) SymbianOS/8.0 Series60/2.6 Profile/MIDP-2.0 Configuration/CLDC-1.1 (botmobi find.mobi/bot.html find@mtld.mobi)
Agent Type: bot
Bot Name: botmobi

BotOnParade, http://www.bots-on-para.de/bot.html
Agent Type: bot
Bot Name: BotOnParade

Browsershots
Agent Type: bot
Bot Name: Browsershots

btbot/0.4 (+http://www.btbot.com/btbot.html)
Agent Type: bot
Bot Name: btbot

Mozilla/5.0 (compatible; Butterfly/1.0; +http://labs.topsy.com/butterfly.html) Gecko/2009032608 Firefox/3.0.8
Agent Type: bot
Bot Name: Butterfly

Mozilla/5.0 (compatible; Butterfly/1.0; +http://labs.topsy.com/butterfly/) Gecko/2009032608 Firefox/3.0.8
Agent Type: bot
Bot Name: Butterfly

Mozilla/5.0 (compatible; BuzzRankingBot/1.0; +http://www.buzzrankingbot.com/)
Agent Type: bot
Bot Name: BuzzRankingBot

CamontSpider/1.0 +http://epweb2.ph.bham.ac.uk/user/slater/camont/info.html
Agent Type: bot
Bot Name: CamontSpider

CatchBot/2.0; +http://www.catchbot.com
Agent Type: bot
Bot Name: CatchBot

CatchBot/1.0; +http://www.catchbot.com
Agent Type: bot
Bot Name: CatchBot

CazoodleBot/CazoodleBot-0.1 (CazoodleBot Crawler; http://www.cazoodle.com/cazoodlebot; cazoodlebot@cazoodle.com)
Agent Type: bot
Bot Name: CazoodleBot

Cazoodle/Nutch-0.9-dev (Cazoodle Nutch Crawler; http://www.cazoodle.com; mqbot@cazoodle.com)
Agent Type: bot
Bot Name: CazoodleBot

CazoodleBot/0.0.2 (http://www.cazoodle.com/contact.php; cbot@cazoodle.com)
Agent Type: bot
Bot Name: CazoodleBot

CazoodleBot/Nutch-0.9-dev (CazoodleBot Crawler; http://www.cazoodle.com/cazoodlebot; cazoodlebot@cazoodle.com)
Agent Type: bot
Bot Name: CazoodleBot

CazoodleBot/Nutch-0.9-dev (CazoodleBot Crawler; http://www.cazoodle.com; mqbot@cazoodle.com)
Agent Type: bot
Bot Name: CazoodleBot

CazoodleBot/0.1 (CazoodleBot Crawler; http://www.cazoodle.com; mqbot@cazoodle.com)
Agent Type: bot
Bot Name: CazoodleBot

CCBot/1.0 (+http://www.commoncrawl.org/bot.html)
Agent Type: bot
Bot Name: CCBot

ccubee/10.0
Agent Type: bot
Bot Name: ccubee

ccubee/3.3
Agent Type: bot
Bot Name: ccubee

ccubee/9.0
Agent Type: bot
Bot Name: ccubee

ccubee/3.2
Agent Type: bot
Bot Name: ccubee

ccubee/4.0
Agent Type: bot
Bot Name: ccubee

ccubee/3.7
Agent Type: bot
Bot Name: ccubee

ccubee/3.5
Agent Type: bot
Bot Name: ccubee

ccubee/2008
Agent Type: bot
Bot Name: ccubee

mozilla/4.0 (compatible; changedetection/1.0 (admin@changedetection.com))
Agent Type: bot
Bot Name: changedetection

Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1;  http://www.changedetection.com/bot.html )
Agent Type: bot
Bot Name: ChangeDetection

Mozilla/5.0 (compatible; Charlotte/1.1; http://www.searchme.com/support/)
Agent Type: bot
Bot Name: Charlotte

City4you/1.3 Cesky (+http://www.city4you.pl)
Agent Type: bot
Bot Name: City4you

Cityreview Robot (+http://www.cityreview.org/crawler/)
Agent Type: bot
Bot Name: cityreview

CJB.NET Proxy
Agent Type: bot
Bot Name: CJB.NET Proxy

Combine/3 http://combine.it.lth.se/
Agent Type: bot
Bot Name: Combine

ConveraCrawler/0.9e (+http://www.authoritativeweb.com/crawl)
Agent Type: bot
Bot Name: ConveraCrawler

ConveraCrawler/0.9d (+http://www.authoritativeweb.com/crawl)
Agent Type: bot
Bot Name: ConveraCrawler

ConveraMultiMediaCrawler/0.1 (+http://www.authoritativeweb.com/crawl)
Agent Type: bot
Bot Name: ConveraCrawler

copyright sheriff (+http://www.copyrightsheriff.com/)
Agent Type: bot
Bot Name: copyright sheriff

CorpusCrawler 2.0.0 (http://corpora.fi.muni.cz/crawler/)
Agent Type: bot
Bot Name: CorpusCrawler

CorpusCrawler 2.0.14 (http://corpora.fi.muni.cz/crawler/)
Agent Type: bot
Bot Name: CorpusCrawler

CorpusCrawler 2.0.19 (http://corpora.fi.muni.cz/crawler/);Project:CzCorpus
Agent Type: bot
Bot Name: CorpusCrawler

CorpusCrawler 2.0.21 (http://corpora.fi.muni.cz/crawler/);Project:CzCorpus
Agent Type: bot
Bot Name: CorpusCrawler

CorpusCrawler 2.0.8 (http://corpora.fi.muni.cz/crawler/)
Agent Type: bot
Bot Name: CorpusCrawler

CorpusCrawler 2.0.20 (http://corpora.fi.muni.cz/crawler/);Project:CzCorpus
Agent Type: bot
Bot Name: CorpusCrawler

CorpusCrawler 2.0.22 (http://corpora.fi.muni.cz/crawler/);Project:CzCorpus
Agent Type: bot
Bot Name: CorpusCrawler

CorpusCrawler 2.0.9 (http://corpora.fi.muni.cz/crawler/)
Agent Type: bot
Bot Name: CorpusCrawler

CorpusCrawler 2.0.13 (http://corpora.fi.muni.cz/crawler/)
Agent Type: bot
Bot Name: CorpusCrawler

CorpusCrawler 2.0.15 (http://corpora.fi.muni.cz/crawler/)
Agent Type: bot
Bot Name: CorpusCrawler

CorpusCrawler 2.0.12 (http://corpora.fi.muni.cz/crawler/)
Agent Type: bot
Bot Name: CorpusCrawler

CorpusCrawler 2.0.24 (http://corpora.fi.muni.cz/crawler/);Project:CzCorpus
Agent Type: bot
Bot Name: CorpusCrawler

CorpusCrawler 2.0.25 (http://corpora.fi.muni.cz/crawler/);Project:CzCorpus
Agent Type: bot
Bot Name: CorpusCrawler

CorpusCrawler 2.0.10 (http://corpora.fi.muni.cz/crawler/)
Agent Type: bot
Bot Name: CorpusCrawler

CorpusCrawler 2.0.17 (http://corpora.fi.muni.cz/crawler/);Project:CzCorpus
Agent Type: bot
Bot Name: CorpusCrawler

csci_b659/0.13
Agent Type: bot
Bot Name: csci_b659

DataFountains/DMOZ Feature Vector Corpus Creator (http://ivia.ucr.edu/useragents.shtml)
Agent Type: bot
Bot Name: DataFountains

DataFountains/Dmoz Downloader (http://ivia.ucr.edu/useragents.shtml)
Agent Type: bot
Bot Name: DataFountains

DataparkSearch/4.40.1 (+http://www.dataparksearch.org/)
Agent Type: bot
Bot Name: DataparkSearch

Mozilla/4.0 (compatible; MSIE enviable; DAUMOA/1.0.1; DAUM Web Robot; Daum Communications Corp., Korea; +http://ws.daum.net/aboutkr.html)
Agent Type: bot
Bot Name: Daumoa

Mozilla/4.0 (compatible; MSIE enviable; DAUMOA 2.0; DAUM Web Robot; Daum Communications Corp., Korea; +http://ws.daum.net/aboutkr.html)
Agent Type: bot
Bot Name: Daumoa

Mozilla/5.0 (compatible; MSIE or Firefox mutant; not on Windows server; +http://ws.daum.net/aboutWebSearch.html) Daumoa/2.0
Agent Type: bot
Bot Name: Daumoa

Mozilla/4.0 (compatible; MSIE is not me; DAUMOA/1.0.0; DAUM Web Robot; Daum Communications Corp., Korea)
Agent Type: bot
Bot Name: Daumoa

Mozilla/4.0 (compatible; MSIE is not me; DAUMOA/1.0.1; DAUM Web Robot; Daum Communications Corp., Korea)
Agent Type: bot
Bot Name: Daumoa

Mozilla/5.0 (compatible; DBLBot/1.0; +http://www.dontbuylists.com/)
Agent Type: bot
Bot Name: DBLBot

DealGates Bot/1.1 by Luc Michalski (http://spider.dealgates.com/bot.html)
Agent Type: bot
Bot Name: DealGates Bot

del.icio.us-thumbnails/1.0 Mozilla/5.0 (compatible; Konqueror/3.4; FreeBSD) KHTML/3.4.2 (like Gecko)
Agent Type: bot
Bot Name: del.icio.us-thumbnails

Mozilla/5.0 (compatible; del.icio.us-thumbnails/1.0; FreeBSD) KHTML/4.3.2 (like Gecko)
Agent Type: bot
Bot Name: del.icio.us-thumbnails

Mozilla/4.0 (compatible; DepSpid/5.10; +http://about.depspid.net)
Agent Type: bot
Bot Name: DepSpid

depspid - the dependency spider
Agent Type: bot
Bot Name: DepSpid

Mozilla/4.0 (compatible; DepSpid/5.25; +http://about.depspid.net)
Agent Type: bot
Bot Name: DepSpid

Mozilla/4.0 (compatible; DepSpid/5.07; +http://about.depspid.net)
Agent Type: bot
Bot Name: DepSpid

Mozilla/4.0 (compatible; DepSpid/5.24; +http://about.depspid.net)
Agent Type: bot
Bot Name: DepSpid

Mozilla/4.0 (compatible; DepSpid/5.26; +http://about.depspid.net)
Agent Type: bot
Bot Name: DepSpid

mozilla/5.0 (compatible; discobot/1.1; +http://discoveryengine.com/discobot.html)
Agent Type: bot
Bot Name: discobot

Mozilla/5.0 (compatible; DKIMRepBot/1.0; +http://www.dkim-reputation.org)
Agent Type: bot
Bot Name: DKIMRepBot

Mozilla/5.0 (compatible; DNS-Digger-Explorer/1.0; +http://www.dnsdigger.com)
Agent Type: bot
Bot Name: DNS-Digger-Explorer

Mozilla/4.0 (compatible; MSIE 5.01; Windows NT 5.0; DomainDB-1.1; http://domaindb.com/crawler/)
Agent Type: bot
Bot Name: DomainDB

Mozilla/5.0 (compatible; DotBot/1.1; http://www.dotnetdotcom.org/, crawler@dotnetdotcom.org)
Agent Type: bot
Bot Name: DotBot

Mozilla/5.0 (compatible; dotSemantic/1.0; +http://www.dotsemantic.org)
Agent Type: bot
Bot Name: dotSemantic

DuckDuckBot/1.0; (+http://duckduckgo.com/duckduckbot.html)
Agent Type: bot
Bot Name: DuckDuckBot

e-SocietyRobot(http://www.yama.info.waseda.ac.jp/~yamana/es/)
Agent Type: bot
Bot Name: e-SocietyRobot

eCairn-Grabber/1.0 (+http://ecairn.com/grabber) curl/7.15
Agent Type: bot
Bot Name: eCairn-Grabber

Mozilla/4.0 (compatible; EDI/1.6.6; Edacious & Intelligent Web Robot; Daum Communications Corp., Korea)
Agent Type: bot
Bot Name: EDI

EDI/1.6.5 (Edacious & Intelligent Web Robot, Daum Communications Corp.)
Agent Type: bot
Bot Name: EDI

Mozilla/4.0 (compatible; MSIE is not me; EDI/1.6.6; Edacious & Intelligent Web Robot; Daum Communications Corp., Korea)
Agent Type: bot
Bot Name: EDI

Mozilla/5.0 (compatible; egothor/8.0g; +http://ego.ms.mff.cuni.cz/)
Agent Type: bot
Bot Name: egothor

Mozilla/5.0 (compatible; egothor/11.0d; +http://ego.ms.mff.cuni.cz/)
Agent Type: bot
Bot Name: egothor

egothor/8.0f (+http://ego.ms.mff.cuni.cz/)
Agent Type: bot
Bot Name: egothor

Mozilla/5.0 (compatible; egothor/11.0d; +https://kocour.ms.mff.cuni.cz/ego/)
Agent Type: bot
Bot Name: egothor

Mozilla/5.0 (compatible; egothor/12.0rc-2; +http://ego.ms.mff.cuni.cz/)
Agent Type: bot
Bot Name: egothor

ejupiter.com
Agent Type: bot
Bot Name: ejupiter.com

crawler43.ejupiter.com
Agent Type: bot
Bot Name: ejupiter.com

EnaBot/1.2 (http://www.enaball.com/crawler.html)
Agent Type: bot
Bot Name: EnaBot

EnaBot/1.1 (http://www.enaball.com/crawler.html)
Agent Type: bot
Bot Name: EnaBot

Enterprise_Search/1.00.143;MSSQL (http://www.innerprise.net/es-spider.asp)
Agent Type: bot
Bot Name: Enterprise_Search

envolk/1.7 (+http://www.envolk.com/envolkspiderinfo.html)
Agent Type: bot
Bot Name: envolk

Eurobot/1.1 (http://eurobot.ayell.eu)
Agent Type: bot
Bot Name: Eurobot

Eurobot/1.2 (http://eurobot.ayell.eu)
Agent Type: bot
Bot Name: Eurobot

Mozilla/5.0 (compatible; Exabot-Images/3.0; +http://www.exabot.com/go/robot)
Agent Type: bot
Bot Name: Exabot

Mozilla/5.0 (compatible; Exabot/3.0 (BiggerBetter); +http://www.exabot.com/go/robot)
Agent Type: bot
Bot Name: Exabot

Mozilla/5.0 (compatible; Exabot/3.0; +http://www.exabot.com/go/robot)
Agent Type: bot
Bot Name: Exabot

exactseek.com
Agent Type: bot
Bot Name: ExactSEEK

facebookexternalhit/1.0 (+http://www.facebook.com/externalhit_uatext.php)
Agent Type: bot
Bot Name: facebookexternalhit

Factbot 1.09
Agent Type: bot
Bot Name: factbot

Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1 + FairShare-http://fairshare.cc)
Agent Type: bot
Bot Name: FairShare

Mozilla/5.0 (compatible; Falconsbot; +http://iws.seu.edu.cn/services/falcons/contact_us.jsp)
Agent Type: bot
Bot Name: Falconsbot

Mozilla/5.0 (compatible; Falconsbot; +http://ws.nju.edu.cn/falcons/)
Agent Type: bot
Bot Name: Falconsbot

FAST Enterprise Crawler/6.4 (crawler@fast.no)
Agent Type: bot
Bot Name: FAST Enterprise Crawler

FAST Enterprise Crawler 6 used by Virk.dk - udvikling (thomas.bentzen@capgemini.com)
Agent Type: bot
Bot Name: FAST Enterprise Crawler

FAST Enterprise Crawler 6 used by FAST (jim.mosher@fastsearch.com)
Agent Type: bot
Bot Name: FAST Enterprise Crawler

FAST MetaWeb Crawler (helpdesk at fastsearch dot com)
Agent Type: bot
Bot Name: FAST MetaWeb Crawler

Mozilla/5.0 (FauBot/0.1; +http://buzzvolume.com/fau/)
Agent Type: bot
Bot Name: FauBot

favorstarbot/1.0 (+http://favorstar.com/bot.html)
Agent Type: bot
Bot Name: favorstarbot

FeedCatBot/3.0 (+http://www.feedcat.net/)
Agent Type: bot
Bot Name: FeedCatBot

Mozilla/4.0 (compatible; MSIE 5.01; Windows NT 5.0; FeedFinder-2.0; http://bloggz.se/crawler)
Agent Type: bot
Bot Name: FeedFinder/bloggz.se

Findexa Crawler (http://www.findexa.no/gulesider/article26548.ece)
Agent Type: bot
Bot Name: Findexa Crawler

findlinks/1.1.6-beta1 (+http://wortschatz.uni-leipzig.de/findlinks/)
Agent Type: bot
Bot Name: findlinks

findlinks/1.1.5-beta7 (+http://wortschatz.uni-leipzig.de/findlinks/)
Agent Type: bot
Bot Name: findlinks

flatlandbot/baypup (Flatland Industries Web Spider; http://www.flatlandindustries.com/flatlandbot; jason@flatlandindustries.com)
Agent Type: bot
Bot Name: Flatland Industries Web Spider

flatlandbot/flatlandbot (Flatland Industries Web Spider; http://www.flatlandindustries.com/flatlandbot.php; jason@flatlandindustries.com)
Agent Type: bot
Bot Name: flatlandbot

great-plains-web-spider/flatlandbot (Flatland Industries Web Spider; http://www.flatlandindustries.com/flatlandbot.php; jason@flatlandindustries.com)
Agent Type: bot
Bot Name: flatlandbot

great-plains-web-spider/gpws (Flatland Industries Web Spider; http://www.flatlandindustries.com/flatlandbot.php; jason@flatlandindustries.com)
Agent Type: bot
Bot Name: flatlandbot

great-plains-web-spider/flatlandbot (Flatland Industries Web Robot; http://www.flatlandindustries.com/flatlandbot.php; jason@flatlandindustries.com)
Agent Type: bot
Bot Name: flatlandbot

http://www.uni-koblenz.de/~flocke/robot-info.txt
Agent Type: bot
Bot Name: Flocke bot

FollowSite Bot ( http://www.followsite.com/bot.html )
Agent Type: bot
Bot Name: FollowSite Bot

Mozilla/4.0 (compatible; Fooooo_Web_Video_Crawl http://fooooo.com/bot.html)
Agent Type: bot
Bot Name: Fooooo_Web_Video_Crawl

Forschungsportal/0.8-dev (Testinstallation; http://www.forschungsportal.net/; fpcrawler@rrzn.uni-hannover.de)
Agent Type: bot
Bot Name: Forschungsportal

Francis/2.0 (francis@neomo.de http://www.neomo.de/pages/crawler.php)
Agent Type: bot
Bot Name: Francis

Mozilla/5.0 (compatible; FunnelBack; http://cyan.funnelback.com/robot.html)
Agent Type: bot
Bot Name: FunnelBack

Mozilla/4.0 compatible FurlBot/Furl Search 2.0 (FurlBot; http://www.furl.net; wn.furlbot@looksmart.net)
Agent Type: bot
Bot Name: FurlBot

FyberSpider/1.2 (http://www.fybersearch.com/fyberspider.php)
Agent Type: bot
Bot Name: FyberSpider

FyberSpider/1.3 (http://www.fybersearch.com/fyberspider.php)
Agent Type: bot
Bot Name: FyberSpider

g2Crawler (nobody@airmail.net)
Agent Type: bot
Bot Name: g2crawler

Gaisbot/3.0+(robot@gais.cs.ccu.edu.tw;+http://gais.cs.ccu.edu.tw/robot.php)
Agent Type: bot
Bot Name: Gaisbot

Gaisbot/3.0+(robot06@gais.cs.ccu.edu.tw;+http://gais.cs.ccu.edu.tw/robot.php)
Agent Type: bot
Bot Name: Gaisbot

Gallent Search Spider v1.4 Robot 3 (http://www.GallentSearch.com/robot)
Agent Type: bot
Bot Name: Gallent Search Spider

genieBot (wgao@genieknows.com)
Agent Type: bot
Bot Name: genieBot

genieBot ((http://64.5.245.11/faq/faq.html))
Agent Type: bot
Bot Name: genieBot

GeonaBot/1.2; http://www.geona.com/
Agent Type: bot
Bot Name: GeonaBot

Giant/1.0 (Openmaru bot; robot@openmaru.com)
Agent Type: bot
Bot Name: Giant/1.0

Gigabot/3.0 (http://www.gigablast.com/spider.html)
Agent Type: bot
Bot Name: Gigabot

GingerCrawler/1.0 (Language Assistant for Dyslexics; www.gingersoftware.com/crawler_agent.htm; support at ginger software dot com)
Agent Type: bot
Bot Name: GingerCrawler

Mozilla/4.0 (compatible; MSIE 5.0; Windows NT; Girafabot; girafabot at girafa dot com; http://www.girafa.com)
Agent Type: bot
Bot Name: Girafabot

Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.2; SV1; .NET CLR 1.1.4322; Girafabot [girafa.com])
Agent Type: bot
Bot Name: Girafabot

Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 4.0; Girafabot; girafabot at girafa dot com; http://www.girafa.com)
Agent Type: bot
Bot Name: Girafabot

GOFORITBOT ( http://www.goforit.com/about/ )
Agent Type: bot
Bot Name: GOFORITBOT

gonzo1[P] +http://www.suchen.de/faq.html
Agent Type: bot
Bot Name: gonzo

gonzo2[P] +http://www.suchen.de/faq.html
Agent Type: bot
Bot Name: gonzo

Mediapartners-Google
Agent Type: bot
Bot Name: Googlebot

Googlebot-Video/1.0
Agent Type: bot
Bot Name: Googlebot

Googlebot-Image/1.0
Agent Type: bot
Bot Name: Googlebot

Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)
Agent Type: bot
Bot Name: Googlebot

Mozilla/5.0 (compatible; GurujiBot/1.0; +http://www.guruji.com/en/WebmasterFAQ.html)
Agent Type: bot
Bot Name: GurujiBot

Mozilla/5.0 (compatible; Hailoobot/1.2; +http://www.hailoo.com/spider.html)
Agent Type: bot
Bot Name: Hailoobot

HatenaScreenshot/1.0 (checker)
Agent Type: bot
Bot Name: HatenaScreenshot

Mozilla/5.0 (X11; U; Linux i686 (x86_64); en-US; rv:1.8.1.20) Gecko/20090429 HeartRails_Capture/0.6 (+http://capture.heartrails.com/) BonEcho/2.0.0.20
Agent Type: bot
Bot Name: HeartRails_Capture

Mozilla/5.0 (compatible; heritrix/1.12.1b +http://netarkivet.dk/website/info.html)
Agent Type: bot
Bot Name: heritrix

Mozilla/5.0 (compatible; heritrix/2.0.2 +http://seekda.com)
Agent Type: bot
Bot Name: heritrix

Mozilla/5.0 (compatible; heritrix/1.14.2 +http://rjpower.org)
Agent Type: bot
Bot Name: heritrix

Mozilla/5.0 (compatible; heritrix/1.12.1 +http://www.webarchiv.cz)
Agent Type: bot
Bot Name: heritrix

Mozilla/5.0 (compatible; heritrix/1.14.3 +http://archive.org)
Agent Type: bot
Bot Name: heritrix

Mozilla/5.0 (compatible; heritrix/1.14.2 +http://www.webarchiv.cz)
Agent Type: bot
Bot Name: heritrix

Mozilla/5.0 (compatible; heritrix/2.0.2 +http://aihit.com)
Agent Type: bot
Bot Name: heritrix

Mozilla/5.0 (compatible; heritrix/1.14.3 +http://www.webarchiv.cz)
Agent Type: bot
Bot Name: heritrix

Mozilla/5.0 (compatible; heritrix/3.0.0-SNAPSHOT-20091120.021634 +http://crawler.archive.org)
Agent Type: bot
Bot Name: heritrix

Mozilla/5.0 (compatible; heritrix/1.12.0 +http://www.accelobot.com)
Agent Type: bot
Bot Name: heritrix

Mozilla/5.0 (compatible; heritrix/1.14.3.r6601 +http://www.buddybuzz.net/yptrino)
Agent Type: bot
Bot Name: heritrix

HiddenMarket-1.0-beta (www.hiddenmarket.net/crawler.php)
Agent Type: bot
Bot Name: HiddenMarket

holmes/3.11 (http://morfeo.centrum.cz/bot)
Agent Type: bot
Bot Name: Holmes

holmes/3.12.4 (http://morfeo.centrum.cz/bot)
Agent Type: bot
Bot Name: Holmes

holmes/3.10.1 (OnetSzukaj/5.0; +http://szukaj.onet.pl)
Agent Type: bot
Bot Name: Holmes

holmes/3.9 (onet.pl)
Agent Type: bot
Bot Name: Holmes

holmes/3.9 (OnetSzukaj/5.0; +http://szukaj.onet.pl)
Agent Type: bot
Bot Name: Holmes

holmes/3.11 (OnetSzukaj/5.0; +http://szukaj.onet.pl)
Agent Type: bot
Bot Name: Holmes

HolmesBot (http://holmes.ge)
Agent Type: bot
Bot Name: HolmesBot

HooWWWer/2.1.3 (debugging run) (+http://cosco.hiit.fi/search/hoowwwer/ | mailto:crawler-info<at>hiit.fi)
Agent Type: bot
Bot Name: HooWWWer

HooWWWer/2.2.0 (debugging run) (+http://cosco.hiit.fi/search/hoowwwer/ | mailto:crawler-info<at>hiit.fi)
Agent Type: bot
Bot Name: HooWWWer

Mozilla/4.0 (compatible; HostTracker.com/1.0;+http://host-tracker.com/)
Agent Type: bot
Bot Name: HostTracker.com

cinetic_htdig
Agent Type: bot
Bot Name: ht://Dig

HuaweiSymantecSpider/1.0+DSE-support@huaweisymantec.com+(compatible; MSIE 7.0; Windows NT 5.1; Trident/4.0; .NET CLR 2.0.50727; .NET CLR 3.0.4506.2152; .NET CLR ; http://www.huaweisymantec.com/en/IRL/spider)
Agent Type: bot
Bot Name: HuaweiSymantecSpider

iaskspider/2.0(+http://iask.com/help/help_index.html)
Agent Type: bot
Bot Name: iaskspider

ia_archiver-web.archive.org
Agent Type: bot
Bot Name: ia_archiver

ia_archiver (+http://www.alexa.com/site/help/webmasters; crawler@alexa.com)
Agent Type: bot
Bot Name: ia_archiver

ICC-Crawler(Mozilla-compatible; ; http://kc.nict.go.jp/project1/crawl.html)
Agent Type: bot
Bot Name: ICC-Crawler

ICC-Crawler/2.0 (Mozilla-compatible; ; http://kc.nict.go.jp/project1/crawl.html)
Agent Type: bot
Bot Name: ICC-Crawler

ICF_Site_Crawler+(see+http://www.infocenter.fi/spiderinfo.html)
Agent Type: bot
Bot Name: ICF_Site_Crawler

ichiro/2.0 (ichiro@nttr.co.jp)
Agent Type: bot
Bot Name: ichiro

ichiro/1.0 (ichiro@nttr.co.jp)
Agent Type: bot
Bot Name: ichiro

ichiro/4.0 (http://help.goo.ne.jp/door/crawler.html)
Agent Type: bot
Bot Name: ichiro

ichiro/2.0 (http://help.goo.ne.jp/door/crawler.html)
Agent Type: bot
Bot Name: ichiro

ichiro/3.0 (http://help.goo.ne.jp/door/crawler.html)
Agent Type: bot
Bot Name: ichiro

ichiro/2.01 (http://help.goo.ne.jp/door/crawler.html)
Agent Type: bot
Bot Name: ichiro

IlseBot/1.1
Agent Type: bot
Bot Name: IlseBot

IlTrovatore/1.2 (IlTrovatore; http://www.iltrovatore.it/bot.html; bot@iltrovatore.it)
Agent Type: bot
Bot Name: IlTrovatore

IlTrovatore-Setaccio/1.2 (It search engine; http://www.iltrovatore.it/bot.html; bot@iltrovatore.it)
Agent Type: bot
Bot Name: IlTrovatore-Setaccio

IlTrovatore-Setaccio/1.2 (Italy search engine; http://www.iltrovatore.it/bot.html; bot@iltrovatore.it)
Agent Type: bot
Bot Name: IlTrovatore-Setaccio

InfociousBot (+http://corp.infocious.com/tech_crawler.php)
Agent Type: bot
Bot Name: InfociousBot

InternetSeer.com
Agent Type: bot
Bot Name: InternetSeer

Ipselonbot/1.0-beta (+; http://www.ipselon.com/intl/en/ipselonbot.html)
Agent Type: bot
Bot Name: Ipselonbot

Ipselonbot/0.47-beta (Ipselon; http://www.ipselon.com/intl/en/ipselonbot.html; ipselonbot@ipselon.com)
Agent Type: bot
Bot Name: Ipselonbot

IRLbot/3.0 (compatible; MSIE 6.0; http://irl.cs.tamu.edu/crawler)
Agent Type: bot
Bot Name: IRLbot

IRLbot/2.0 (compatible; MSIE 6.0; http://irl.cs.tamu.edu/crawler)
Agent Type: bot
Bot Name: IRLbot

IRLbot/3.0 (compatible; MSIE 6.0; http://irl.cs.tamu.edu/crawler/)
Agent Type: bot
Bot Name: IRLbot

IRLbot/2.0 (+http://irl.cs.tamu.edu/crawler)
Agent Type: bot
Bot Name: IRLbot

JadynAve - http://www.jadynave.com/robot
Agent Type: bot
Bot Name: JadynAve

Mozilla/5.0 (compatible; JadynAveBot; +http://www.jadynave.com/robot)
Agent Type: bot
Bot Name: JadynAveBot

Jambot/0.1.1 (Jambot; http://www.jambot.com/blog; crawler@jambot.com)
Agent Type: bot
Bot Name: Jambot

JUST-CRAWLER(+http://www.justsystems.com/jp/tech/crawler/)
Agent Type: bot
Bot Name: JUST-CRAWLER

JyxobotRSS/0.06
Agent Type: bot
Bot Name: Jyxobot

Jyxobot/1
Agent Type: bot
Bot Name: Jyxobot

kakle-spider/0.1 (kakle-spider; http://www.kakle.com/bot.html; support@kakle.com)
Agent Type: bot
Bot Name: Kakle Bot

kalooga/KaloogaBot (Kalooga; http://www.kalooga.com/info.html?page=crawler; crawler@kalooga.com)
Agent Type: bot
Bot Name: Kalooga

kalooga/KaloogaBot (Kalooga; http://www.kalooga.com/info.html?page=crawler)
Agent Type: bot
Bot Name: Kalooga

Karneval-Bot (Version: 1.06, powered by www.karnevalsuchmaschine.de +http://www.karnevalsuchmaschine.de/bot.html)
Agent Type: bot
Bot Name: Karneval-Bot

KeywenBot/4.1  http://www.keywen.com/Encyclopedia/Links
Agent Type: bot
Bot Name: KeywenBot

Kongulo v0.1 personal web crawler
Agent Type: bot
Bot Name: Kongulo

KRetrieve/1.1/dbsearchexpert.com
Agent Type: bot
Bot Name: KRetrieve

Krugle/Krugle,Nutch/0.8+ (Krugle web crawler; http://corp.krugle.com/crawler/info.html; webcrawler@krugle.com)
Agent Type: bot
Bot Name: Krugle

Krugle/Krugle,Nutch/0.8+ (Krugle web crawler; http://www.krugle.com/crawler/info.html; webcrawler@krugle.com)
Agent Type: bot
Bot Name: Krugle

ksibot/8.0a (+http://ego.ms.mff.cuni.cz/)
Agent Type: bot
Bot Name: ksibot

ksibot/7.0d (+http://ego.ms.mff.cuni.cz/)
Agent Type: bot
Bot Name: ksibot

ksibot/5.2m (+http://ego.ms.mff.cuni.cz/)
Agent Type: bot
Bot Name: ksibot

L.webis/0.44 (http://webalgo.iit.cnr.it/index.php?pg=lwebis)
Agent Type: bot
Bot Name: L.webis

L.webis/0.53 (http://webalgo.iit.cnr.it/index.php?pg=lwebis)
Agent Type: bot
Bot Name: L.webis

L.webis/0.51 (http://webalgo.iit.cnr.it/index.php?pg=lwebis)
Agent Type: bot
Bot Name: L.webis

L.webis/0.50 (http://webalgo.iit.cnr.it/index.php?pg=lwebis)
Agent Type: bot
Bot Name: L.webis

LapozzBot/1.4 (+http://robot.lapozz.com)
Agent Type: bot
Bot Name: LapozzBot

LapozzBot/1.4 (+http://robot.lapozz.hu)
Agent Type: bot
Bot Name: LapozzBot

Larbin (larbin2.6.3@unspecified.mail)
Agent Type: bot
Bot Name: Larbin

LarbinWebCrawler (spider@download11.com)
Agent Type: bot
Bot Name: LarbinWebCrawler

LexxeBot/1.0 (lexxebot@lexxe.com)
Agent Type: bot
Bot Name: LexxeBot

Lijit Crawler (+http://www.lijit.com/robot/crawler)
Agent Type: bot
Bot Name: Lijit

LinguaBot/v0.001-dev (MultiLinual Sarch Engine v0.001; LinguaSeek; admin at linguaseek dot com)
Agent Type: bot
Bot Name: LinguaBot

Linguee Bot (http://www.linguee.com/bot)
Agent Type: bot
Bot Name: Linguee Bot

Link Valet Online 1.1
Agent Type: bot
Bot Name: Link Valet Online

Link Valet Online 1.2
Agent Type: bot
Bot Name: Link Valet Online

LinkAider (http://linkaider.com/crawler/)
Agent Type: bot
Bot Name: LinkAider

Mozilla/5.0 (compatible; LinksManager.com_bot +http://linksmanager.com/linkchecker.html)
Agent Type: bot
Bot Name: linksmanager_bot

LinkWalker/2.0
Agent Type: bot
Bot Name: LinkWalker

LinkWalker
Agent Type: bot
Bot Name: LinkWalker

livedoor ScreenShot/0.10
Agent Type: bot
Bot Name: livedoor ScreenShot

lmspider (lmspider@scansoft.com)
Agent Type: bot
Bot Name: lmspider

lmspider/Nutch-0.9-dev (For research purposes.; www.nuance.com)
Agent Type: bot
Bot Name: lmspider

magpie-crawler/1.1 (U; Linux amd64; en-GB; +http://www.brandwatch.net)
Agent Type: bot
Bot Name: magpie-crawler

Mahiti.Com/Mahiti Crawler-1.0 (Mahiti.Com; http://mahiti.com ; mahiti.com)
Agent Type: bot
Bot Name: Mahiti Crawler

Mail.Ru/1.0
Agent Type: bot
Bot Name: Mail.Ru

Megatext/Nutch-0.8.1 (Beta; http://www.megatext.cz/; microton@microton.cz)
Agent Type: bot
Bot Name: Megatext

Megatext/Megatext-0.5 (beta; http://www.megatext.cz/; microton@microton.cz)
Agent Type: bot
Bot Name: Megatext

Mozilla/5.0 (compatible; MetamojiCrawler/1.0; +http://www.metamoji.com/jp/crawler.html
Agent Type: bot
Bot Name: MetamojiCrawler

Metaspinner/0.01 (Metaspinner; http://www.meta-spinner.de/; support@meta-spinner.de/)
Agent Type: bot
Bot Name: Metaspinner/0.01

MetaTagRobot/2.1 (http://www.widexl.com/remote/search-engines/metatag-analyzer.html)
Agent Type: bot
Bot Name: MetaTagRobot

MetaTagRobot/1.6 (http://www.widexl.com/remote/search-engines/metatag-analyzer.html)
Agent Type: bot
Bot Name: MetaTagRobot

MetaURI API +metauri.com
Agent Type: bot
Bot Name: MetaURI

miniRank/3.1 (miniRank; www.minirank.com; website ranking engine)
Agent Type: bot
Bot Name: miniRank

miniRank/1.5 (miniRank; www.minirank.com; robot)
Agent Type: bot
Bot Name: miniRank

miniRank/1.6 (Website ranking; www.minirank.com; robot)
Agent Type: bot
Bot Name: miniRank

miniRank/2.0 (miniRank; http://minirank.com/; website ranking engine)
Agent Type: bot
Bot Name: miniRank

miniRank/1.2 (miniRank; http://minirank.com/; MiniRank)
Agent Type: bot
Bot Name: miniRank

Mozilla/5.0 (compatible; MJ12bot/v1.3.3; http://www.majestic12.co.uk/bot.php?+)
Agent Type: bot
Bot Name: MJ12bot

Mozilla/5.0 (compatible; MJ12bot/v1.3.0; http://www.majestic12.co.uk/bot.php?+)
Agent Type: bot
Bot Name: MJ12bot

Mozilla/5.0 (compatible; MJ12bot/v1.2.5; http://www.majestic12.co.uk/bot.php?+)
Agent Type: bot
Bot Name: MJ12bot

Mozilla/5.0 (compatible; MJ12bot/v1.2.1; http://www.majestic12.co.uk/bot.php?+)
Agent Type: bot
Bot Name: MJ12bot

Mozilla/5.0 (compatible; MJ12bot/v1.2.4; http://www.majestic12.co.uk/bot.php?+)
Agent Type: bot
Bot Name: MJ12bot

Mozilla/5.0 (compatible; MJ12bot/v1.3.1; http://www.majestic12.co.uk/bot.php?+)
Agent Type: bot
Bot Name: MJ12bot

Mozilla/5.0 (compatible; MJ12bot/v1.2.3; http://www.majestic12.co.uk/bot.php?+)
Agent Type: bot
Bot Name: MJ12bot

Mozilla/5.0 (compatible; MJ12bot/v1.3.2; http://www.majestic12.co.uk/bot.php?+)
Agent Type: bot
Bot Name: MJ12bot

MLBot (www.metadatalabs.com/mlbot)
Agent Type: bot
Bot Name: MLBot

MLBot (www.metadatalabs.com)
Agent Type: bot
Bot Name: MLBot

MnoGoSearch/3.3.9
Agent Type: bot
Bot Name: MnoGoSearch

MnoGoSearch/3.2.37
Agent Type: bot
Bot Name: MnoGoSearch

MnoGoSearch/3.3.2
Agent Type: bot
Bot Name: MnoGoSearch

MnoGoSearch/3.3.6
Agent Type: bot
Bot Name: MnoGoSearch

MojeekBot/0.2 (archi; http://www.mojeek.com/bot.html)
Agent Type: bot
Bot Name: MojeekBot

Motoricerca-Robots.txt-Checker/1.0 (http://tool.motoricerca.info/robots-checker.phtml)
Agent Type: bot
Bot Name: Motoricerca-Robots.txt-Checker

Mozdex/0.7.2 (Mozdex; http://www.mozdex.com/bot.html; spider@mozdex.com)
Agent Type: bot
Bot Name: mozDex

Mozdex/0.7.2-dev (Mozdex; http://www.mozdex.com/bot.html; spider@mozdex.com)
Agent Type: bot
Bot Name: mozDex

Mozdex/0.7.1 (Mozdex; http://www.mozdex.com/bot.html; spider@mozdex.com)
Agent Type: bot
Bot Name: mozDex

Mozilla/5.0 (compatible; Mp3Bot/0.7; +http://mp3realm.org/mp3bot/)
Agent Type: bot
Bot Name: Mp3Bot

Mozilla/5.0 (compatible; Mp3Bot/0.4; +http://mp3realm.org/mp3bot/)
Agent Type: bot
Bot Name: Mp3Bot

MQbot metaquerier.cs.uiuc.edu/crawler
Agent Type: bot
Bot Name: MQbot

MQBOT/Nutch-0.9-dev (MQBOT Nutch Crawler; http://vwbot.cs.uiuc.edu; mqbot@cs.uiuc.edu)
Agent Type: bot
Bot Name: MQbot

MQBOT/Nutch-0.9-dev (MQBOT Nutch Crawler; http://falcon.cs.uiuc.edu; mqbot@cs.uiuc.edu)
Agent Type: bot
Bot Name: MQbot

MQBOT/Nutch-0.9-dev (MQBOT Crawler; http://falcon.cs.uiuc.edu; mqbot@cs.uiuc.edu)
Agent Type: bot
Bot Name: MQbot

msnbot/2.0b (+http://search.msn.com/msnbot.htm).
Agent Type: bot
Bot Name: MSNBot

msnbot/2.0b (+http://search.msn.com/msnbot.htm)
Agent Type: bot
Bot Name: MSNBot

msnbot-media/1.1 (+http://search.msn.com/msnbot.htm)
Agent Type: bot
Bot Name: MSNBot

msnbot/1.0 (+http://search.msn.com/msnbot.htm)
Agent Type: bot
Bot Name: MSNBot

msnbot/2.0b (+http://search.msn.com/msnbot.htm)._
Agent Type: bot
Bot Name: MSNBot

msnbot/1.1 (+http://search.msn.com/msnbot.htm)
Agent Type: bot
Bot Name: MSNBot

MSRBOT
Agent Type: bot
Bot Name: MSRBOT

MSRBOT (http://research.microsoft.com/research/sv/msrbot)
Agent Type: bot
Bot Name: MSRBOT

MSRBOT (http://research.microsoft.com/research/sv/msrbot/
Agent Type: bot
Bot Name: MSRBOT

MSRBOT (http://research.microsoft.com/research/sv/msrbot/)
Agent Type: bot
Bot Name: MSRBOT

multicrawler (+http://sw.deri.org/2006/04/multicrawler/robots.html)
Agent Type: bot
Bot Name: MultiCrawler

Mozilla/4.0 (compatible; MyFamilyBot/1.0; http://www.myfamilyinc.com)
Agent Type: bot
Bot Name: MyFamilyBot

mozilla/4.0 (compatible; myfamilybot/1.0; http://www.ancestry.com/learn/bot.aspx)
Agent Type: bot
Bot Name: MyFamilyBot

Mozilla/4.0 (compatible; MyFamilyBot/1.0; http://www.ancestry.com/learn/bot.aspx)
Agent Type: bot
Bot Name: MyFamilyBot

Mozilla/5.0 (compatible; Najdi.si/3.1)
Agent Type: bot
Bot Name: Najdi.si

Yeti/1.0 (NHN Corp.; http://help.naver.com/robots/)
Agent Type: bot
Bot Name: NaverBot

Mozilla/4.0 (compatible; NaverBot/1.0; http://help.naver.com/customer_webtxt_02.jsp)
Agent Type: bot
Bot Name: NaverBot

navissobot/1.7  (+http://navisso.com/)
Agent Type: bot
Bot Name: navissobot

nestReader/0.2 (discovery; http://echonest.com/reader.shtml; reader at echonest.com)
Agent Type: bot
Bot Name: nestReader

Netintelligence LiveAssessment - www.netintelligence.com
Agent Type: bot
Bot Name: Netintelligence LiveAssessment

nrsbot/5.0(loopip.com/robot.html)
Agent Type: bot
Bot Name: NetResearchServer

nrsbot/6.0(loopip.com/robot.html)
Agent Type: bot
Bot Name: NetResearchServer

NetWhatCrawler/0.06-dev (NetWhatCrawler from NetWhat.com; http://www.netwhat.com; support@netwhat.com)
Agent Type: bot
Bot Name: NetWhatCrawler

NextGenSearchBot 1 (for information visit http://about.zoominfo.com/About/NextGenSearchBot.aspx)
Agent Type: bot
Bot Name: NextGenSearchBot

NextGenSearchBot 1 (for information visit http://www.zoominfo.com/About/misc/NextGenSearchBot.aspx)
Agent Type: bot
Bot Name: NextGenSearchBot

Mozilla/5.0 (compatible; nextthing.org/1.0; +http://www.nextthing.org/bot)
Agent Type: bot
Bot Name: nextthing.org

NG/2.0
Agent Type: bot
Bot Name: NG

NG-Search/0.9.8 (NG-SearchBot; http://www.ng-search.com)
Agent Type: bot
Bot Name: NG-Search

NG-Search/0.90 (NG-SearchBot; http://www.ng-search.com;  )
Agent Type: bot
Bot Name: NG-Search

Mozilla/5.0 (Windows;) NimbleCrawler 1.12 obeys UserAgent NimbleCrawler For problems contact: crawler@healthline.com
Agent Type: bot
Bot Name: NimbleCrawler

Mozilla/5.0 (Windows;) NimbleCrawler 2.0.1 obeys UserAgent NimbleCrawler For problems contact: crawler@healthline.com
Agent Type: bot
Bot Name: NimbleCrawler

Mozilla/5.0 (Windows; U; Windows NT 5.0; en-US; rv:1.7.7) NimbleCrawler 1.11 obeys UserAgent NimbleCrawler For problems contact: crawler_at_dataalchemy.com
Agent Type: bot
Bot Name: NimbleCrawler

Mozilla/5.0 (Windows;) NimbleCrawler 1.13 obeys UserAgent NimbleCrawler For problems contact: crawler@healthline.com
Agent Type: bot
Bot Name: NimbleCrawler

Mozilla/5.0 (Windows;) NimbleCrawler 2.0.0 obeys UserAgent NimbleCrawler For problems contact: crawler@healthline.com
Agent Type: bot
Bot Name: NimbleCrawler

Mozilla/5.0 (Windows;) NimbleCrawler 2.0.2 obeys UserAgent NimbleCrawler For problems contact: crawler@healthline.com
Agent Type: bot
Bot Name: NimbleCrawler

Mozilla/5.0 (Windows;) NimbleCrawler 1.15 obeys UserAgent NimbleCrawler For problems contact: crawler@healthline.com
Agent Type: bot
Bot Name: NimbleCrawler

Mozilla/5.0 (Windows;) NimbleCrawler 1.14 obeys UserAgent NimbleCrawler For problems contact: crawler@healthline.com
Agent Type: bot
Bot Name: NimbleCrawler

nodestackbot/0.1 (bot@nodestack.com http://nodestack.com/bot.html)
Agent Type: bot
Bot Name: nodestackbot

noyona_0_1
Agent Type: bot
Bot Name: noyona

NPBot/3 (NPBot; http://www.nameprotect.com; npbot@nameprotect.com)
Agent Type: bot
Bot Name: NPBot

Nuhk/2.4 ( http://www.neti.ee/cgi-bin/abi/Otsing/Nuhk/)
Agent Type: bot
Bot Name: Nuhk

Nusearch Spider (www.nusearch.com)
Agent Type: bot
Bot Name: NuSearch Spider

NuSearch Spider (compatible; MSIE 6.0)
Agent Type: bot
Bot Name: NuSearch Spider

heeii/Nutch-0.9-dev (heeii.com; www.heeii.com; nutch at heeii.com)
Agent Type: bot
Bot Name: Nutch

NutchCVS/0.8-dev (Nutch; http://lucene.apache.org/nutch/bot.html; nutch-agent@lucene.apache.org)
Agent Type: bot
Bot Name: Nutch

NutchCVS/0.06-dev (http://www.nutch.org/docs/en/bot.html; rhwarren+nutch@uwaterloo.ca)
Agent Type: bot
Bot Name: Nutch

NutchCVS/0.7 (Nutch; http://lucene.apache.org/nutch/bot.html; nutch-agent@lucene.apache.org)
Agent Type: bot
Bot Name: Nutch

NutchCVS/0.7.1 (Nutch; http://www.vvdb.org; voorzitter@vvdb.org)
Agent Type: bot
Bot Name: Nutch

NutchOSU-VLIB/0.7 (Nutch; http://lucene.apache.org/nutch/bot.html; nutch-agent@lucene.apache.org)
Agent Type: bot
Bot Name: Nutch

NutchCVS/0.7.1 (Nutch; http://lucene.apache.org/nutch/bot.html; nutch-agent@lucene.apache.org)
Agent Type: bot
Bot Name: Nutch

InternetArchive/0.8-dev (Nutch; http://lucene.apache.org/nutch/bot.html; nutch-agent@lucene.apache.org)
Agent Type: bot
Bot Name: Nutch

NutchCVS/0.7.1 (Nutch running at UW; http://www.nutch.org/docs/en/bot.html; sycrawl@cs.washington.edu)
Agent Type: bot
Bot Name: Nutch

NutchCVS/0.7.1 (Nutch running at UW; http://crawlers.cs.washington.edu/; sycrawl@cs.washington.edu)
Agent Type: bot
Bot Name: Nutch

NutchCVS/0.7.1 (Nutch; http://lucene.apache.org/nutch/bot.html; raphael@unterreuth.de)
Agent Type: bot
Bot Name: Nutch

Zscho.de Crawler/Nutch-1.0-Zscho.de-semantic_patch (Zscho.de Crawler, collecting for machine learning; http://zscho.de/)
Agent Type: bot
Bot Name: Nutch

NutchCVS/0.06-dev (Nutch; http://www.nutch.org/docs/en/bot.html; nutch-agent@lists.sourceforge.net)
Agent Type: bot
Bot Name: Nutch

NutchCVS/0.8-dev (Nutch running at UW; http://www.nutch.org/docs/en/bot.html; sycrawl@cs.washington.edu)
Agent Type: bot
Bot Name: Nutch

BilgiBetaBot/0.8-dev (bilgi.com (Beta) ; http://lucene.apache.org/nutch/bot.html; nutch-agent@lucene.apache.org)
Agent Type: bot
Bot Name: Nutch

NutchCVS/Nutch-0.9 (Nutch; http://lucene.apache.org/nutch/bot.html; nutch-agent@lucene.apache.org)
Agent Type: bot
Bot Name: Nutch

HouxouCrawler/Nutch-0.9-dev (houxou.com's nutch-based crawler which serves special interest on-line communities; http://www.houxou.com/crawler; crawler at houxou dot com)
Agent Type: bot
Bot Name: Nutch

HouxouCrawler/Nutch-0.9 (houxou.com's nutch-based crawler which serves special interest on-line communities; http://www.houxou.com/crawler; crawler at houxou dot com)
Agent Type: bot
Bot Name: Nutch

HouxouCrawler/Nutch-0.8.2-dev (houxou.com's nutch-based crawler which serves special interest on-line communities; http://www.houxou.com/crawler; crawler at houxou dot com)
Agent Type: bot
Bot Name: Nutch

NutchCVS/0.7.2 (Nutch; http://lucene.apache.org/nutch/bot.html; nutch-agent@lucene.apache.org)
Agent Type: bot
Bot Name: Nutch

asked/Nutch-0.8 (web crawler; http://asked.jp; epicurus at gmail dot com)
Agent Type: bot
Bot Name: Nutch

HouxouCrawler/Nutch-0.8 (houxou.com's nutch-based crawler which serves special interest on-line communities; http://www.houxou.com/crawler; crawler at houxou dot com)
Agent Type: bot
Bot Name: Nutch

oBot
Agent Type: bot
Bot Name: oBot

Mozilla/4.0 (compatible; MSIE 5.5; Windows NT 4.0; obot)
Agent Type: bot
Bot Name: oBot

Ocelli/1.4 (http://www.globalspec.com/Ocelli)
Agent Type: bot
Bot Name: Ocelli

OmniExplorer_Bot/4.06 (+http://www.omni-explorer.com) WorldIndexer
Agent Type: bot
Bot Name: OmniExplorer_Bot

OmniExplorer_Bot/4.02 (+http://www.omni-explorer.com) WorldIndexer
Agent Type: bot
Bot Name: OmniExplorer_Bot

OmniExplorer_Bot/6.47 (+http://www.omni-explorer.com) WorldIndexer
Agent Type: bot
Bot Name: OmniExplorer_Bot

Mozilla/5.0 (compatible; OnetSzukaj/5.0; +http://szukaj.onet.pl)
Agent Type: bot
Bot Name: OnetSzukaj

Mozilla/5.0 (compatible; OnetSzukaj/5.0; +http://szukaj.onet.pl
Agent Type: bot
Bot Name: OnetSzukaj

OOZBOT/0.20 ( http://www.setooz.com/oozbot.html ; agentname at setooz dot_com )
Agent Type: bot
Bot Name: OOZBOT

OOZBOT/0.20 ( Setooz výrazný ako say-th-uuz, znamená mosty.  ; http://www.setooz.com/oozbot.html ; agentname at setooz dot_com )
Agent Type: bot
Bot Name: OOZBOT

OOZBOT/0.20 ( -- ; http://www.setooz.com/oozbot.html ; agentname at setooz dot_com )
Agent Type: bot
Bot Name: OOZBOT

Openfind data gatherer, Openbot/3.0+(robot-response@openfind.com.tw;+http://www.openfind.com.tw/robot.html)
Agent Type: bot
Bot Name: Openbot

Orbiter (+http://www.dailyorbit.com/bot.htm)
Agent Type: bot
Bot Name: Orbiter

Orgbybot/OrgbyBot v1.3 (Spider; http://orgby.com/bot/  ; Orgby.com Search Engine)
Agent Type: bot
Bot Name: OrgbyBot

Orgbybot/OrgbyBot v1.2 (Spidering the net for Orgby; http://www.orgby.com/  ; Orgby.com Search Engine)
Agent Type: bot
Bot Name: OrgbyBot

Mozilla/5.0 (compatible; OsO; http://oso.octopodus.com/abot.html)
Agent Type: bot
Bot Name: OsObot

owsBot/0.2 (owsBot; www.oneworldstreet.com; owsBot)
Agent Type: bot
Bot Name: owsBot

owsBot/0.1 (Nutch; www.oneworldstreet.com; nutch-agent@lucene.apache.org)
Agent Type: bot
Bot Name: owsBot

PageBitesHyperBot/600 (http://www.pagebites.com/)
Agent Type: bot
Bot Name: PageBitesHyperBot

page_verifier (http://www.securecomputing.com/goto/pv)
Agent Type: bot
Bot Name: page_verifier

panscient.com
Agent Type: bot
Bot Name: Panscient web crawler

Mozilla/5.0 (compatible;+ParchBot/1.0;++http://www.parchmenthill.com/search.htm)
Agent Type: bot
Bot Name: ParchBot

Pingdom GIGRIB (http://www.pingdom.com)
Agent Type: bot
Bot Name: Pingdom GIGRIB

pingdom.com_bot_version_1.4_(http://www.pingdom.com/)
Agent Type: bot
Bot Name: pingdom.com_bot

Mozilla/5.0 (compatible; Plukkie/1.2; http://www.botje.com/plukkie.htm)
Agent Type: bot
Bot Name: Plukkie

Mozilla/5.0 (compatible; Plukkie/1.1; http://www.botje.com/plukkie.htm)
Agent Type: bot
Bot Name: Plukkie

Mozilla/5.0 (compatible; Plukkie/1.3; http://www.botje.com/plukkie.htm)
Agent Type: bot
Bot Name: Plukkie

Mozilla/5.0 (compatible; Pogodak.co.yu/3.1)
Agent Type: bot
Bot Name: Pogodak.co.yu

Mozilla/5.0 (compatible; polixea.de-Robot +http://www.polixea.de)
Agent Type: bot
Bot Name: polixea.de

Pompos/1.3 http://dir.com/pompos.html
Agent Type: bot
Bot Name: Pompos

posterus (seek.se) +http://www.seek.se/studio/index.php?id=47&t=details
Agent Type: bot
Bot Name: posterus

psbot/0.1 (+http://www.picsearch.com/bot.html)
Agent Type: bot
Bot Name: psbot

Mozilla/5.0 (compatible; ptd-crawler; +http://bixolabs.com/crawler/ptd/; crawler@bixolabs.com)
Agent Type: bot
Bot Name: ptd-crawler

Qseero v1.0.0
Agent Type: bot
Bot Name: Qseero

Mozilla/5.0 (compatible; Quantcastbot/1.0; www.quantcast.com)
Agent Type: bot
Bot Name: Quantcastbot

R6_CommentReader(www.radian6.com/crawler)
Agent Type: bot
Bot Name: R6 bot

R6_FeedFetcher(www.radian6.com/crawler)
Agent Type: bot
Bot Name: R6 bot

RedBot/redbot-1.0 (Rediff.com Crawler; redbot at rediff dot com)
Agent Type: bot
Bot Name: RedBot

Robo Crawler 6.4.5 (robocrawler@bb.softbank.co.jp)
Agent Type: bot
Bot Name: Robo Crawler

Robozilla/1.0
Agent Type: bot
Bot Name: Robozilla

Ronzoobot/1.2 (http://www.ronzoo.com/about.php)
Agent Type: bot
Bot Name: Ronzoobot

Ronzoobot/1.3 (http://www.ronzoo.com/about.php)
Agent Type: bot
Bot Name: Ronzoobot

RSSMicro.com RSS/Atom Feed Robot
Agent Type: bot
Bot Name: RSSMicro.com RSS/Atom Feed Robot

Ruky-Roboter (Version: 1.06, powered by www.ruky.de +http://www.ruky.de/bot.html)
Agent Type: bot
Bot Name: Ruky-Roboter

http://domino.research.ibm.com/comm/research_projects.nsf/pages/sai-crawler.callingcard.html
Agent Type: bot
Bot Name: SAI Crawler

SanszBot/1.7(http://www.sansz.org/sanszbot, spider@sansz.org) (spider@sansz.org)
Agent Type: bot
Bot Name: SanszBot

SBIder/0.8-dev (SBIder; http://www.sitesell.com/sbider.html; http://support.sitesell.com/contact-support.html)
Agent Type: bot
Bot Name: SBIder

SBIder/0.7 (SBIder; http://www.sitesell.com/sbider.html; http://support.sitesell.com/contact-support.html)
Agent Type: bot
Bot Name: SBIder

SBIder/SBIder-0.8.2-dev (http://www.sitesell.com/sbider.html)
Agent Type: bot
Bot Name: SBIder

Mozilla/5.0 (compatible; SecretSerachEngineLabs.com-SBSearch/0.9; http://www.secretsearchenginelabs.com/secret-web-crawler.php)
Agent Type: bot
Bot Name: SBSearch

Mozilla/5.0 (compatible; Scarlett/ 1.0; +http://www.ellerdale.com/crawler.html)
Agent Type: bot
Bot Name: Scarlett

schibstedsokbot (compatible; Mozilla/5.0; MSIE 5.0; FAST FreshCrawler 6; +http://www.schibstedsok.no/bot/)
Agent Type: bot
Bot Name: schibstedsokbot

Mozilla/3.0 (compatible; ScollSpider; http://www.webwobot.com)
Agent Type: bot
Bot Name: ScollSpider

Scooter/3.3
Agent Type: bot
Bot Name: Scooter

Mozilla/5.0 (compatible; ScoutJet; +http://www.scoutjet.com/)
Agent Type: bot
Bot Name: ScoutJet

Mozilla/5.0 (compatible; ScoutJet; http://www.scoutjet.com/)
Agent Type: bot
Bot Name: ScoutJet

Search Engine World Robots.txt Validator at http://www.searchengineworld.com/cgi-bin/robotcheck.cgi
Agent Type: bot
Bot Name: Search Engine World Robots.txt Validator

Mozilla/5.0 (compatible; Search17Bot/1.1; http://www.search17.com/bot.php)
Agent Type: bot
Bot Name: Search17Bot

Sensis Web Crawler (search_comments\at\sensis\dot\com\dot\au)
Agent Type: bot
Bot Name: Sensis Web Crawler

Sensis Web Crawler (search_comments\\at\\sensis\\dot\\com\\dot\\au)
Agent Type: bot
Bot Name: Sensis Web Crawler

SEOENGBot/1.2 (+http://learn.seoeng.com/seoengbot.htm)
Agent Type: bot
Bot Name: SEOENGBot

SeznamBot/2.0-Test (+http://fulltext.sblog.cz/robot/)
Agent Type: bot
Bot Name: SeznamBot

SeznamBot/3.0-alpha (+http://fulltext.sblog.cz/)
Agent Type: bot
Bot Name: SeznamBot

SeznamBot/2.0 (+http://fulltext.seznam.cz/)
Agent Type: bot
Bot Name: SeznamBot

Mozilla/5.0 (compatible; Seznam screenshot-generator 2.0; +http://fulltext.sblog.cz/screenshot/)
Agent Type: bot
Bot Name: SeznamBot

SeznamBot/2.0 (+http://fulltext.sblog.cz/robot/)
Agent Type: bot
Bot Name: SeznamBot

Shelob (shelob@gmx.net)
Agent Type: bot
Bot Name: Shelob

Shim-Crawler(Mozilla-compatible; http://www.logos.ic.i.u-tokyo.ac.jp/crawler/; crawl@logos.ic.i.u-tokyo.ac.jp)
Agent Type: bot
Bot Name: Shim-Crawler

Shim-Crawler(Mozilla-compatible; http://www.logos.ic.i.u-tokyo.ac.jp/crawl/; crawl@logos.ic.i.u-tokyo.ac.jp)
Agent Type: bot
Bot Name: Shim-Crawler

ShopWiki/1.0 ( +http://www.shopwiki.com/wiki/Help:Bot)
Agent Type: bot
Bot Name: ShopWiki

silk/1.0 (+http://www.slider.com/silk.htm)/3.7
Agent Type: bot
Bot Name: silk

Silk/1.0
Agent Type: bot
Bot Name: silk

Busiversebot/v1.0 (http://www.busiverse.com/bot.php)
Agent Type: bot
Bot Name: Sirketce/Busiverse

Sirketcebot/v.01 (http://www.sirketce.com/bot.html)
Agent Type: bot
Bot Name: Sirketce/Busiverse

Mozilla/5.0 (compatible; SkreemRBot +http://skreemr.com)
Agent Type: bot
Bot Name: SkreemRBot

smart.apnoti.com Robot/v1.34 (http://smart.apnoti.com/en/aboutApnotiWebCrawler.html)
Agent Type: bot
Bot Name: smart.apnoti.com Robot

snap.com beta crawler v0
Agent Type: bot
Bot Name: snap.com

Snapbot/1.0 (Snap Shots, +http://www.snap.com)
Agent Type: bot
Bot Name: Snapbot

Snapbot/1.0 (Site Search Crawler, +http://www.snap.com)
Agent Type: bot
Bot Name: Snapbot

Snapbot/1.0
Agent Type: bot
Bot Name: Snapbot

Mozilla/5.0 (compatible; SnapPreviewBot; en-US; rv:1.8.0.9) Gecko/20061206 Firefox/1.5.0.9
Agent Type: bot
Bot Name: SnapBot

Snapbot/1.0 (+http://www.snap.com)
Agent Type: bot
Bot Name: Snapbot

Snappy/1.1 ( http://www.urltrends.com/ )
Agent Type: bot
Bot Name: Snappy

SniffRSS/0.5beta (+http://www.blogator.com/)
Agent Type: bot
Bot Name: SniffRSS

Sogou web spider/4.0(+http://www.sogou.com/docs/help/webmasters.htm#07)
Agent Type: bot
Bot Name: Sogou

Sogou develop spider/4.0(+http://www.sogou.com/docs/help/webmasters.htm#07)
Agent Type: bot
Bot Name: Sogou

Sogou web spider/3.0(+http://www.sogou.com/docs/help/webmasters.htm#07)
Agent Type: bot
Bot Name: sogou spider

sogou spider
Agent Type: bot
Bot Name: sogou spider

sogou web spider http://www.sogou.com/docs/help/webmasters.htm#07
Agent Type: bot
Bot Name: sogou spider

sogou web spider(+http://www.sogou.com/docs/help/webmasters.htm#07)
Agent Type: bot
Bot Name: sogou spider

Sosospider+(+http://help.soso.com/webspider.htm)
Agent Type: bot
Bot Name: Sosospider

Mozilla/5.0 (compatible; spbot/1.0; +http://www.seoprofiler.com/bot/ )
Agent Type: bot
Bot Name: spbot

Mozilla/5.0 (compatible; spbot/2.0.3; +http://www.seoprofiler.com/bot/ )
Agent Type: bot
Bot Name: spbot

Mozilla/5.0 (compatible; spbot/1.2; +http://www.seoprofiler.com/bot/ )
Agent Type: bot
Bot Name: spbot

Mozilla/5.0 (compatible; spbot/2.0; +http://www.seoprofiler.com/bot/ )
Agent Type: bot
Bot Name: spbot

Mozilla/5.0 (compatible; spbot/1.1; +http://www.seoprofiler.com/bot/ )
Agent Type: bot
Bot Name: spbot

Mozilla/5.0 (compatible; spbot/2.0.1; +http://www.seoprofiler.com/bot/ )
Agent Type: bot
Bot Name: spbot

Mozilla/5.0 (compatible; spbot/2.0.4; +http://www.seoprofiler.com/bot )
Agent Type: bot
Bot Name: spbot

Mozilla/5.0 (compatible; spbot/2.0.2; +http://www.seoprofiler.com/bot/ )
Agent Type: bot
Bot Name: spbot

Speedy Spider (http://www.entireweb.com/about/search_tech/speedy_spider/)
Agent Type: bot
Bot Name: Speedy

Speedy Spider (Entireweb; Beta/1.2; http://www.entireweb.com/about/search_tech/speedyspider/)
Agent Type: bot
Bot Name: Speedy

Mozilla/5.0 (compatible; Speedy Spider; http://www.entireweb.com/about/search_tech/speedy_spider/)
Agent Type: bot
Bot Name: Speedy

Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.2.1; aggregator:Spinn3r (Spinn3r 3.1); http://spinn3r.com/robot) Gecko/20021130
Agent Type: bot
Bot Name: Spinn3r

Mozilla/5.0 (X11; U; Linux x86_64; en-US; rv:1.9.0.19; aggregator:Spinn3r (Spinn3r 3.1); http://spinn3r.com/robot) Gecko/2010040121 Firefox/3.0.19
Agent Type: bot
Bot Name: Spinn3r

Spock Crawler (http://www.spock.com/crawler)
Agent Type: bot
Bot Name: Spock Crawler

SpokeSpider/1.0 (http://support.spoke.com/webspider/) Mozilla/5.0 (not really)
Agent Type: bot
Bot Name: SpokeSpider

sproose/0.1-alpha (sproose crawler; http://www.sproose.com/bot.html; crawler@sproose.com)
Agent Type: bot
Bot Name: sproose

sproose/0.1 (sproose bot; http://www.sproose.com/bot.html; crawler@sproose.com)
Agent Type: bot
Bot Name: sproose

sproose/1.0beta (sproose bot; http://www.sproose.com/bot.html; crawler@sproose.com)
Agent Type: bot
Bot Name: Sproose

SrevBot/2.0 (SrevBot; http://winsrev.com/bot.html; bot@winsrev.com)
Agent Type: bot
Bot Name: SrevBot

SrevBot/1.2 (SrevBot; http://winsrev.com/bot.html; bot@winsrev.comg)
Agent Type: bot
Bot Name: SrevBot

Mozilla/5.0 (compatible; SSLBot/1.0;  http://www.sslstats.com/sslbot)
Agent Type: bot
Bot Name: SSLBot

StackRambler/2.0 (MSIE incompatible)
Agent Type: bot
Bot Name: StackRambler

StatoolsBot (+http://www.statools.com/bot.html)
Agent Type: bot
Bot Name: StatoolsBot

Steeler/3.2 (http://www.tkl.iis.u-tokyo.ac.jp/~crawler/)
Agent Type: bot
Bot Name: Steeler

Mozilla/5.0 (compatible; Steeler/3.5; http://www.tkl.iis.u-tokyo.ac.jp/~crawler/)
Agent Type: bot
Bot Name: Steeler

Steeler/3.3 (http://www.tkl.iis.u-tokyo.ac.jp/~crawler/)
Agent Type: bot
Bot Name: Steeler

Stroke.cz (http://stroke.cz)
Agent Type: bot
Bot Name: Strokebot

Surphace Scout&v4.0 - scout at surphace dot com
Agent Type: bot
Bot Name: Surphace Scout

SurveyBot/2.3 (Whois Source)
Agent Type: bot
Bot Name: SurveyBot

SygolBot http://www.sygol.com
Agent Type: bot
Bot Name: SygolBot

SynooBot (compatible; Synoobot/0.7.1; http://www.synoo.com/search/bot.html)
Agent Type: bot
Bot Name: SynooBot

SynooBot/0.7.1 (SynooBot; http://www.synoo.de/bot.html; webmaster@synoo.com)
Agent Type: bot
Bot Name: SynooBot

Szukacz/1.5 (robot; www.szukacz.pl/html/jak_dziala_robot.html; info@szukacz.pl)
Agent Type: bot
Bot Name: Szukacz

Szukacz/1.5 (robot; www.szukacz.pl/jakdzialarobot.html; info@szukacz.pl)
Agent Type: bot
Bot Name: Szukacz

Szukankobot /1.0 (+http://www.szukanko.pl/addurl.php)
Agent Type: bot
Bot Name: Szukankobot

Mozilla/5.0 (compatible; Tagoobot/3.0; +http://www.tagoo.ru)
Agent Type: bot
Bot Name: Tagoobot

taptubot *** please read http://www.taptu.com/corp/taptubot ***
Agent Type: bot
Bot Name: taptubot

Technoratibot/8.0
Agent Type: bot
Bot Name: Technoratibot

Technoratibot/7.0
Agent Type: bot
Bot Name: Technoratibot

TeragramCrawler
Agent Type: bot
Bot Name: TeragramCrawler

textractor.harvester/h34/1.0 (+http://ufal.mff.cuni.cz/project/textractor/, textractor@ufal.mff.cuni.cz)
Agent Type: bot
Bot Name: textractor

textractor.harvester/h12/1.0 (+http://ufal.mff.cuni.cz/project/textractor/, textractor@ufal.mff.cuni.cz)
Agent Type: bot
Bot Name: textractor

textractor.harvester/h3/1.0 (+http://ufal.mff.cuni.cz/project/textractor/, textractor@ufal.mff.cuni.cz)
Agent Type: bot
Bot Name: textractor

textractor.harvester/h5/1.0 (+http://ufal.mff.cuni.cz/project/textractor/, textractor@ufal.mff.cuni.cz)
Agent Type: bot
Bot Name: textractor

textractor.harvester/h7/1.0 (+http://ufal.mff.cuni.cz/project/textractor/, textractor@ufal.mff.cuni.cz)
Agent Type: bot
Bot Name: textractor

textractor.harvester/h2/1.0 (+http://ufal.mff.cuni.cz/project/textractor/, textractor@ufal.mff.cuni.cz)
Agent Type: bot
Bot Name: textractor

textractor.harvester/h27/1.0 (+http://ufal.mff.cuni.cz/project/textractor/, textractor@ufal.mff.cuni.cz)
Agent Type: bot
Bot Name: textractor

textractor.harvester/h38/1.0 (+http://ufal.mff.cuni.cz/project/textractor/, textractor@ufal.mff.cuni.cz)
Agent Type: bot
Bot Name: textractor

textractor.harvester/h24/1.0 (+http://ufal.mff.cuni.cz/project/textractor/, textractor@ufal.mff.cuni.cz)
Agent Type: bot
Bot Name: textractor

textractor.queuekeeper/0.1 (+http://ufal.mff.cuni.cz/project/textractor/, textractor@ufal.mff.cuni.cz)
Agent Type: bot
Bot Name: textractor

textractor.harvester/h39/1.0 (+http://ufal.mff.cuni.cz/project/textractor/, textractor@ufal.mff.cuni.cz)
Agent Type: bot
Bot Name: textractor

textractor.harvester/h37/1.0 (+http://ufal.mff.cuni.cz/project/textractor/, textractor@ufal.mff.cuni.cz)
Agent Type: bot
Bot Name: textractor

Mozilla/5.0 (compatible; Theophrastus/2.0; +http://users.cs.cf.ac.uk/N.A.Smith/theophrastus.php)
Agent Type: bot
Bot Name: Theophrastus

Thumbnail.CZ robot 1.1 (http://thumbnail.cz/why-no-robots-txt.html)
Agent Type: bot
Bot Name: Thumbnail.CZ robot

ThumbShots-Bot (+http://thumbshots.in/bot.html)
Agent Type: bot
Bot Name: ThumbShots-Bot

thumbshots-de-Bot (Version: 1.02, powered by www.thumbshots.de)
Agent Type: bot
Bot Name: thumbshots-de-Bot

TinEye/1.0; +http://www.tineye.com/
Agent Type: bot
Bot Name: TinEye

TinEye/1.1 (http://tineye.com/crawler.html)
Agent Type: bot
Bot Name: TinEye

Mozilla/5.0 (compatible; Topicbot/12.0rc-2; +http://topicbot.awardspace.us/)
Agent Type: bot
Bot Name: Topicbot

Mozilla/4.0 (Toread-Crawler/1.1; +http://news.toread.cc/crawler.php)
Agent Type: bot
Bot Name: Toread-Crawler

Touche (+http://www.touche.com.ve)
Agent Type: bot
Bot Name: Touche

TurnitinBot/2.1 (http://www.turnitin.com/robot/crawlerinfo.html)
Agent Type: bot
Bot Name: TurnitinBot

TurnitinBot/2.0 (http://www.turnitin.com/robot/crawlerinfo.html)
Agent Type: bot
Bot Name: TurnitinBot

TutorGigBot/1.5 ( +http://www.tutorgig.info )
Agent Type: bot
Bot Name: TutorGigBot

TwengaBot/1.1 (+http://www.twenga.com/bot.html)
Agent Type: bot
Bot Name: TwengaBot

TwengaBot-Discover (http://www.twenga.fr/bot-discover.html)
Agent Type: bot
Bot Name: TwengaBot

Mozilla/5.0 (Twiceler-0.9 http://www.cuil.com/twiceler/robot.html)
Agent Type: bot
Bot Name: Twiceler

Twiceler-0.9 http://www.cuill.com/twiceler/robot.html
Agent Type: bot
Bot Name: Twiceler

updated/0.1-beta (updated; http://www.updated.com; crawler@updated.com)
Agent Type: bot
Bot Name: updated

updated/0.1-alpha (updated crawler; http://www.updated.com; crawler@updated.com)
Agent Type: bot
Bot Name: updated

UptimeDog Robot (www.uptimedog.com)
Agent Type: bot
Bot Name: UptimeDog

urlfan-bot/1.0; +http://www.urlfan.com/site/bot/350.html
Agent Type: bot
Bot Name: urlfan-bot

Vagabondo/3.0 (webagent at wise-guys dot nl)
Agent Type: bot
Bot Name: Vagabondo

Mozilla/4.0 (compatible;  Vagabondo/4.0Beta; webcrawler at wise-guys dot nl; http://webagent.wise-guys.nl/; http://www.wise-guys.nl/)
Agent Type: bot
Bot Name: Vagabondo

Mozilla/4.0 (compatible;  Vagabondo/4.0; http://webagent.wise-guys.nl/)
Agent Type: bot
Bot Name: Vagabondo

VERASYS 2k Mozilla/4.0 (compatible; en) (compatible; MSIE 6.0; Windows NT 5.2; (+ http://web.verasys.ro); SV1; Unix; .NET CLR 1.1.4322)
Agent Type: bot
Bot Name: VERASYS 2k

Mozilla/5.0 (compatible; Vermut +http://vermut.aol.com)
Agent Type: bot
Bot Name: Vermut

Vespa Crawler
Agent Type: bot
Bot Name: Vespa Crawler

Mozilla/5.0 (compatible; VideoSurf_bot +http://www.videosurf.com/bot.html)
Agent Type: bot
Bot Name: VideoSurf_bot

virus_detector (virus_harvester@securecomputing.com)
Agent Type: bot
Bot Name: virus_detector

VisBot/2.0 (Visvo.com Crawler; http://www.visvo.com/bot.html; bot@visvo.com)
Agent Type: bot
Bot Name: visbot

Visbot/1.1 (Visvo.com - The Category Search Engine!; http://www.visvo.com/bot.html; bot@visvo.com)
Agent Type: bot
Bot Name: visbot

VMBot/0.9 (VMBot; http://www.verticalmatch.com; vmbot@tradedot.com)
Agent Type: bot
Bot Name: VMBot

VMBot/0.7.2 (VMBot; http://www.VerticalMatch.com/; vmbot@tradedot.com)
Agent Type: bot
Bot Name: VMBot

void-bot/0.1 (bot@void.be; http://www.void.be/)
Agent Type: bot
Bot Name: void-bot

Mozilla/5.0 (Windows; U; Windows NT 5.1; fr; rv:1.8.1) VoilaBot BETA 1.2 (support.voilabot@orange-ftgroup.com)
Agent Type: bot
Bot Name: VoilaBot

Mozilla/4.0 (compatible; MSIE 5.0; Windows 95) VoilaBot BETA 1.2 (http://www.voila.com/)
Agent Type: bot
Bot Name: VoilaBot

VORTEX/1.2 (+http://marty.anstey.ca/robots/vortex/)
Agent Type: bot
Bot Name: VORTEX

voyager/2.0 (http://www.kosmix.com/crawler.html)
Agent Type: bot
Bot Name: voyager

voyager/1.0 (+http://www.kosmix.com/html/crawler.html)
Agent Type: bot
Bot Name: voyager

VWBOT/Nutch-0.9-dev (VWBOT Nutch Crawler; http://vwbot.cs.uiuc.edu; vwbot@cs.uiuc.edu)
Agent Type: bot
Bot Name: VWBot

Web-sniffer/1.0.31 (+http://web-sniffer.net/)
Agent Type: bot
Bot Name: Web-sniffer

WebAlta Crawler/1.3.34 (http://www.webalta.net/ru/about_webmaster.html) (Windows; U; Windows NT 5.1; ru-RU)
Agent Type: bot
Bot Name: WebAlta Crawler

WebAlta Crawler/1.3.33 (http://www.webalta.net/ru/about_webmaster.html) (Windows; U; Windows NT 5.1; ru-RU)
Agent Type: bot
Bot Name: WebAlta Crawler

WebarooBot (Webaroo Bot; http://www.webaroo.com/rooSiteOwners.html)
Agent Type: bot
Bot Name: WebarooBot

WebarooBot (Webaroo Bot; http://64.124.122.252/feedback.html)
Agent Type: bot
Bot Name: WebarooBot

WebMiner (Web Miner; http://64.124.122.252/feedback.html)
Agent Type: bot
Bot Name: WebarooBot

RufusBot (Rufus Web Miner; http://64.124.122.252/feedback.html)
Agent Type: bot
Bot Name: WebarooBot

WebImages 0.3 ( http://herbert.groot.jebbink.nl/?app=WebImages )
Agent Type: bot
Bot Name: WebImages

mozilla/5.0 (compatible; webmastercoffee/0.7; +http://webmastercoffee.com/about)
Agent Type: bot
Bot Name: webmastercoffee

WebRankSpider/1.37 (+http://ulm191.server4you.de/crawler/)
Agent Type: bot
Bot Name: WebRankSpider

Webscope/Nutch-0.9-dev (http://www.cs.washington.edu/homes/mjc/agent.html)
Agent Type: bot
Bot Name: Webscope Crawler

wectar/Nutch-0.9 (nectar extracted form the glorious web; http://goosebumps4all.net/wectar; see website)
Agent Type: bot
Bot Name: wectar

wectar/Nutch-0.9 (wectar - wectar extracted from the glorious web; http://goosebumps4all.net/wectar)
Agent Type: bot
Bot Name: wectar

Willow Internet Crawler by Twotrees V2.1
Agent Type: bot
Bot Name: Willow Internet Crawler

WinkBot/0.06 (Wink.com search engine web crawler; http://www.wink.com/Wink:WinkBot; winkbot@wink.com)
Agent Type: bot
Bot Name: WinkBot

WinWebBot/1.0; (Balaena Ltd, UK); http://www.balaena.com/winwebbot.html; winwebbot@balaena.com;)
Agent Type: bot
Bot Name: WinWebBot

WIRE/0.10 (Linux; i686; Bot,Robot,Spider,Crawler)
Agent Type: bot
Bot Name: WIRE

WIRE/0.11 (Linux; i686; Robot,Spider,Crawler,aromano@cli.di.unipi.it)
Agent Type: bot
Bot Name: WIRE

WIRE/0.11 (Linux; i686; Bot,Robot,Spider,Crawler,aromano@cli.di.unipi.it)
Agent Type: bot
Bot Name: WIRE

WMCAI-robot (http://www.topicmaster.jp/wmcai/crawler.html)
Agent Type: bot
Bot Name: WMCAI_robot

Mozilla/5.0 (compatible; woriobot +http://worio.com)
Agent Type: bot
Bot Name: woriobot

www.fi crawler, contact crawler@www.fi
Agent Type: bot
Bot Name: www.fi crawler

wwwster/1.4 (Beta, mailto:gue@cis.uni-muenchen.de)
Agent Type: bot
Bot Name: wwwster

Mozilla/5.0 (compatible; XmarksFetch/1.0; +http://www.xmarks.com/about/crawler; info@xmarks.com)
Agent Type: bot
Bot Name: XmarksFetch

Mozilla/5.0 (compatible; XML Sitemaps Generator; http://www.xml-sitemaps.com) Gecko XML-Sitemaps/1.0
Agent Type: bot
Bot Name: XML Sitemaps Generator

XML Sitemaps Generator 1.0
Agent Type: bot
Bot Name: XML Sitemaps Generator

Yaanb/1.5.001 (compatible; Win64;+http://www.yaanb.com/company/bot.hmtl)
Agent Type: bot
Bot Name: Yaanb

Yaanb/1.5.001 (compatible; Win64;)
Agent Type: bot
Bot Name: Yaanb

yacybot (x86 Windows 2003 5.2; java 1.6.0_16; Europe/de) http://yacy.net/bot.html
Agent Type: bot
Bot Name: yacybot

yacybot (i386 Linux 2.6.28-13-generic; java 1.6.0_13; Europe/en) http://yacy.net/bot.html
Agent Type: bot
Bot Name: yacybot

yacybot (amd64 Linux 2.6.26-2-amd64; java 1.6.0_0; Europe/en) http://yacy.net/bot.html
Agent Type: bot
Bot Name: yacybot

yacybot (x86 Windows Vista 6.1; java 1.6.0_13; Europe/de) http://yacy.net/bot.html
Agent Type: bot
Bot Name: yacybot

yacybot (amd64 Linux 2.6.24-23-generic; java 1.6.0_07; Europe/de) http://yacy.net/bot.html
Agent Type: bot
Bot Name: yacybot

yacybot (i386 Linux 2.6.26-2-686; java 1.6.0_0; Europe/de) http://yacy.net/bot.html
Agent Type: bot
Bot Name: yacybot

yacybot (x86 Windows 2003 5.2; java 1.6.0_20; America/de) http://yacy.net/bot.html
Agent Type: bot
Bot Name: yacybot

yacybot (amd64 Linux 2.6.26-2-openvz-amd64; java 1.6.0_12; UTC/en) http://yacy.net/bot.html
Agent Type: bot
Bot Name: yacybot

yacybot (amd64 Linux 2.6.32-gentoo; java 1.6.0_17; Europe/en) http://yacy.net/bot.html
Agent Type: bot
Bot Name: yacybot

yacybot (amd64 Linux 2.6.26-2-amd64; java 1.6.0_20; Europe/en) http://yacy.net/bot.html
Agent Type: bot
Bot Name: yacybot

yacybot (i386 Linux 2.6.31-18-generic; java 1.6.0_0; Europe/en) http://yacy.net/bot.html
Agent Type: bot
Bot Name: yacybot

yacybot (i386 Linux 2.6.23; java 1.6.0_17; Europe/en) http://yacy.net/bot.html
Agent Type: bot
Bot Name: yacybot

yacybot (x86 Windows XP 5.1; java 1.6.0_18; Europe/de) http://yacy.net/bot.html
Agent Type: bot
Bot Name: yacybot

yacybot (amd64 Windows 7 6.1; java 1.6.0_14; Europe/de) http://yacy.net/bot.html
Agent Type: bot
Bot Name: yacybot

yacybot (amd64 Linux 2.6.18-164.el5; java 1.6.0; Europe/de) http://yacy.net/bot.html
Agent Type: bot
Bot Name: yacybot

yacybot (i386 Linux 2.6.23; java 1.6.0_06; Europe/en) http://yacy.net/bot.html
Agent Type: bot
Bot Name: yacybot

yacybot (i386 Linux 2.6.31-21-generic; java 1.6.0_0; Europe/en) http://yacy.net/bot.html
Agent Type: bot
Bot Name: yacybot

yacybot (i386 Linux 2.6.30-2-686; java 1.6.0_0; SystemV/en) http://yacy.net/bot.html
Agent Type: bot
Bot Name: yacybot

yacybot (i386 Linux 2.6.32-22-generic; java 1.6.0_20; Europe/de) http://yacy.net/bot.html
Agent Type: bot
Bot Name: yacybot

yacybot (i386 Linux 2.6.24-23-generic; java 1.6.0_16; Europe/en) http://yacy.net/bot.html
Agent Type: bot
Bot Name: yacybot

yacybot (amd64 Linux 2.6.28-18-generic; java 1.6.0_16; GMT/en) http://yacy.net/bot.html
Agent Type: bot
Bot Name: yacybot

yacybot (i386 Linux 2.6.28-gentoo-r5; java 1.5.0_18; Europe/en) http://yacy.net/bot.html
Agent Type: bot
Bot Name: yacybot

yacybot (i386 Linux 2.6.28-11-generic; java 1.6.0_13; Europe/de) http://yacy.net/bot.html
Agent Type: bot
Bot Name: yacybot

Mozilla/5.0 (compatible; Yahoo! Slurp/3.0; http://help.yahoo.com/help/us/ysearch/slurp)
Agent Type: bot
Bot Name: Yahoo!

Mozilla/5.0 (compatible; Yahoo! Slurp; http://help.yahoo.com/help/us/ysearch/slurp)
Agent Type: bot
Bot Name: Yahoo!

Mozilla/5.0 (compatible; Yahoo! Slurp China; http://misc.yahoo.com.cn/help.html)
Agent Type: bot
Bot Name: Yahoo!

Mozilla/5.0 (Yahoo-MMCrawler/4.0; mailto:vertical-crawl-support@yahoo-inc.com)
Agent Type: bot
Bot Name: Yahoo!

Y!J-BRI/0.0.1 crawler ( http://help.yahoo.co.jp/help/jp/search/indexing/indexing-15.html )
Agent Type: bot
Bot Name: Yahoo! JAPAN

Y!J-BSC/1.0 (http://help.yahoo.co.jp/help/jp/blog-search/)
Agent Type: bot
Bot Name: Yahoo! JAPAN

YandexSomething/1.0
Agent Type: bot
Bot Name: YandexBot

Yandex/1.01.001 (compatible; Win16; P)
Agent Type: bot
Bot Name: YandexBot

Yandex/1.01.001 (compatible; Win16; I)
Agent Type: bot
Bot Name: YandexBot

Mozilla/5.0 (compatible; YandexBot/3.0; +http://yandex.com/bots)
Agent Type: bot
Bot Name: YandexBot

Mozilla/5.0 (compatible; YandexImages/3.0; +http://yandex.com/bots)
Agent Type: bot
Bot Name: YandexBot

Mozilla/5.0 (compatible; YandexBot/3.0; MirrorDetector; +http://yandex.com/bots)
Agent Type: bot
Bot Name: YandexBot

Mozilla/5.0 (compatible; YandexWebmaster/2.0; +http://yandex.com/bots)
Agent Type: bot
Bot Name: YandexBot

Yandex/1.01.001 (compatible; Win16; m)
Agent Type: bot
Bot Name: YandexBot

Yandex/1.01.001 (compatible; Win16; H)
Agent Type: bot
Bot Name: YandexBot

Yanga WorldSearch Bot v1.1/beta (http://www.yanga.co.uk/)
Agent Type: bot
Bot Name: Yanga

YodaoBot/1.0 (http://www.yodao.com/help/webmaster/spider/; )
Agent Type: bot
Bot Name: YodaoBot

Mozilla/5.0 (compatible; YodaoBot/1.0; http://www.yodao.com/help/webmaster/spider/; )
Agent Type: bot
Bot Name: YodaoBot

Mozilla/5.0 (compatible;YodaoBot-Image/1.0;http://www.youdao.com/help/webmaster/spider/;)
Agent Type: bot
Bot Name: YodaoBot

Mozilla/5.0 (compatible; Yoono; http://www.yoono.com/)
Agent Type: bot
Bot Name: Yoono Bot

Mozilla/5.0 (compatible; YoudaoBot/1.0; http://www.youdao.com/help/webmaster/spider/; )
Agent Type: bot
Bot Name: YoudaoBot

YowedoBot/Yowedo 1.0 (Search Engine crawler for yowedo.com; http://yowedo.com/en/partners.html; crawler@yowedo.com)
Agent Type: bot
Bot Name: YowedoBot

ZACATEK_CZ_BOT (www.zacatek.cz)
Agent Type: bot
Bot Name: ZACATEK_CZ

Zeusbot/0.07 (Ulysseek's web-crawling robot; http://www.zeusbot.com; agent@zeusbot.com)
Agent Type: bot
Bot Name: Zeusbot

Zookabot/2.0;++http://zookabot.com
Agent Type: bot
Bot Name: Zookabot

ZoomSpider - wrensoft.com [ZSEBOT]
Agent Type: bot
Bot Name: ZoomSpider (ZSEBOT)

Mozilla/4.0 compatible ZyBorg/1.0 (wn-14.zyborg@looksmart.net; http://www.WISEnutbot.com)
Agent Type: bot
Bot Name: ZyBorg

Mozilla/4.0 compatible ZyBorg/1.0 Dead Link Checker (wn.dlc@looksmart.net; http://www.WISEnutbot.com)
Agent Type: bot
Bot Name: ZyBorg

Mozilla/4.0 compatible ZyBorg/1.0 (wn-16.zyborg@looksmart.net; http://www.WISEnutbot.com)
Agent Type: bot
Bot Name: ZyBorg

^Nail (http://CaretNail.com)
Agent Type: bot
Bot Name: ^Nail

